tree.yml

* Adds the new B9 Procedural Wings into START node like existing pWings.
* Moves FASA launch apparatus to START with the exception of the full fledged tower.  This allows use of clamps and umbilicals early on to avoid boil off issues.
* Sorted Stock Launch Clamp along with FASA clamps

Add B9 proc wings.  Rearrange FASA launch apparatus

---

tree.yml

Remove engine from ORPHANS and add to giganticRocketry.
When I updated RP-0 to 0.21 I noticed RS-68A wasn't available. I have added it to giganticRocketry (TL7 present day) because it  was certified for use on Delta IV in December 2001.

Update AIES engine VR1vulcan (RS-68A)

---

GameData/RP-0/VSR_Engines.cfg

Yes I named my branch wrong.
This adds the AJ10-104D, the main engine used in Able Star launches.
ref: http://space.skyrocket.de/doc_lau/thor_ablestar.htm
Also a quick fix to the Isp of the -142

Add AJ10-104D

---

tree.yml

Currently for the radial decouplers and 6S tubes. These things have
crazy default costs compared to companion parts with the same purpose.

Moar costings for moar parts.

---

tree.yml

Some UniversalStorage parts had dots in their names when they should
have been underscores.
Part of #56.

Fix periods in part names.

---

tree.yml

For starting tech:
- Wings now all cost 10.
- Scoops cost 20.
- Structural Pylon reduced from 50 to 20.
- SXTSmallFuselage costed at 20.
- Ladders and starting lights cost 10.
- Starting tanks cost 30.
Thse prices can and probably should be tweaked further, so I believe
that this changes mean that we're more correct than we previously were.
*Totally* happy with this being merged and then some prices adjusted.
For #90.

Made a bunch of common parts cheap!

---

GameData/RP-0/CTTChanges.cfg

- Orbital Surveys and advanced sensors match nearby nodes in
positioning.
- Fixed missing `@` on start of advSurveys node.
- Recycling moved so the tech tree no longer goes *backwards*.

Fix misplaced or broken nodes in tech tree.

---

GameData/RP-0/CTTChanges.cfg
GameData/RP-0/Hydrolox.cfg
tree.yml

This PR adds a dedicated line of hydrolox nodes to the tech tree, from `hydroloxTL2` to `hydroloxTL7`. They fit near the top of the tree, and don't overlap with any other nodes.
Features:
- We no longer hijack the construction line, so dependencies make more sense, and there are no more weird misplaced parts.
- All Engine Configs are updated to use the new nodes through the power of ModuleManager. Regular RO players (without the CTT) are unaffected.
- `Tree.cfg` has the new nodes added.
- Tested. Oh goodness. So many hours of waiting for KSP to reload.
- New nodes have placeholder text and costs. Feel free to update these as appropriate.
- The PR branch is in the RP-0 repo, so any contributor can add to it. *Please do so* if you feel a change is required before this is merge-ready.
Closes …

Create dedicated hydrolox nodes.

---

GameData/RP-0/ExperimentAdder.cfg
GameData/RP-0/PartHacks.cfg
tree.yml

The old Geiger Counter experiment is no more.
This means that players with FASA installed don't get a buttload more
science, but they do have a cool alternative to putting a big sphere on
their craft. :)
Includes #119, to avoid merge conflicts.

FASA Geiger Counter now does X-rays instead.

---

tree.yml

These engines were in the RD0120 part folder and I did not see them earlier.  Sorry about that.

RD270 & RD270M

---

GameData/RP-0/PartHacks.cfg
tree.yml

- Stack goo weighs the same as radial goo.
- Stack and wedge goo cost the same as radial goo.
Closes #91.

Goo standardisation

---

tree.yml

Via @Dasms:
> FASAlaunchClampApollo had a capitalized "L" instead of how it appears in the config with a lower case L
(I don't have FASA currently installed, so can't test this myself at the moment.)

Fix typo in FASA launch clamps

---

tree.yml

These were lost when they were used for hydrolox surrogates. I've
now returned them to their former glory.

Re-add the construction nodes back into tree.yml

---

tree.yml

All of these are just cargo bays and structural caps, so they're all cheap and in low-tech nodes.

Placed MOL structural parts

---

GameData/RP-0/PartHacks.cfg

Fix dmUSPresTemp ("Univ. Storage - PresMat / 2Hot / X-Ray") description and mass to reflect that it now has 3 science experiments onboard.

Fix DMagic USPresTemp description and mass.

---

GameData/RP-0/Contracts/Groups.cfg

Recommended for grouping in the debug menu (and a user-settings menu coming in 1.6.0).  Also allows you to put a min Contract Configurator version - use this post-release if you make a change that depends on a feature introduced in a new version of Contract Configurator, it'll save you from investigating bug reports from users that don't update the dependencies properly.

Add a high-level RP0 group

---

Source/ModuleAvionics.cs

The "Shutdown Avionics" event only updated the name to "Activate Avionics", and nothing else.

Fix bug with toggling avionics

---

GameData/RP-0/Avionics.cfg
tree.yml

Forgot a few parts from the original pull request, added those.  Also removed avionics from all probes that do not come equipped with RCS, except pioneer 5, that gets some avionics lovin.  Gave IUS 2nd stage avionics, all other probes with RCS got ~ 2x their weight in avionics to allow for a bit of extra attitude/propulsion control. 
More balance may be on the way as I get a bit of a chance to experiment in game.
https://docs.google.com/spreadsheets/d/1nSpgjnR8j-CoM71H5H9RJS2xfRVuKFtgeVRqiMn419k/edit#gid=0

US Probes/RP-0 - Added Avionics/Added missing parts

---

tree.yml

https://github.com/KSP-RO/RealismOverhaul/pull/527
Places the next SXT R-7 engines in the RP-0 tech tree, pricing copied from the versions at line 804 and line 807.
My first time editting YAML through the online Github interface, please let me know if there is any trouble.

Place SXT RD-107 & RD-108

---

GameData/RP-0/Avionics.cfg

5t is pretty exactly the weight of a Gemini spacecraft with all service modules. No room for extras.
20t should be sufficient-to-generous for MOL or lunar missions

Upgraded FASA Gemini avionics from 5t to 20t

---

tree.yml

look at page 3:
http://esto.nasa.gov/conferences/nstc2007/papers/Manzella_David_D10P2_NSTC-07-0116.pdf
"In fact more than 40mln USD in cost overruns were directly related to the ion propulsion systems xenon tank and ion thruster power sources placing the cost of the Dawn ion propulsion system at more than 50mln USD."
So 50mln USD for the xenon tank and 3 NSTAR engines? How much for one engine?

Ion engine - pricing

---

tree.yml

I found that Big Gemini development cost would be about 1,5bln USD with Titan III-M. I also found that Six-man Apollo spacecraft would cost 1bln USD (1970)  for development and 73mln USD (1970) for operatonal cost.
https://falsesteps.wordpress.com/2013/02/24/big-g-getting-to-orbit-post-apollo/ (at the bottom)
http://www.dtic.mil/dtic/tr/fulltext/u2/729770.pdf (page 42)
So I think that 1bln USD (1970) for development and 75mln USD (1970) for unit cost will be ok.

Big Gemini - pricing

---

tree.yml

http://in.rbth.com/blogs/2013/12/04/how_indias_cryogenic_programme_was_wrecked_31365
“Just then a third approach came, this time from the Soviet Union, offering two engines and technology transfer for the more reasonable price of $200 million,” writes Harvey.
https://en.m.wikipedia.org/wiki/User:Gaurav_Pruthi/KVD-1
"Later the design of the engine was sold to ISRO under the name "KVD-1" under a deal worth $120 million [8] with soviet agency Glavkosmos which enabled ISRO to import 2 KVD-1 engines and an agreement for transfer of technology from Russia."
http://isp.justthe80.com/isro-rocket-motors/isro-s-cryogenic-upper-stage-cus
"The GSLV project including the Soviet cryogenic engines was approved by the Space Commission and the GOI in October 1990. In 1991 ISRO entered into a  $120 million …

KVD1 engine - price

---

GameData/RP-0/Contracts/Human Spaceflight/Lunar Landing 1 Repeat.cfg

This change should adjust the rewards so there isn't such a huge change.  Now there is a 12.5k boost (25%) in the base reward for each additional 12hr over the minimum.

Update rewards for Lunar Landing contract

---

tree.yml

Trying to separate the various Atlas tanks into various tech nodes.  Cost value included is based on the progression from the existing tanks.
Placing two new Centaur tanks (D5 and T) into what I believe are legitimate tech nodes.

Add Atlas and Centaur tanks to tech tree

---

GameData/RP-0/Avionics.cfg

Avionics added to the Centaur D3 as well as the new D5 and T models.

Add avionics for additional centaur tanks

---

tree.yml

Both parts are the same. One models the engine as RCS, the other as an engine.

Apply pricing to the other Gemini service module

---

tree.yml

Generally, antennas will be available as soon as one has the means to power them; in most cases that's a bit earlier than in real-life history.
BEWARE: this makes the AsteroidDay mod mandatory for RP-0, as I used it's antenna for the mariner model.

Tech tree to suit the new antenna stats.

---

tree.yml

Moved to precisionPropulsion. It is showing up in the wrong node now, for some reason, even though it is an Orphan.

SXTK1BaseLarge:moved

---

tree.yml

Atlas G/H/I didn't start being used until the 80s so I've moved the Atlas H tank from Specialized Construction over to Advanced Metal Works.  Though it may actually be more accurate to wait until Nanolathing.
The Centaur-T was effectively designed specifically for the Titan IV so it makes sense to have it be introduced in the same tier as the 11A engines used on the TItan IV.  Those engines become available with Advanced Rocketry so I've put the tank in Nanolathing.
Centaur D2 doesn't get introduced until early 90s when the Atlas II starts being used.  Since the engines for the Atlas II don't become available until Experimental Rocketry, I've moved the Centaur D2 tank to Exotic Alloys to keep it in the same Tier and in a construction node.
I've moved the Centaur D3 (used on the Atlas III) …

Update tech placement for Atlas and Centaur

---

tree.yml

Titan I first stage made the same as a procedural, despite the fact that the proc (Default) is a bit lighter.
Titan I upper charged 1.5/Ton avionics (already appears set to 120) + Proc cost.

Titan I tank pricing

---

GameData/RP-0/FASA_Engines.cfg

A few more configs were added in RO without changes here. Set estimated price increases, as without these changes the new configs unlock at the same price and tech as the base one.
If someone wants to research these engine configs, they might also belong at a higher tech node unlock, although they quickly become obsolete (in my opinion) as early hydrolox is shortly unlocked afterward.

Added Bell Configs

---

GameData/RP-0/Avionics.cfg
tree.yml

Re-placed RN and Tantares R7 tanks as well as RN sputnik fairings etc to the Basic Construction node. Mercury - Atlas LV was already there so it should be ok now with the avionics restriction.

RN&Tantares R7 re-placement

---

tree.yml

Added FASAGeminiLFTLongIF tank (for Titan 3A, 3B), priced a couple percent more than Titan II tank. 200

small FASA adds

---

tree.yml

Seems I accidentally capitalized an extra letter which results in the node not being found.  This should correct it so that the Advanced Metalworks (advMetalworks) tech node gets populated with the FASA Atlas H correctly.

Correct node capitilization

---

GameData/RP-0/Contracts/Human Spaceflight/CrewedMarsFlyby.cfg

Not sure if it was done intentionally, but with the current contract you can't decline it or cancel it.  This corrects that, assuming it was a mistake in the first place.

Make CrewedMarsFlyby declinable

---

GameData/RP-0/Contracts/Human Spaceflight/CrewedVenusFlyby.cfg

Not sure if it was done intentionally, but with the current contract you can't decline it or cancel it.  This corrects that, assuming it was a mistake in the first place.

Make CrewedVenusFlyby declinable

---

GameData/RP-0/Contracts/StockContracts.cfg

I changed the "Title" section under PART_REQUEST to "Article/PartDescription/VesselDescription" which is the new syntax for 1.0.5. This should fix the bug that had contracts asking for "Part on Vessel." This is my first edit, so I hope I didn't screw up :)

Fixed "Have Part on Vessel" bug

---

tree.yml

The kestrel uses similar tech to the Merlin A1, so should belong in the same node.

place Kestrel engine alongside Merlin 1A

---

tree.yml

These are the bulk of the tech node changes discussed in issue #417.  In a few places I've also altered Cost and/or EntryCost so that duplicate parts match (i.e. SRBs from ATK have the same costs as their KW Rocketry equivalent).
Also included are tech node placement for the new parts discussed in issue #417.  This includes the AJ10Adv (118F/118K), the Atlas II tank, and the Thor/Delta avionics parts.

Update tree.yml for issue #417

---

GameData/RP-0/Avionics.cfg

Was missing from the generic probe core list.

Add HS-333 avionics

---

tree.yml

Move the AJ10-118K engine found in KW Rocketry so it appears in the tech tree at the same time as the AJ10-118K config found in SXT (SXTAJ10Adv)

Move AJ10-118K

---

tree.yml

moved to ~1969 node because 1964 seems to be too early.

RTG + Pioneer 10/11 Antenna

---

tree.yml

It appears that the "Titan II/III/IV Series Upper Stage Fuel Tank" (FASAGeminiLFTMedWhite) is missing from the tree.

Titan 2nd stage tank tree placement

---

tree.yml

Place and price the "Big G" service module, docking ring and decoupler.
There is a part listed as "FASABigGDock" which I am guessing is the "FASAGeminiBigGDock".  I didn't remove "FASABigGDock" in case I'm mistaken but I did use the cost and entry cost for FASAGeminiBigGDock.
Pricing for the docking ring is based on the price for the Apollo docking device.
Pricing for the decoupler is based on Saturn SLA.

Gemini Big G

---

GameData/RP-0/Contracts/Sounding Rocket Contracts/SoundingLow.cfg

Changed altLow to int and used integer division

Print altitude in kilometers without decimal places

---

GameData/RP-0/Contracts/Human Spaceflight/Station Crew Rotation.cfg
GameData/RP-0/Contracts/Milestones/Station.cfg

According to the Contract Configuration documentation:
If this Rendezvous parameter is a child of a VesselParameterGroup parameter, then no more than *one* vessel should be provided (the other is the vessel being tracked under the VesselParameterGroup). If no vessel attributes are provided, the second vessel will match any vessel.
Since "Rendezvous" is a PARAMETER of "VesselParameterGroup", then the second "vessel" value is not needed and appears to be disabling the contract.

Station contract fix

---

tree.yml

Look at my previous discussion with @stratochief66, he said clearly that weaker variant RD270 should be around 20% more expensive than F1 (15000).
https://github.com/KSP-RO/RP-0/pull/271

RD270 cost revision

---

tree.yml

2 parts prices combine to 4500, as suggested by @NathanKell for initial pricing. Comparable to same assembly produced through proc & existing parts.
Antenna half the price of Mariner. @NathanKell suggested making it cheaper than Mariner ant if it was heavier than Mariner's ant.

Add Tantares Venera lander & lander antenna

---

tree.yml

Voskhod chute for Tantares is identical to Vostok. So, same price and place.
We already have P&P for RN's soyuz SM, so I tagged 7 cloned that to the Tantares one.

P&P Early Soyuz SM, Voskhod chute: Tantares

---

GameData/RP-0/Contracts/Milestones/KarmanLineUncrewed.cfg

"their" was used instead of "there", and a comma was replaced with a
semicolon.

Make minor change to KarmanLineUncrewed description

---

GameData/RP-0/Contracts/SCANSat.cfg

Remove the M700 and NarrowBand scanner contracts which don't currently work since we don't yet have RO/RP-0 parts.

Update SCANsat contracts

---

GameData/RP-0/Avionics.cfg

In RO Github 1126 I'm proposing adding a FASAGeminiLFTCentarCSM_D1T (a thermal insulated version of FASAGeminiLFTCentar used on Titan 3E) and removing FASAGeminiLFTCentarCSM_D3 since Atlas IIIB didn't use it's own version of Centaur.  I'm therefore adding avionics for the first, and removing the 2nd.

Centaur Avionics

---

GameData/RP-0/EntryCostModifiers.cfg

Long explanation for this. I am studying the related unlock costs of the LR89, LR79, and LR105 engines.
The smallest issue I noticed was this one; that one LR105 had a maxEntryCost and the other didn't. The initial LR105 entry cost is 11k if neither of the other two are unlocked. When the LR89 is bought (EntryCost paid) the FASA version of the 105 drops to a 3k entry price, while the RO was at 6k. After also unlocking the LR79, FASA 105 drops to 2k, while the RO version stays the same. Removing this line aligns them.
An aside. For future planning, should/could these unlock prices be linked to the global engine config, rather than to the part name? That may not be useful, as we may be phasing out the RO clone parts in 1.1 as we can just use a good model (ie. Raidernick ones) as the …

Match RO-stock & FASA LR-105 entry costs

---

tree.yml

In RO Github 1126 I'm proposing adding FASAGeminiLFTCentarCSM_D1T to represent the insulated Centaur D-1T used on Titan 3E.  Witht he exception of the added thermal insulation, it is basically identical to the standard FASAGeminiLFTCentar so I put it in the same node and added a slight increase in cost to account for the extra insulation.
In the same Github I'm suggesting removing FASAGeminiLFTCentarCSM_D3 since Atlas IIIB did not use it's own version of the Centaur.  I've therefore removed it's entry from the tree.

Place new Centaur tank

---

GameData/RP-0/Contracts/Human Spaceflight/Lunar Landing 1 Repeat.cfg

I'm not sure if it was left in place intentionally or not but the 4th parameter is resulting in the current contract being un-finishable.  Basically it seems to be requiring that the vehicle permanently retain a destination of the Moon, which you can't do while also returning home.  Since there is already a "ReachState" setup in parameter 3 which requires you land on the Moon at a specific Biome and remain landed for a specific amount of time, I don't think there's a need for the 4th parameter at all.  So now the parameters would just be:
1) Launch a new vehicle
2) Have at least 1 crew on the vehicle
3) Land on the Moon with at least one crew, in the specified biome and for the specified duration
4) Safely return home.

Lunar Landing-Repeat

---

tree.yml

Tantares_Engine_A was placed twice, and there were duplicate tags for the PAO.

Fix funny/duplicate placement of Soyuz PAO parts

---

GameData/RP-0/Contracts/Milestones/FirstLaunch.cfg

Changes first launch contract to require the vessel to be moving upward at 1 m/s at some point. I originally set it to 0.1, but that showed as 0.0 in-game.

Tweak first launch

---

GameData/RP-0/SSTU_TechLimits.cfg

this patch is intended to set the max size for procedural or semi-procedural SSTU parts, like tanks, decouplers, fairings, interstages, it matches the ProceduralParts patches, using the very same node (NOTE: the values need to be a multiple of 0.125, as this is the default scaling for SSTU parts)
this patch is needed so these parts can actually work with RP-0 tech tree, as I said before, I copied the nodes from the Procedural Parts one, but if you want to set them on another node, feel free to change these
also, a new tech tree can be created, but I decided to replace the default SSTU one just so all parts using it would be affected, instead of going after each individual part and change, so if anyone wants to make a tech tree for tanks, one for fairings, one for decouplers, etc... all …

SSTU Tech Tree Size Limits

---

tree.yml

The tanks pricing should be fine with medium-sized tanks (aligned with PP); indeed, SSTU does not use the same pricing system and a flat and wide tanks will be less expensive than a long and thin one, for the same volume.
Decouplers are just here not to appear in the "non-RP0" section; I do not have a way to change their price (radial one is less expensive, stack one is more expensive).

SSTU Tanks and procedural decouplers

---

tree.yml

As said on the Reddit page, one node back for each engine. The next FRE update will fix engine configs pricing/placing conflicts (requested by @NathanKell )
it conflicts now, I probably left a tab somewhere.

moving FRE viking engine back

---

tree.yml

It costs the same as the Communotron 16, because while it has shorter
range, it can't break in the atmosphere and doesn't require deployment.

Add support for the Vostok antenna.

---

tree.yml

Price 750, comparable to the cheapest LR79 (S-3D) configs, since it's
largely a simplification of that engine.  H-1B pushes up to 1050 to pay
for additional reliability / man-rating, then RS-27 are cheaper again
(at 800, 825) because they're mature tech and are the inexpensive option.
No actual sources for these numbers.

Reduce cost of H-1 family (issue #490)

---

GameData/RP-0/Contracts/Fly-by Contracts/CallistoFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/DioneFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/EnceladusFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/EuropaFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/GanymedeFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/IapetusFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/IoFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/MimasFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/RheaFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/TethysFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/TitanFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/TritonFlyByContract.cfg

Creates Fly-by contracts for the gas giant moons. 
- Rewards (loosely) based on the difference between Mars and Phobos fly-bys
- Minimum distance kept the same 20Mm, given all flyby missions (except the moon) have this
- Deadline is the same as the one for parent body flyby
- Requirement is parent body flyby

Flyby Contracts for the gas giant moons

---

tree.yml

I wanted to fix insane cost for some of raidernick parts and move them from rocketry node to construction.  There were some old configs in the file that didn't match part names so I updated them.  Equivalent parts from Tanares are already there so i don't see why RN couldn't be as well.

RN R7 core and booster tanks

---

GameData/RP-0/NonRP0.cfg

Change log:
* Merge the Filter Extensions and the "NoNonRP0" folder patchers to a single one.
* Make the RP-0 tag insensitive to capitalization ("true" and "True" are exactly the same).
* Change the MM pass that the patches are applied (FINAL is bad for redistributed mods).
* Remove some part patches that referred to two VSR engines (the "engineSkipperButtless" does not exist and the "MicroEngineB" is already taken care of by RO).
* Add a tag cleanup pass.

Update the RP-0 part categorizer

---

GameData/RP-0/ProceduralAvionics.cfg
README.md

added procedural Ranger Block I Core TECHLIMIT

fixed procedural Ranger Block I Core power usage

---

GameData/RP-0/Contracts/Fly-by Contracts/MercuryFlyByContract.cfg

Fixed the requirements as they weren't preventing the contract from being available prior to Venus (or even lunar) flyby completion.
Also increased rewards because small bodies next to huge Sun's are far harder than say Venus.  I set rewards equal to Saturn, but should probably be more inline with Uranus or Neptune.

Fix Mercury Flyby Contract

---

GameData/RP-0/Contracts/Fly-by Contracts/CallistoFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/DeimosFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/DioneFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/EnceladusFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/EuropaFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/GanymedeFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/IapetusFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/IoFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/JupiterFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/MarsFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/MercuryFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/MimasFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/NeptuneFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/PhobosFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/PlutoFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/RheaFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/SaturnFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/TethysFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/TitanFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/TritonFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/UranusFlyByContract.cfg
GameData/RP-0/Contracts/Fly-by Contracts/VenusFlyByContract.cfg

@stratochief66 @NathanKell see any problems with this?  By doing this, I could setup a Jupiter flyby, and then if I see that I could also swing by Saturn, I could accept that contract later and use my Jupiter probe.

Removed the NewVessel requirement from the flyby contracts

---

GameData/RP-0/Avionics.cfg

Unlocking Basic Avionics will enable the integrated avionics on all Atlas tanks.

Atlas only depends on basicAvionics

---

tree.yml

**Change log:**
* Add RP-0 support for the new engines: RD-100, RD-107, RD-108 and RD-0124A (dual/Sunkar variant).
**Notes:**
* This PR also sets the correct tech tree placement for the Ven Stock Revamp RD-100 engine (was previously the RD-103/M engine).

RealEngines v1.5 RP-0 support

---

GameData/RP-0/ProceduralAvionics.cfg

Given  #649, I doubled the baseline volume of this procedural. It still is super dense compared to Ranger I. I wonder if the volume for the ranger core was calculated including the metal structural parts below the core.

Add stability tech level early controllable core

---

tree.yml

**Change log:**
* Change the name of the RO engine clones to fix conflicts with the RealEngines pack (https://github.com/KSP-RO/RealismOverhaul/pull/1616).

BobCat Soviet Engines Extras name fixes

---

tree.yml

**Change Log:**
* Add RP-0 support for the RealEngines SuperDraco engine.

RealEngines v1.6 RP-0 support

---

GameData/RP-0/ResourceTechs.cfg

In reference to #523 I decided to create very simple PARTUPGRADES to show up in the Tech Tree for each of the different types of fuel tanks made available by RealFuels.
I have used stock Icons so that they will work on any install and given them no costs to unlock (because they don't actually do anything, they are just informative).
Here they are in action:
http://imgur.com/a/6yfvB

Created PARTUPGRADES for the RF Fuel Tank Types

---

GameData/RP-0/Contracts/Space Stations/First Space Station.cfg

in the current version, minPeA=400km, after the first crew departed, even though the text says 250k. I think that's a typo and set it to 250k.

fix minPeA after completion

---

bin/makeversion
bin/yml2mm

use `/usr/bin/env perl` to look it up in the PATH instead of
the hardcoded /usr/bin/perl (typically the first perl in the user's
PATH is going to be preferred).
the -w flag causes issues when used with env but both of these
scripts declare `use warnings` so that flag is redundant and
removed from the shebang.
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

fix perl shebang line

---

RP-0.version.in

using https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md as a guide, added line 8 to this version file, confusion exists with NetKan file.
See issue #704

CKAN homepage pointing at Forums

---

GameData/RP-0/Avionics.cfg

Added most RN Soviet Probes (all sputniks, molinya1, polyot, and lunas
2-10) and removed avionics from Pioneer 5

Avionic Changes

---

GameData/RP-0/Tree/EntryCostModifiers.cfg
GameData/RP-0/Tree/TREE-Parts.cfg

Added entry cost mosifiers for AJ10 early and mid and the Vanguard X405.
Also chnage the entry cost for the RN X405 Vernier so that the total
entry cost for the RN Vanguard X405 matches the SXT composite

Entry Cost configs

---

GameData/RP-0/Contracts/Human Contracts/Suborbital Crewed.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingAltitude.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingDifficult.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingEasy.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingIntermediate.cfg
GameData/RP-0/Contracts/X-Planes/CrewedHighAtmo.cfg
GameData/RP-0/Contracts/X-Planes/CrewedHighAtmoLate.cfg

Adding cooldowns to x-planes high, high late, and crewed suborbital, setting reasonable minimums to sounding rockets just as a safety net for players who don't start the game off with the new ones

Adjusting contracts

---

GameData/RP-0/Contracts/RP0_Contract_Resources.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingAltitude.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingDifficult.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingEasy.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingIntermediate.cfg

Fixed sounding altitude errors
Set sounding density to .5 g/cc
Made all contracts read density to make further changes easier.

Sounding Rocket fixes

---

GameData/RP-0/Science/PartExperimentAdder.cfg

The Agena satellite bus provided by FASA has a geiger counter, but it is not being replaced by RP-0 with its version.

Replace the Geiger Counter in FASA's Agena probe

---

Source/Avionics/ModuleProceduralAvionics.cs

Makes the displayed value consistent with the values shown in the
avionics tab of the RP-0 GUI

Show 3 sig figs for proc avionics tonnage slider

---

GameData/RP-0/Tree/RFTechLevels.cfg

soundnfury noticed that RCS `TLTECH2` in `RFSETTINGS` was placed into
the `earlyDocking` node, but the `PARTUPGRADE` was placed into the
`improvedFlightControl` node. Pap said that the correct value is
whatever `TLTECH` was.

Place RCS Tech Level 2 into earlyDocking node

---

Source/Tooling/ToolingGUI.cs

Stored total cost in untooledPart instead of tooled cost directly to
avoid calculating untooled cost twice.
Didn't add recompiled DLL to avoid merge conflicts in case another PR is merged first

Show part cost after purchasing tooling in tooling UI

---

Source/Avionics/ModuleProceduralAvionics.cs

Prior to this, the window would not resize when selecting different tech
levels. This could result in buttons and text being rendered below the
bottom of the window, especially when lots of tech levels are present
(e.g. Sandbox).

Use GUILayout for proc avionics config window

---

Source/Avionics/ModuleProceduralAvionics.cs
Source/Avionics/ProceduralAvionicsConfig.cs

Prior to this PR, distinct proc avionics parts that had the same
config (i.e. "booster", "upper stage", or "probe") were forced to have
the same tech level, since the tech level was set per-config, instead of
per-part (or per-PartModule, in this case).

Allow distinct proc avionics parts to have different tech levels

---

Source/Tooling/ModuleToolingDiamLen.cs
Source/Tooling/ToolingGUI.cs

Proc parts sliders allow editing with precision of up to three decimal
places, so three decimal places should be shown when displaying sizes of
tooled/untooled parts

Show three decimal places for tooling dimensions

---

GameData/RP-0/Science/CrewScience/CrewLabAdder.cfg

I also noticed HTP was being removed from the FASA Mercury pod, but the list
of possible RCS propellants is quite long; there must be a better way to fix
this than just listing them all.  (It'd surely be simpler to list all the
resources to _remove_...)

Don't remove Ablator from crew pods.  They're likely to need it.

---

GameData/RP-0/Contracts/Orbits/Venus Orbit.cfg

The contract was being satisfied by a fly-by instead of an orbit. Changing the min Apoapsis value to be 0 means that hyperbolic orbits no longer satisfy the contract.

Fix completion bug Issue #764

---

GameData/RP-0/Parts/RFProcTanks.cfg

Without this, the player can set the utilization for any
non-service-module proc tank to 100%, partially defeating the purpose of
the tank progression

Set max utilization for proc tanks

---

GameData/RP-0/Tree/TREE-Parts.cfg

From #RO:
21:36 <@Pap> awang: Agena A should be in orbitalRocketry1959, Agena B in
orbitalRocketry1961, Agena D in orbitalRocketry1962
Fixes #796

Fix BDB Agena engine tree placement

---

GameData/RP-0/Tree/TREE-Parts.cfg

Part costs and Pioneer entryCost are copied from the old tree.yml;
Voyager entryCost is just 20x part cost.

Add part costs for Pioneer-10/11 and Voyager class dishes

---

GameData/RP-0/Tree/TREE-Parts.cfg

AJ10-137 engine config is supposed to be in the 1967 orbital rocketry
node, so it only makes sense for the AJ10-137 part to be in the same
node

Fix RealEngines AJ10-137 tree placement

---

GameData/RP-0/Tree/TREE-Parts.cfg

Enabling crossfeed for radial decouplers require the "fuelSystems" tech
node to be unlocked, but that node doesn't exist any more.
Guess the implicit question here is whether fuel crossfeed should be enabled by default, or whether it should be hidden behind a tech node, like it is for stock

Allow fuel crossfeed for radial decouplers

---

GameData/RP-0/Avionics.cfg

This eliminates the need to explicitly enumerate all probe cores that
need to have science cores added.

Add science core to everything without avionics or crew control

---

GameData/RP-0/Contracts/Space Stations/New Crew Station.cfg

As I read this, the point of this contract is to send crew to an empty station.  But the current requirement is set to only allow the contract to occur when there are less than 3 vacant seats available.  Meaning if a station can support 5 crew and you have 3 on the station, the contract would become available because "EmptyCrewSpace()" would return a result of 2.  By using "v.CrewCount()==0" we should only allow the contract to occur when a station has no crew on board, regardless of how many available seats there may be.

Fix NewCrewStations.cfg

---

GameData/RP-0/Tree/Crossfeed.cfg
GameData/RP-0/Tree/TREE-Parts.cfg

Changes can't be made directly to TREE-Parts.cfg, since it's generated
from The Spreadsheet (tm) and will be overwritten on next export. The
changes here can't be made in The Spreadsheet, either, because it isn't
configured to account for changes to ModuleToggleCrossfeed.
Patches were partially broken, anyways, since I forgot to change
"!techRequired" to "@techRequired" when requiring
materialsScienceSpaceplane.

Move radial crossfeed patches to independent file

---

GameData/RP-0/Avionics.cfg

The node `flightControl` no longer exists. I've placed the avionics on the same node that unlocks the Centaur's RCS thrusters.

Fix avionics tech for FASA Centaur parts

---

GameData/RP-0/Avionics.cfg

placed SSTU command pods in their respective avionics class.
Added avionics to SSTU service modules (20 t, same class as small pods), delete this if you consider it inappropriate.
Added avionics to a couple Coatl aerospace parts for the Venera mission.

Adding avionics to SSTU, coatl

---

GameData/RP-0/Contracts/Flyby Contracts/Ceres Flyby.cfg
GameData/RP-0/Contracts/Flyby Contracts/Vesta Flyby.cfg

* Based on data from Mars and Jupiter flybys
* 4-year deadline
* Same requirement as Jupiter flyby
* Same altitude (20 Mm) as Mars flyby

Add flyby contracts for Ceres and Vesta

---

GameData/RP-0/Contracts/Records/AltRecord.cfg

Can't fix this correctly because CC is weird, so now altitude records won't update the sounding difficulty if they beat your current - but at least it won't write an old cached value back to the difficulty and overwrite progress.

Fix for altitude record overwrite issue

---

GameData/RP-0/Contracts/Space Stations/New Crew Station.cfg

#783, merged in commit be7a24b, fixes the empty seat requirement in the contract. It was merged only in master and not in Developmental. This ports it to Developmental.

Fix NewCrewStations.cfg (port be7a24b) (#783)

---

GameData/RP-0/Contracts/Surface Outposts/MarsOutpost.cfg
GameData/RP-0/Contracts/Surface Outposts/MarsOutpostWithLab.cfg
GameData/RP-0/Contracts/Surface Outposts/MoonOutpost.cfg
GameData/RP-0/Contracts/Surface Outposts/MoonOutpostWithLab.cfg

The group name was not matching the group definition by RP-0. They were not showing in the RP-0 group and were red. Now they are appearing correctly.

Fix Surface Base Contracts

---

GameData/RP-0/Science/CrewScience/Experiments/BasicCapsuleExperiments.cfg
GameData/RP-0/Science/CrewScience/Experiments/MatureCapsuleExperiments.cfg
GameData/RP-0/Science/CrewScience/Experiments/SecondGenExperiments.cfg
GameData/RP-0/Science/CrewScience/LabConfigs.cfg

There's several entry requirements for crew science:
- Part has to be configured with a "Lab" module. These come in three classes which are mostly proxies for size.
- Each class of lab module has a techlevel requirement.
- individual experiments each require a particular class of lab AND have a tech requirement.
This PR removes the second requirement by moving all Labs to be at the "start" node (you still need to get a sufficiently large module into orbit to do the experiments, and three small ones don't stack)
Further, I attempted to put a reasonable tech requirement on the experiments.

Crew Science requirements

---

GameData/RP-0/Parts/RFProcTanks.cfg

Problem: 
Shielded Proctank was not part of the general RP-1 overhaul and still uses the old system of unlocking sizes by techlevel (no tooling). Also has 100% utilization.
Solution:
Retrofitted tooling and applied a max utilization.

ProcTankSpaceplane: added tooling

---

GameData/RP-0/CrewTrainingTimes.cfg

Fixed missing RN soyuz entries for 7K-OK Descent and Orbital (Male, Female)  modules for the Soyuz training, plus the Voskhod Airlock for the Voskhod training.
Added:
ok-sa = Soyuz
ok-bo-fem = Soyuz
ok-bo-male = Soyuz
rn-voskhod-airlock = Voskhod

Fixed missing RN soyuz entries for crew training

---

Source/Crew/CrewHandler.cs
Source/Crew/FSGUI.cs
Source/DifficultyPresets.cs
Source/KCTBinderModule.cs
Source/Maintenance/MaintenanceGUI.cs

Added options into the game's difficulty settings menu for toggling the RP-1 crew training and automatic retirement features. I know that a lot of people (including me) would prefer to play without having to micromanage their crews. This commit adds the option for disabling either of these features. For new games, these options are now by-default disabled on 'easy' difficult but 'normal' and above  still has them turned on.
The training and retirement updates are still done in the background. Also beware that because retirement dates are unaffected, re-enabling the retirement feature after playing for 10 years can cause most of the old nauts to retire almost instantly. But I thought that it's a better option than increasing the retirement deadline that gets stored for each individual …

Added settings for disabling crew training and retirement features

---

GameData/RP-0/Science/CrewScience/CrewLabAdder.cfg

Equips more parts with the WBIConvertibleMPL part module. Requires https://github.com/KSP-RO/RP-0/pull/881 or it won't work.
I've used the incredibly scientific method of assigning them according to crew capacity: 1 - basic, 2 - 2ndGen, 3+ mature

More CrewScience Labs

---

GameData/RP-0/Contracts/Space Stations/Power Module Station.cfg

Warning: when I had this locally, this contract somehow seems to have blocked the New Crew Station contract to appear. Do you have an idea why?

Why do I need <3 empty seats?

---

GameData/RP-0/Contracts/Human Records/CrewedDurationRecord.cfg

The current rewards for flight duration are dominating all my contract rewards. 180days gives me 7,200,000 funds.  A year would double that.  (In my settings a moon landing is significantly less than that.) 
Considering that long-time spaceflights are not a  difficult thing in gameplay, I think this should be changed to an approach that is less than linear.

reduce Crazy rewards for flight duration

---

GameData/RP-0/Contracts/Early Satellites/Tundra Satellite.cfg
GameData/RP-0/Parts/RFProcTanks.cfg

@pap1723 
I'm not sure why SM-I would have been in the cost reduction list for a non-SM tank. Maybe something related to the fact that the original sounding rocket payloads are in Tank-I-HP, but if anything, I would see that as a reason to have SM-1 be cost-reduced by Tank-I. I'm guessing this was just an oversight.

Have Tank-III be cost-reduced by Tank-II, not Tank-I and SM-I

---

Source/LoadingScreenChanger.cs

* Increase the time that each loading screen image is shown to 12 seconds (was 4 previously)
* Removed code that didn't appear to be doing anything useful. I have no idea why the code was previously calling Unity's random generator up to 99 times.
Test dll's are available here: https://github.com/siimav/RP-0/releases/tag/dev2

Fix loading screen images switching too quickly

---

GameData/RP-0/Contracts/Sounding Rockets/SoundingAltitude.cfg

Contract used to be repeatable until 6Mm, is now repeatable until 10Mm. That means the max target must also be 10Mm, otherwise the limit is never reached and the contract is repeatable forever.

Let Sounding Rocket (Altitude) reach its maximum

---

Source/Tooling/ModuleTooling.cs
Source/Tooling/ModuleToolingDiamLen.cs
Source/Tooling/ModuleToolingGeneric.cs
Source/Tooling/ModuleToolingPFSide.cs
Source/Tooling/ModuleToolingPTank.cs
Source/Tooling/ModuleToolingSSTUTank.cs
Source/Tooling/ToolingDatabase.cs
Source/Tooling/ToolingGUI.cs

This fixes an issue where tooling for (near) identical untooled parts were purchased multiple times when using the 'Tool All' button. Also takes into account the 4% stretch margin and cost reducers.

Tool all improvements

---

GameData/RP-0/CrewHandlerSettings.cfg
Source/Crew/ActiveCourse.cs
Source/Crew/CrewHandler.cs
Source/Crew/CrewHandlerSettings.cs
Source/KCTBinderModule.cs

* Proficiency trainings no longer expire, removed refresher courses
* Flight trainings do not expire when flight duration was less than 30 seconds
* Allow only 1 mission training to be active at a time

Crew training changes

---

GameData/RP-0/Contracts/Nav Sats/Second-Gen Nav Sats.cfg

The second generation Navsat contracts have ComSatPayload as a requirement, which is not intuitive. Added highlighting in the contract blurb to aid players somewhat.

Added highlight to 2nd gen navsat contract for unexpected resource type

---

Source/Crew/CourseTemplate.cs
Source/Crew/CrewHandler.cs
Source/Crew/FSGUI.cs
Source/KCTBinderModule.cs

Creates proficiency courses for all crewed parts that are in the KCT's research list. Mission trainings are not available before the part is actually purchased. If the research is finished but the user does not unlock the part, then the proficiency course will also disappear. I think it might actually be a good thing because this way the list wouldn't get cluttered up with entries for parts that will never be used.

Allow proficiency training while the part is still being researched

---

GameData/RP-0/Contracts/Flyby Contracts/Ariel Flyby.cfg
GameData/RP-0/Contracts/Flyby Contracts/Miranda Flyby.cfg
GameData/RP-0/Contracts/Flyby Contracts/Oberon Flyby.cfg
GameData/RP-0/Contracts/Flyby Contracts/Titania Flyby.cfg
GameData/RP-0/Contracts/Flyby Contracts/Umbriel Flyby.cfg
GameData/RP-0/Science/BodyScienceParams.cfg

Many moons had altitude thresholds for space low above their SoIs.
* This changes all (except Earth/Moon) thresholds to be the radius of the body, rounded to look nicer.
* Also reduces the science multipliers of the Moon as requested by @pap1723 
* This PR incorporates what @Bornholio did in #999
* Also adds Flyby contracts for Uranus moons. I used most parameters from the Triton flyby, adjusting only the altitude to fit inside the SoI.

Change SpaceAltitudeThresholds

---

GameData/RP-0/Parts/RFProcTanks.cfg

The ability to hold Sounding Rocket Payload was recently removed from the HP versions of  Tank II, II, and IV.  See 36d027672216f5f9ccdc9c35a3b13574c0d2b0d6.  But the descriptions of these tanks in-game still claims that those HP tanks can hold SR payloads.  This edit just removes those chunks of description, so that they match, e.g., Tank III (Balloon).

Remove claim that HP Tanks II to IV can hold Sounding Rocket Payload

---

.travis.yml

Travis defaults to last 50 commits, but this does not include the most recent tag so `git describe` failed.  Increasing the clone depth should allow it to find the tag.

Attempt to fix CI by increasing clone depth

---

Source/Tech Tree/Parts Browser/data/SSTU.json

SSTU LC2-POD was RP-0 no cost. I added pricing. I priced it the same as the FASA Lunar Accent Module. Similar parts both have crew of 2 and built in RCS.

Added RP-0 pricing to SSTU LC2-POD

---

GameData/RP-0/Tree/EntryCostModifiers.cfg
GameData/RP-0/Tree/ProceduralAvionics.cfg

* Adds a Deep Space Upper stage avionics. it is capable of going interplanetary and hibernates. Focused in crewed spacecraft and satellite buses
* Makes the "normal" upper stage slightly cheaper and unable to hibernate or go into deep space
* Tentative values for all ECMs for avionics
* Small tweaks to all avionics, increasing energy consumption in boosters, and imputing values for more advanced parts.
* Reduce density of booster and upper avionics, as those were getting too small

General rebalance of Procedural avionics

---

GameData/RP-0/Contracts/X-Planes/CrewedSupersonic.cfg

No reason for the contract to require exactly 1 crew member.
You can EVA additional passengers after taking them for the ride to satisfy maxCrew = 1.
Crewed flight and crewed high contracts both have maxCrew = 99.

x-planes supersonic contract should allow > 1 crew

---

GameData/RP-0/Contracts/Weather Sats/Geostationary Weather Sat.cfg

Looks like it was copied from comms sats. Also references other orbits even though contract is only for GEO.
Replaced with genericDescription from other weather sat contracts.

Wrong description for GEO weather sat

---

GameData/RP-0/Parts/SampleReturnCapsule/RP0SampleReturnCommand.cfg

reverseOrientation = true needed to be outside PARACHUTE... ¯\_(ツ)_/¯
Also changed the ISP to theoretical max values for cold gas Nitrogen in vacuum and at 1 atm.
Used 500 bar for RCS tank pressure for calculation at 1 atm. It's probably a bit generous, but it's better than the current hydrazine numbers.
Ref for theoretical cold gas ISP, http://cdn.intechopen.com/pdfs/37528/InTech-Cold_gas_propulsion_system_an_ideal_choice_for_remote_sensing_small_satellites.pdf

Fix the elusive return capsule parachute bug

---

GameData/RP-0/Avionics.cfg

The other capsules in ROCapsules were tagged along their counterparts from other mods but the Mercury pod got left out. Simple fix.

Added ROCapsules Mercury avionics

---

GameData/RP-0/Contracts/Moon Exploration/Lunar Rover.cfg
GameData/RP-0/Contracts/Rovers/Callisto Rover.cfg
GameData/RP-0/Contracts/Rovers/Charon Rover.cfg
GameData/RP-0/Contracts/Rovers/Dione Rover.cfg
GameData/RP-0/Contracts/Rovers/Enceladus Rover.cfg
GameData/RP-0/Contracts/Rovers/Europa Rover.cfg
GameData/RP-0/Contracts/Rovers/Ganymede Rover.cfg
GameData/RP-0/Contracts/Rovers/Iapetus Rover.cfg
GameData/RP-0/Contracts/Rovers/Io Rover.cfg
GameData/RP-0/Contracts/Rovers/Mars Rover.cfg
GameData/RP-0/Contracts/Rovers/Mercury Rover.cfg
GameData/RP-0/Contracts/Rovers/Mimas Rover.cfg
GameData/RP-0/Contracts/Rovers/Pluto Rover.cfg
GameData/RP-0/Contracts/Rovers/Rhea Rover.cfg
GameData/RP-0/Contracts/Rovers/Tethys Rover.cfg
GameData/RP-0/Contracts/Rovers/Titan Rover.cfg
GameData/RP-0/Contracts/Rovers/Triton Rover.cfg
GameData/RP-0/Contracts/Rovers/Venus Rover.cfg

In certain config points the second waypoint was labeled 'Beta', in others 'Bravo'. Now it's all NATO compliant. _Loud cheering in the background_

Made waypoint naming for the lunar rover contract consistent

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/EntryCostModifiers.cfg
GameData/RP-0/Tree/RP0TechTree.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json

Part entry cost for upper stage solids was reduced by 25K. The biggest change is probably in the tech tree where early nodes got a sci point reduction in the range of 2-3x. I would've liked to reduce the first node to 0.5 points but unfortunately KSP doesn't support floating point values there. I chose the new values based on how much useful tech you get by researching it. Because of that the 1956 node ~~got a higher cost than 1958.~~ has the same cost as 1958.

Reduce tech node & entry costs for early solid motors

---

GameData/RP-0/Contracts/Sounding Rockets/DistanceSoundingDifficult.cfg
GameData/RP-0/Contracts/Sounding Rockets/DistanceSoundingIntermediate.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingBio.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingDifficult.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingFilm.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingIntermediate.cfg

- initialize the completion counts so that 'N completed' actually shows
zero (hackish, probably a better way)
- make the 'Bio SR unlocks Crewed Suborbital' message stand out
- remove other SR contracts when bio or film SR are accepted
(because accepting them hides bio & film, even if already accepted)

Tweak new science-SR contracts

---

GameData/RP-0/Avionics.cfg
GameData/RP-0/CrewTrainingTimes.cfg

ksp 1.6 introduced a mk1pod.v2 part. Most of rp-1 was switched over to
it; avionics and training, which live in their own file, were overlooked

Fix Mk1 pod's avionics and training configs

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Ven_Stock_Revamp.json

Minimal fix for overpowered part: a 1959 tech node shouldn't have a part
that allows EVA.
There's other arguably-OP aspects to the part (mass, power usage, cost),
but how to address those is less clear-cut. Until someone tackles the larger issue, at least this should go in.

#1148 Add No-EVA tag to 1.25m Crew Carrier

---

GameData/RP-0/CustomBarnKit.cfg

TS upgrade levels were tweaked according to newComms
rules, but the corresponding change to orbitDisplayMode
was left out.
(see https://github.com/MikeOnTea/RealismOverhaul/commit/7b79de36a93c2db9c321957ee7ccfa6ba9b301a5 )

Make Maneuver Nodes available with Lunar Comms TS

---

GameData/RP-0/Tree/ECM-Parts.cfg
Source/Tech Tree/Parts Browser/data/SXT.json

Because rp-1 removes all experiments from it

Remove experiment ECMs from 20in probe

---

Source/Crew/CrewHandler.cs
Source/UI/UIHolder.cs

Unity is unhappy with some UI calls from a Monobehavior constructor.  Move UIHolder's TopWindow and CrewHandler's FSGUI instantiation to Start methods

Fix Exceptions from UIBase()

---

GameData/RP-0/Contracts/Human Milestones/First EVA.cfg

First EVA milestone was recently hidden behind 'must unlock 2nd gen
capsules', to protect players from thinking they can do it with
Mercury
But 2ndgen capsules aren't the only way to go EVA, prototype spaceplanes
are an alternate path. It'd be silly if the player could go EVA and not
hit the milestone.

Unlock First EVA with any EVA-enabling tech

---

GameData/RP-0/CrewTrainingTimes.cfg

Only x-15 was configured, not higher tiers.
This handles the next 2.

Crew Training for Spaceplane cockpits

---

Source/Avionics/ModuleAvionics.cs

Currently it's possible to toggle non-toggleable avionics via kOS or similar mods (and also possibly via an action group) as the action is still valid, even though its gui is disabled.
This change fixes the logic such that the power draw is always full for non-toggleable avionics.

Fixed power draw for non-toggleable avionics

---

GameData/RP-0/Tree/ProceduralAvionics.cfg

Changed the progression to be closer to prefab parts. Also added an additional level to the postWarAvionics node which was currently empty.
The mass figures are now:
* lvl 0 (starting) - 60kg
* lvl 1 (new) - 40kg
* lvl 2 (Sputnik) - 20kg
* lvl 3 (Explorer) - 10kg
* lvl 4 (Early controllable probe core) - 2kg

Early Science-Core proc avionics overhaul

---

GameData/RP-0/Contracts/Early Satellites/Communications Satellite - Early.cfg
GameData/RP-0/Contracts/Early Satellites/Communications Test Satellite.cfg

Because the requirement is just a 'gotcha'.
- All those contracts are gated behind First Scientific Satellites,
so solar panels are necessarily available
- Without any specific power output needed, the requirement can
be satisfied with a single tiny panel that doesn't actually provide
enough power for anything
So the requirement doesn't increase contract difficulty in any way
other than punishing players who fail to notice it

Remove 'solar power' param from Comm Sat contracts

---

GameData/RP-0/Contracts/Moon Exploration/Crewed Lunar Orbit 1 Repeatable.cfg
GameData/RP-0/Contracts/Space Stations/Lunar Space Station.cfg

Gate it behind a single 'moon orbit with at least one crew', and
spell out that unlock in the description.
Because First Lunar Orbit pays enough to be worth doing, but
the rest don't; it's too easy for someone to just stop there,
going straight to Landing and never realize the chain is
worth continuing. Putting up a station before going for a landing
should be a viable option, and shouldn't require doing the same prereq 4 times.
(per discord "discussion" https://discordapp.com/channels/319857228905447436/516431076680531978/683086297434423356 - PR submitted as much to provoke more discussion as anything else)

Don't gate Lunar Station behind 4 Lunar Orbits

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

All the other Apollos are 35k, this one was 38k
Might still be too high; the forward heatshield is another 3k,
presumably all the variants don't have the same parts breakdown...

Tweak ROCapsules Apollo part cost

---

GameData/RP-0/Tree/OrphanNode.cfg

The improvedNuclearPropulsion node still exists in the RP-1 tech tree, and has fully configured parts that are being orphaned (ie NERVA 2, RD-0410).

improvedNuclearPropulsion shouldn't be orpahned

---

GameData/RP-0/Contracts/Advanced Satellites/Communications Satellites.cfg
GameData/RP-0/Contracts/Advanced Satellites/Geostationary Communications Network.cfg
GameData/RP-0/Contracts/Advanced Satellites/IridiumNEXT.cfg.disabled
GameData/RP-0/Contracts/Early Satellites/Communications Satellite - Early.cfg
GameData/RP-0/Contracts/Early Satellites/Communications Test Satellite.cfg
GameData/RP-0/Contracts/Early Satellites/Early CommNet (3 Sat).cfg
GameData/RP-0/Contracts/Early Satellites/Early CommNet (4 Sat).cfg
GameData/RP-0/Contracts/Early Satellites/First Com Sat.cfg
GameData/RP-0/Contracts/Early Satellites/First Nav Sat.cfg
GameData/RP-0/Contracts/Early Satellites/Geostationary.cfg
GameData/RP-0/Contracts/Early Satellites/Molniya Satellite.cfg
GameData/RP-0/Contracts/Early Satellites/Tundra Satellite.cfg
GameData/RP-0/Contracts/Nav Sats/Early Nav Sats.cfg
GameData/RP-0/Contracts/Nav Sats/GLONASS Network.cfg
GameData/RP-0/Contracts/Nav Sats/GPS Network.cfg
GameData/RP-0/Contracts/Nav Sats/Operational Nav Sats.cfg
GameData/RP-0/Contracts/Nav Sats/Second-Gen Nav Sats.cfg
GameData/RP-0/Contracts/Sounding Rockets/DistanceSoundingDifficult.cfg
GameData/RP-0/Contracts/Sounding Rockets/DistanceSoundingIntermediate.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingBio.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingDifficult.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingIntermediate.cfg
GameData/RP-0/Contracts/Weather Sats/Early Weather Sats.cfg
GameData/RP-0/Contracts/Weather Sats/First Weather Sat.cfg
GameData/RP-0/Contracts/Weather Sats/Geostationary Weather Sat.cfg
GameData/RP-0/Contracts/Weather Sats/Second Gen Weather Sats.cfg
GameData/RP-0/Contracts/Weather Sats/Sun Sync Weather Sats.cfg

This fixes the rounding errors from different floating point approximations in CC and RF.

Fix payload contracts by requiring 0.01 less than stated

---

GameData/RP-0/Tree/ResourceTechs.cfg

The Tech Tree Icons were not matching the tank definitions. 
Looks like there was some Copy-Paste error, the first upgrade had the technology for the base balloon tank, and the second upgrade had the technology of the first upgrade.

Fix the TechTree Icons for Baloon tank upgrades

---

GameData/RP-0/Contracts/Advanced Satellites/Communications Satellites.cfg
GameData/RP-0/Contracts/Advanced Satellites/Geostationary Communications Network.cfg
GameData/RP-0/Contracts/Advanced Satellites/IridiumNEXT.cfg.disabled
GameData/RP-0/Contracts/Early Satellites/Communications Satellite - Early.cfg
GameData/RP-0/Contracts/Early Satellites/Communications Test Satellite.cfg
GameData/RP-0/Contracts/Early Satellites/Early CommNet (3 Sat).cfg
GameData/RP-0/Contracts/Early Satellites/Early CommNet (4 Sat).cfg
GameData/RP-0/Contracts/Early Satellites/First Com Sat.cfg
GameData/RP-0/Contracts/Early Satellites/First Nav Sat.cfg
GameData/RP-0/Contracts/Early Satellites/Geostationary.cfg
GameData/RP-0/Contracts/Early Satellites/Molniya Satellite.cfg
GameData/RP-0/Contracts/Early Satellites/Tundra Satellite.cfg
GameData/RP-0/Contracts/Nav Sats/Early Nav Sats.cfg
GameData/RP-0/Contracts/Nav Sats/GLONASS Network.cfg
GameData/RP-0/Contracts/Nav Sats/GPS Network.cfg
GameData/RP-0/Contracts/Nav Sats/Operational Nav Sats.cfg
GameData/RP-0/Contracts/Nav Sats/Second-Gen Nav Sats.cfg
GameData/RP-0/Contracts/Weather Sats/Early Weather Sats.cfg
GameData/RP-0/Contracts/Weather Sats/First Weather Sat.cfg
GameData/RP-0/Contracts/Weather Sats/Geostationary Weather Sat.cfg
GameData/RP-0/Contracts/Weather Sats/Second Gen Weather Sats.cfg
GameData/RP-0/Contracts/Weather Sats/Sun Sync Weather Sats.cfg

As #1237 had some issues with showing the rounded amounts of payloads, I followed a different approach here. I tested it in a few of the early satellite contracts, and it seems to be working correctly now. I have also fixed the contracts that include several satellites, which I had omitted in the previous PR.

Fix payload contracts to show rounded amounts in the requirements

---

GameData/RP-0/Contracts/Nav Sats/Second-Gen Nav Sats.cfg

Fix was double-applied: payload got a -0.01, then minQuantity got payload-0.01.
'payload' is also used for the user-visible text, so minQuantity is the one that should have the -0.01

Tweak payload-rounding fix for second-gen nav sats

---

GameData/RP-0/Tree/ECM-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

- lower flat cost from 36k to 1k. For an rcs block and fuel tank,
36k is silly.
- BUT add mmh-nto ECM, since that's the fuel it uses. It's possible
to unlock the part first, shouldn't get a free pass.
The ECM is 25k, so this adds up to a 10k reduction, and lessens
the pain by making the rest a shared cost

Better unlock cost for ROC gemini RCS pack

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/EntryCostModifiers.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

- Move 45k to an ECM shared by both andro ports and p&d ports.
The choice between the 2 types is largely cosmetic, don't
punish the player quite so much for wanting to use both.
- Reduce ROC Gemini docking port cost by 25k, bringing the total
cost of probe+drogue to 1k less than Andro instead of 24k more.
It doesn't make much sense for the more convenient, magical
magnetic port to be significantly cheaper.
Oddity: even with this cost reduction, ROC Gemini ports are
more expensive than FASA by 28k. Don't know why, so leaving as-is

Docking port unlock cost tweaks

---

GameData/RP-0/Contracts/Flyby Contracts/Ceres Flyby.cfg
GameData/RP-0/Contracts/Flyby Contracts/Jupiter Flyby.cfg
GameData/RP-0/Contracts/Flyby Contracts/Mercury Flyby.cfg
GameData/RP-0/Contracts/Flyby Contracts/Vesta Flyby.cfg
GameData/RP-0/Contracts/Orbits/Jupiter Orbit.cfg
GameData/RP-0/Contracts/Orbits/Jupiter Orbit_Rep.cfg
GameData/RP-0/Contracts/Orbits/Mars Orbit.cfg
GameData/RP-0/Contracts/Orbits/Mars Orbit_Rep.cfg
GameData/RP-0/Contracts/Orbits/Mercury Orbit.cfg
GameData/RP-0/Contracts/Orbits/Mercury Orbit_Rep.cfg
GameData/RP-0/Contracts/Orbits/Neptune Orbit.cfg
GameData/RP-0/Contracts/Orbits/Neptune Orbit_Rep.cfg
GameData/RP-0/Contracts/Orbits/Pluto Orbit.cfg
GameData/RP-0/Contracts/Orbits/Saturn Orbit_Rep.cfg
GameData/RP-0/Contracts/Orbits/Uranus Orbit.cfg
GameData/RP-0/Contracts/Orbits/Uranus Orbit_Rep.cfg
GameData/RP-0/Contracts/Orbits/Venus Orbit.cfg
GameData/RP-0/Contracts/Orbits/Venus Orbit_Rep.cfg

Fixes the payout from most planetary orbit contracts, which were missing the @RP0:globalHardContractMultiplier and adds a new planetary orbit contract for the 7 main planets.
Also changes the Requirement for the flybys Mercury, Ceres, Vesta and Jupiter, to be either Mars or Venus instead of only Mars.
These repeatables have slightly less payout than the first orbit "milestone" contracts, and add a high inclination and apoapsis (5 * planet radius for the rocky planets, and a higher preset "reasonable" requirement for the gas giants) requirements.
As they require a new vessel, only one of each can be launched at a time, avoiding a shotgun into each planet every window. The intention is to stimulate people to return to the planets with more advanced experiments later on after the first …

Planet orbits

---

RP-0.netkan

The RP-0 wiki mod recommendations page mentions TestLite as a manual install on these pages:
- https://github.com/KSP-RO/RP-0/wiki/Recommended-Extra-Mods
- https://github.com/KSP-RO/RP-0/wiki/TestLiteVsTestFlight
As of KSP-CKAN/NetKAN#8006, TestLite is now in CKAN (only updated for KSP 1.6.1 through 1.7.3, but the author is planning new releases).
The current RP-0 metanetkan recommends both RealAntennas and RemoteTech, which conflict with one another. This causes the install to fail if the user doesn't make any manual changes.
- `spec_version` updated to `v1.26` to allow use of `any_of` relationship (this just means the user's CKAN can't be horribly outdated)
- RealAntennas and RemoteTech recommendations placed in an `any_of` block so they won't be checked by default and the user can …

Recommend TestLite, fix antenna conflict

---

RP-0.netkan

RP-0/1 has a forum thread, but CKAN doesn't know about it.
Now the forum thread is added to the metanetkan.
(Should have included this in #1303, but I didn't notice it at the time.)
Tagging @siimav to ensure notifications.

Add link to forum thread

---

GameData/RP-0/Tree/TREE-Engines.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json

Hand-in-hand with https://github.com/KSP-RO/RP-0/pull/1240.
Once Cavea-B is moved back, the "stability" node will be nearly empty. NASA document 19680006875 says that hydrazine monoprop was fired in space in 59 as a test but not used operationally until 1961 with Ranger and Mariner. This moves it from the '59 node to the '61 node.

Move hydrazine back a node

---

GameData/RP-0/CustomBarnKit.cfg
GameData/RP-0/Tree/RP0TechTree.cfg

In the R&D building, upgrade costs are pushed back 1 tier,
so that maximum cost is 6M instead of 10M, and every tier has lower cost
Additionally, levels 3 and 4 now have higher node cost limits.
In the Mission Control, more levels are added, with 5 instead of 3,
and upgrade costs are overall reduced.

Change upgrade costs and tiers of R&D and Mission Control

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/SXT.json

Because at 170kg per seat, they make very attractive station parts

Tag airliner fuselages Unpressurized

---

Source/CareerLog/CareerLog.cs

* aimed at easier extraction for RiS milestones and their corresponding CC names

Changed contract event name to InternalName for easier contract extraction

---

GameData/RP-0/ProcCosts.cfg
Source/Tooling/ModuleToolingPFSide.cs

Update tooling module to support ProcFairings 6.0 changes:
* ProceduralFairingBase module now encompasses previous Base/Adapter/Resizer modules
* Base and FairingSide modules have MM-configurable cost adjusters based on decoupler presence
Update general procedural costing patches based on those changes.  Simultaneous support of both PF 1.8.x and 6.0+

Proc Fairings v6.0+ Support

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/EntryCostModifiers.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json

Give the ECM a different name than the config. A "x = x" ECM
sends RealFuels into infinite recursion land; there aren't
separate namespaces for engine config names and ECM names

Fix Agena A ECMs

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

because the probe is there, and is completely useless
without the drogue

Move ROCapsules Apollo drogue to docking port node

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Engines.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
GameData/RP-0/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json
Source/Tech Tree/Parts Browser/data/Horizon_Aeronautics_Zenit.json
Source/Tech Tree/Parts Browser/data/RN_Soviet_Rockets.json
Source/Tech Tree/Parts Browser/data/ROEngines.json
Source/Tech Tree/Parts Browser/data/RealEngines.json

- make all RD-8 and RD-120 variants have the same settings (cost, tags,
ECMs, etc)
- make the RD-8 cost 150 per vernier, instead of a crazy 1000
(600 on the config, divided by engineTypeMult=0.25)
rd-8 cost isn't based on anything, pure balance. 4x 1000 to give
verniers to a rd-120 that costs 750 is just insane. 4x 150 is probably
still high (esp. with the turbopump tag); didn't want to accidentally
create a new king of small engines
Also removed the dead ROE-RD8-RE config block; that part name lived for all of 1 month

RD-8, RD-120 tweaks

---

GameData/RP-0/Contracts/Milestones/First Science Sat.cfg

Does 2 things: removes the (at this point obsolete) mention of the need to cheat the contract;
Increases the duration to 1 day, which, as discussed on discord, is a better duration (also coherent with the experiment itself).
Might be best to not merge this until a new ROKerbalism release with this change included

Update FSO contract

---

Source/KerbalConstructionTime/GUI/GUI_BuildList.cs

I usually forget to save new vessels as KCT building plans when I'm in the VAB and only notice it back in the Space Center. Going back to the VAB only to click that button is very annoying (load times...). This adds a new button to the options menu in the KCT build list to do it from the Space Center or from Flight.

New "Add to Plans" button in build list options

---

GameData/RP-0/GameParameters.cfg

RO shouldn't do difficulty levels by changing physical properties.
For example, Mars 96% atmospheric CO2 shouldn't become something else
(especially not > 100%)

Set ResourceAbundance=1 for all difficulties

---

GameData/RP-0/Tree/ECM-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

Antennas are useful on their own and shouldn't involve
paying the unlock cost of the capsule

Remove Gemini ECM from antennas

---

GameData/RP-0/Contracts/Space Stations/Martian Space Station.cfg

Because it makes no sense for Mars Station to only need an uncrewed Mars orbit, while Crewed Orbit only becomes available after at least 2 crewed moon landings.
There's a lot more that's dubious about the prereqs for crewed Mars missions, but this one seems like a no-brainer. Was presumably just copied from Moon Station without any real intent

Gate Mars Station behind Mars Crewed orbit

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Near_Future_Electrical.json

They're nocost, and the topazII is practically free, but this
will at least give it some bite.

Add Nuclear tag to NFE reactors

---

.gitignore

When using a symlinked repo in your KSP install, these files get added. Since they don't add anything useful to the GitHub repo, they can be ignored.

Add KCT related config files to .gitignore

---

GameData/RP-0/Tree/ProceduralAvionics.cfg

It seems ProceduralAvionics don't get their module patched in until `[RP-0]` now, so moving this back.

Moved kOS ProcAvionics config to later pass

---

Source/Crew/CrewHandler.cs

KSP 1.10 introduced a change which causes the hero kerbals to return to the applicant list when fired. If they are then re-hired after their retirement date, they immediately retire.
In order to prevent re-hiring once they've retired, we can force kerbals to become "crew" when their retirement date hits. This will properly move them out of the applicant pool and into the "lost" list.
Additionally, only update retirement date if  a kerbal is brand new, or past its retirement date (which would be a duplicate name). This prevents firing a hero kerbal and re-hiring it to push back the retirement date.
Fixes #1409

Fix hiring Hero kerbals after they would have retired.

---

Source/KerbalConstructionTime/GUI/GUI_Editor.cs
Source/KerbalConstructionTime/Utilities/Utilities.cs

Currently, when editing ships with KCT and the prompt shows to unlock all experimental parts it will create a new entry in the build list
Fixes #1395
* When prompt shows to unlock experimental parts, only add vessel to build list if `EditorShipEditingMode` is false, else edit the current ship
* Move KCT *"Save Edit"* to a method, so it can be called from everywhere not only the IMGUI button
* Plural/Singular switching: Fund**s** (the same thing that already existed for part**s**)

Fix unlocking experimental parts creates a new vessel in edit mode

---

GameData/RP-0/Parts/RFProcTanks.cfg
GameData/RP-0/ProcCosts.cfg

ROTanks is giving it a ModuleToolingROTanks, which no longer exists.

Modular cargo bay tooling

---

GameData/RP-0/Tree/RP0TechTree.cfg

Previously you could skip Small Nuclear Fusion Reactors for Improved RTGs.

Replace parent nodes for Improved RTGs

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Near_Future_Electrical.json

still uncosted.
snap-10a to 1966, when the first one was flown
snap-50 and kilopower to near-future, because they never have

Place more NFElectrical reactors in the tree

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
GameData/RP-0/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/ReStock_Plus.json
Source/Tech Tree/Parts Browser/data/Stock__RO_Config.json

Part was configured in RO a long time ago, and apparently forgotten.
https://github.com/KSP-RO/RealismOverhaul/blob/fe5f66506ed60e27db78b62cec2894e1f95f5310/GameData/RealismOverhaul/RO_SuggestedMods/RestockPlus/RO_RestockPlus_Engine_Part_Config.cfg#L78-L83
Also fixed: the stock-engine-as-rd-0105 part got switched from using
liquidEngine3_v2 directly to using a clone of it recently, but
rp-0 wasn't updated to match.
https://github.com/KSP-RO/RealismOverhaul/blob/991ba498d8d15d09b886eb43e28b0e49223105aa/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Engines.cfg#L24

Add config for restockplus Viking

---

Source/KerbalConstructionTime/KCTEvents.cs
Source/KerbalConstructionTime/Persistence/KerbalConstructionTimeData.cs
Source/KerbalConstructionTime/Utilities/Utilities.cs

Makes it so that parts aren't marked as experimental unless in the editor, as that's the only time when you'd care about experimental parts.
Should also allow you to buy parts directly in the R&D screen, which was previously impossible.

Minor experimental parts fixes

---

GameData/RP-0/Contracts/Moon Exploration/Crewed Lunar Flyby.cfg
GameData/RP-0/Contracts/Moon Exploration/Crewed Lunar Orbit 1 Repeatable.cfg
GameData/RP-0/Contracts/Moon Exploration/Crewed Lunar Orbit Repeatable.cfg
GameData/RP-0/Contracts/Moon Exploration/Crewed Moon Landing and Rover.cfg
GameData/RP-0/Contracts/Moon Exploration/Crewed Targeted Moon Landing.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Flyby.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Impactor.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Landing Far Side.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Landing.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Orbiter.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Rover.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Sample Return.cfg

Implements the suggested changes in #1370, section 1. Lander revamp is to come.
Feedback about values or implementation is very welcome!

Lunar Snowball Nerf

---

GameData/RP-0/Tree/ResourceTechs.cfg

So that Experimental Parts Int and Balloon tanks will have a
valid tank config, instead of a confusing tank UI that says
no fuels are valid.
Actual tank parts remain restricted by the tech tree, so this
shouldn't allow building anything that shouldn't be.
Should also makes the behavior when loading a pre-existing .craft
with a not-yet-unlocked config marginally more sane.

Unlock the first tank configs from the start

---

GameData/RP-0/Parts/Science/VI02-BasicTVCamera.cfg
GameData/RP-0/Parts/Science/VI03-ImprovedTVCamera.cfg
GameData/RP-0/Parts/Science/VI04-AdvancedImager.cfg
GameData/RP-0/Parts/Science/VI05-HIResImager.cfg

Since visual scan is disabled in RSS, add biome scan to cameras instead. Most biomes in KSP are relatively simple (lowlands, mountains, craters, etc.) and should be able to be distinguished even with relatively primitive cameras, given enough data.

Add biome scan to cameras

---

GameData/RP-0/Contracts/Milestones/Docking.cfg

per https://discord.com/channels/319857228905447436/516431076680531978/837516316272885790
It seems PartModuleUnlocked is getting broken by the
Experimental Parts feature; the requirement gets satisfied as
soon as the node is queued into KCT (and VAB entered, for the
parts to get added to the Experimental list) instead of waiting
for a part to be researched and purchased.
So use a plain TechResearched requirement instead.
Maybe the conflict can be fixed, but maybe it's not worth trying;
this looks like the _only_ use of PartModuleUnlocked in rp-1

Re-gate First Docking behind unlocking docking ports

---

GameData/RP-0/ProcCosts.cfg

You're already tooling the tank, and tooling the fairing sides/stringers, as we discussed an extra cost for tooling the base doesn't make much sense.

Disable tooling for Proc Fairing/Interstage bases.

---

GameData/RP-0/Contracts/Human Records/CrewedCountRecord.cfg

Descriptions were missing "crew" in two places.

Small grammar fix in crew count record

---

GameData/RP-0/Contracts/Advanced Satellites/GEO Communications Satellites.cfg
GameData/RP-0/Contracts/Advanced Satellites/Molniya Communications Satellites.cfg
GameData/RP-0/Contracts/Advanced Satellites/Tundra Communications Satellites.cfg
GameData/RP-0/Contracts/Early Satellites/Communications Satellite - Early.cfg
GameData/RP-0/Contracts/Early Satellites/Communications Test Satellite.cfg
GameData/RP-0/Contracts/Human Contracts/Orbit Repeatable.cfg
GameData/RP-0/Contracts/Human Contracts/Suborbital Crewed.cfg
GameData/RP-0/Contracts/Human Contracts/Three Crew Orbit Repeatable.cfg
GameData/RP-0/Contracts/Human Contracts/Two Crew Orbit Repeatable.cfg
GameData/RP-0/Contracts/Moon Exploration/Crewed Lunar Orbit 1 Repeatable.cfg
GameData/RP-0/Contracts/Moon Exploration/Crewed Lunar Orbit Repeatable.cfg
GameData/RP-0/Contracts/Moon Exploration/Crewed Moon Landing and Rover.cfg
GameData/RP-0/Contracts/Moon Exploration/Crewed Targeted Moon Landing.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Impactor.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Landing.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Orbiter.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Rover.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Sample Return.cfg
GameData/RP-0/Contracts/Nav Sats/Early Nav Sats.cfg
GameData/RP-0/Contracts/Nav Sats/Second-Gen Nav Sats.cfg
GameData/RP-0/Contracts/Weather Sats/Early Weather Sats.cfg
GameData/RP-0/Contracts/Weather Sats/Geostationary Weather Sat.cfg
GameData/RP-0/Contracts/Weather Sats/Second Gen Weather Sats.cfg
GameData/RP-0/Contracts/Weather Sats/Sun Sync Weather Sats.cfg

Display max completions as `Number of Contracts Completed: x / y` instead of having a separate line for that info.
Uses `x / unlimited` when there is no max, but keeping track of number of completions is still of interest.
The same change to Lunar Far side Lander is in another PR, #1501

Change way of showing max number of completions in contracts

---

GameData/RP-0/Tree/ProceduralAvionics.cfg
Source/Avionics/ProceduralAvionicsTechNode.cs

kOS tech progression follows selected tech level rather than maximum unlocked.
This will require a fix in kOS in addition to this fix.

Changed kOS tech progression to follow selected tech

---

GameData/RP-0/Contracts/Space Stations/Add Crew Module Station.cfg
GameData/RP-0/Contracts/Space Stations/Crew Rotation Station.cfg
GameData/RP-0/Contracts/Space Stations/Life Support Station.cfg
GameData/RP-0/Contracts/Space Stations/New Crew Station.cfg
GameData/RP-0/Contracts/Space Stations/Power Module Station.cfg

Because the "randomness" we get from SelectUnique is very poor
(took ~50 Declines to get NewCrew instead of PowerModule), and
because there doesn't seem to be much harm in allowing them to
be combined

Let space station contracts select the same station

---

GameData/RP-0/Contracts/Advanced Satellites/GEO Communications Satellites.cfg
GameData/RP-0/Contracts/Advanced Satellites/Molniya Communications Satellites.cfg
GameData/RP-0/Contracts/Advanced Satellites/Tundra Communications Satellites.cfg
GameData/RP-0/Contracts/Early Satellites/Communications Satellite - Early.cfg
GameData/RP-0/Contracts/Early Satellites/Communications Test Satellite.cfg
GameData/RP-0/Contracts/Weather Sats/Geostationary Weather Sat.cfg
GameData/RP-0/Contracts/Weather Sats/Second Gen Weather Sats.cfg
GameData/RP-0/Contracts/Weather Sats/Sun Sync Weather Sats.cfg

This also allows the payload-based-rewards to scale up more slowly since completing contracts more often than every 60 days doesn't pay off.

Add shared soft cooldowns to all repeatable sat contracts

---

Source/KerbalConstructionTime/BuildItems/BuildListVessel.cs
Source/KerbalConstructionTime/GUI/GUI_BuildList.cs

Makes the rollout button yellow if the craft fails editor checks, so you can easily tell if you have the correct pad selected.

Add colour to rollout button for failing editor checks

---

GameData/RP-0/Science/BodyScienceParams.cfg
GameData/RP-0/Science/Experiments/BioSample.cfg
GameData/RP-0/Science/Experiments/Photography.cfg

Removes the flying low multiplier, adds a situation mask at flying high for bio and photo experiments, and lowers flying high to 40km. This depends also on a PR to ROKerbalism https://github.com/KSP-RO/ROKerbalism/pull/99 that adds a crewed supersonic series of experiments

Change science at Earth to remove flying low

---

GameData/RP-0/Contracts/Milestones/Suborbital Return.cfg

Added three commas in the suborbital return contract description. Certain about the last one ("Although ..., ... "), but not sure about the first and second ones ("As early as 1947, ...", "... trajectories, but ..."). I think it doesn't hurt, though.

(text) Change text of the suborbital return contract

---

GameData/RP-0/Contracts/X-Planes/RocketPlaneDevelopment.cfg

Being able to complete all 4 in a quick succession with basically the same plane doesn't make much sense. Same goes for coming back to this contract after having done an XPH or 2. Now the player has a choice of waiting and completing all 4 or jumping to XPH after 2 have been completed.

Give soft cooldowns to 'Experimental rocketplanes' and make it unavailable after either XPH is completed

---

Source/KerbalConstructionTime/BuildItems/BuildListVessel.cs
Source/KerbalConstructionTime/GUI/GUI_BuildList.cs
Source/KerbalConstructionTime/KCTVesselTracker.cs
Source/KerbalConstructionTime/KerbalConstructionTime.cs
Source/KerbalConstructionTime/KerbalConstructionTime.csproj
Source/KerbalConstructionTime/Persistence/BuildListStorageItem.cs
Source/KerbalConstructionTime/Persistence/KCTVesselData.cs
Source/KerbalConstructionTime/SceneAddons/FlightAddon.cs
Source/KerbalConstructionTime/SceneAddons/TrackingStationAddon.cs
Source/KerbalConstructionTime/Utilities/Utilities.cs

Currently tracks whether the vessel was originally built in SPH or VAB and stores a unique ID for it. This data will be assigned as soon as the vessel is added to build queue and will survive multiple recoveries and KCT edits.
On staging all the subvessels will retain the same data which means that we can use it to fix the rendezvous contract. Another potential use case is assigning vessels to contracts at launch or through a custom UI instead of relying on CC to pick one dynamically.
Note that the code relies on a new event that was introduced in KSP 1.10.

Add VesselModule for tracking vessels built in KCT

---

GameData/RP-0/Contracts/Milestones/Rendezvous.cfg
Source/CC_RP0/CC_RP0.csproj
Source/CC_RP0/RP1RendezvousFactory.cs
Source/CC_RP0/RP1RendezvousVesselParam.cs

Prevents 2 stages from the same vessel satisfying the contract parameter. 
Additionally has `relativeSpeed` parameter so that 2 vessels whooshing past each other wouldn't be called a *rendezvous*.

Create a custom Rendezvous CC parameter

---

.github/workflows/attachReleaseArtifacts.yml
.github/workflows/build.yml
Source/KerbalConstructionTime/KerbalConstructionTime.csproj
Source/RP0.csproj
makeMeta.py

How to create releases in a repository once Github CI is enabled
Create the new release in Github as you normally would, with the following guidelines
1. The tag **must** be in the format `v[Major].[Minor].[Path].[Build]`.  All four elements are required.  Use 0 if you don't need them.  All elements **must** be integers. EG: `v1.10.0.0`
2. Be sure to point the release to the appropriate branch as desired
3. Title and Description as normal
4. Mark the release as **pre-release** initially.  This is so that CKAN won't pick it up until the release is finished building
5. Publish the release
After publishing, the CI should kick in if you did everything properly.  Once finished, it will automatically attach a ZIP file to the release, EG RP-1-v1.10.0.0.zip
Once that zip appears, you can go into …

Add CI to RP-0

---

GameData/RP-0/Avionics.cfg

Give the LOK service module interplanetary rating, increase Soyuz mass limit to 20 tons to allow for hauling LK lander/ space station components.

Fix Zond/LOK avionics

---

GameData/RP-0/Contracts/Human Contracts/Suborbital Crewed.cfg
GameData/RP-0/Contracts/Milestones/First Flight.cfg
GameData/RP-0/Contracts/X-Planes/CrewedFlight.cfg
GameData/RP-0/Contracts/X-Planes/CrewedHighAtmoDifficult.cfg
GameData/RP-0/Contracts/X-Planes/CrewedSupersonic.cfg

Arbitrary changes that don't really affect RP1, but makes a difference when playing with Headlines. The later game contracts (rewards over 100) are likely too high compared to what is in the 20-100 range. However, I think that these are material for a different PR.

Reputation reward adjustment for early contracts

---

Source/KerbalConstructionTime/KerbalConstructionTime.cs

This alleviates extreme memory usage that results from advancing UT in very large steps -- see https://github.com/mockingbirdnest/Principia/issues/3089

Ease jump to simulation UT in 1d steps when Principia is installed

---

GameData/RP-0/Contracts/ScanSat/Earth_AltimetryLoRes.cfg
GameData/RP-0/Contracts/ScanSat/Mars_AltimetryLoRes.cfg
GameData/RP-0/Contracts/ScanSat/Moon_AltimetryLoRes.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_Average_AltimetryLoRes.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_Average_Biome.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_Average_HiRes.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_Earth.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_GasGiant_Biome.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_Hard_AltimetryLoRes.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_Hard_Biome.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_Hard_HiRes.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_JupiterMoons.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_NeptuneMoons.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_SaturnMoons.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_UranusMoons.cfg
GameData/RP-0/Contracts/ScanSat/Venus_AltimetryLoRes.cfg

Two major consequences: 
1) Now low-resolution contracts will show up only after finishing research human spaceflight science, whereas previously the contract is available once the tech is in the queue. 
2) Since neither SCANsat_Scanner24 nor SCANsat_Scanner2 has RP-1 configs, this pull request will actually allow biome and high-resolution scan contracts to be accepted.

Change the ScanSat contracts to require technology instead of scanner part

---

GameData/RP-0/Tree/ProceduralAvionics.cfg

Siimav mentioned in Discord that a PR would be welcome to add **kOS disk space** to the descriptions of the procedural avionics upgrade parts in the tech tree.
Since it was me who complained about missing this information, it seems only fair that I take this upon myself. This is my very first PR ever, so please let me know if I'm not following the correct workflow.

Add kOS disk space to upgrade part description

---

Source/CareerLog/CareerLog.cs
Source/CareerLog/CareerLogDto.cs
Source/CareerLog/LogPeriod.cs

Tested on RP1 install with and without Headlines. The first field, `Reputation` is KSP's reputation. The field `hype` is unique to Headlines and thus 0 when the mod isn't installed. We want one plot showing Reputation as one polygonal curve, and another curve for Reputation+hype. 
Not sure if the target of the PR should be master.

Adding Reputation and Hype to career logging

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/RN_Soviet_Rockets.json
Source/Tech Tree/Parts Browser/data/ROEngines.json

They both use a 2x engine multiplier, but seem to be costed for the
1x rd-215.
This change makes the initial config an ok deal at 700 and the rd215m
still a decent deal at 600 (lr87 goes 500-760-...) instead of a great
deal and a fantastic deal at 350/250.
Other configs (rd217/225/250) are trickier to compare, but at least
probably aren't becoming overpriced to the point of uselessness.

Fix cost of ROE-215, RN RD-216

---

GameData/RP-0/Contracts/Groups.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_Average_Biome.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_Potato_AltimetryLoRes.cfg
GameData/RP-0/Contracts/ScanSat/RP0_SCANSat_Potato_HiRes.cfg

Fix issue mentioned in https://discord.com/channels/319857228905447436/320197886614700033/908046700965404732.
1. Add biome and HiRes scans to the moon, Mars, and Venus.
2. Remove biome scans from Phobos and Deimos since they have only one biome. Also lowered the reward for altimetry scans.

Adjust ScanSat bodies categories

---

GameData/RP-0/Contracts/Moon Exploration/Crewed Moon Landing and Rover.cfg
GameData/RP-0/Contracts/Moon Exploration/Lunar Rover.cfg

The distribution is uniform area wise, meaning a higher latitude is proportionally less likely as the total area at that latitude is less.
Currently both contracts are set to a max of 45°

Limit both Lunar Rover contracts to a max latitude

---

GameData/RP-0/CrewSettings.cfg

* Pilot, engineer and scientist now have the same G multipliers
* Each experience level adds 0.025 to the multiplier
* Badass flag adds 0.05 to the multiplier
* Courage no longer has any effect on G mult
* Set max sustained at 7.5G
* As an unrelated change - make chute available from experience lvl 0 for all naut classes

Reconfigure naut G limits

---

GameData/RP-0/Contracts/Moon Exploration/Lunar Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Asteroid Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Callisto Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Charon Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Dione Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Enceladus Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Europa Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Ganymede Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Iapetus Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Io Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Mars Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Mercury Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Mimas Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Phobos Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Pluto Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Rhea Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Tethys Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Titan Sample Return.cfg
GameData/RP-0/Contracts/Sample Return/Triton Sample Return.cfg

Current structure often leads to contract completion too early. The reason for the old setup was because in some cases it would fail to complete, but not completing when it should might be desirable over completing too easily.

Move return parameter on all sample return contracts inside vesselGroup

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/TREE-Engines.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json

Places the FWC-SRM config one node after the redesigned (Post Challenger) RSRM, even though it was developed before. This is for game-play reasons, since having two configs in the same node would be odd, and placing the better config later seems like the better choise, especially since it never flew.

Add support for FWC-SRM engine config

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/ResourceTechs.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Advanced_Jet_Engines.json

Add the P&W Model 304. Also move LH2 gate back to Satellite era science to allow the Model 304 to be used, and add gates to FLOX and Syntin.

Add Model 304, more fuel type gates

---

Source/KerbalConstructionTime/GUI/GUI_CrewSelect.cs
Source/KerbalConstructionTime/KCTGameStates.cs
Source/KerbalConstructionTime/KerbalConstructionTime.cs
Source/KerbalConstructionTime/KerbalConstructionTime.csproj
Source/KerbalConstructionTime/PartCrewAssignment.cs

To support KSP 1.11 extracting chute and jetpack to separate inventory items that need to be assigned to the inventory of every kerbal. The stock logic of configuring inventories inside the VAB doesn't work too well since KCT assigns nauts to crewable parts in space center scene after the vessel has been built and rolled to the pad.
Depends on https://github.com/KSP-RO/RealismOverhaul/pull/2537 and https://github.com/KSP-RO/ROKerbalism/commit/27a696fde4daca919c4f50a43a91d3428b1db261.

Add kerbal chute and eva pack selection to KCT crew assignment dialog

---

GameData/RP-0/Tree/RFTechLevels.cfg

Use the RF partupgrade system to allow MLI upgrades to upgrade tank types over time, rather than assigning MLI based on the tank type.
Conventional, Isogrid and Service Modules gain upgrades from 1-100 layers
Balloon tanks require more advanced technology to mount MLI, due to the difficulty in fixing MLI to the thin walls of Balloon tanks
RO PR: https://github.com/KSP-RO/RealismOverhaul/pull/2595

Add MLI PARTUPGRADES

---

GameData/RP-0/Contracts/Surface Outposts/MarsOutpost.cfg
GameData/RP-0/Contracts/Surface Outposts/MarsOutpostWithLab.cfg
GameData/RP-0/Contracts/Surface Outposts/MoonOutpost.cfg
GameData/RP-0/Contracts/Surface Outposts/MoonOutpostWithLab.cfg

Fixes the Surface Outpost contracts so that it doesn't choose a random vessel and locks onto it.

Prevent Surface Outpost contracts from choosing any vessel

---

GameData/RP-0/ProcCosts.cfg

The patch to set RealFuels tanks cost to 0 when the mass is config-defined instead of code driven didn't apply to any parts due to being in a too early pass.
**This change can affect a lot of parts, since over 1200 parts in RO set the mass of RF tanks in this way.  Discussion is needed reagarding if this is the correct way to fix it!**

Fix RF basecost patch not getting applied

---

GameData/RP-0/CrewTrainingTimes.cfg

Dynasoar Cabin in ProtoSpaceplane to go with the Dyanasoar Cockpit
Apollo D2 Mission Modules to ApolloD2 with the Decent Module
ROC and SXT Apollo LEMs to ApolloLEM

Add missing Crew Training for RO parts

---

GameData/RP-0/ResourceCosts.cfg

Move resource costs that were previously set in RO to RP-0, where they probably belong. RO will be left using whatever costs CRP defines.

Move RF resource cost setting to RP-0

---

Source/Avionics/ModuleProceduralAvionics.cs
Source/Avionics/ProceduralAvionicsWindow.cs
Source/KerbalConstructionTime/VesselBuildValidator.cs

This allows trying out configs without having to buy them. KCT will prevent building vessels that have configs that aren't available. It will still offer to purchase the config if the tech is researched.

Add PartModule-level validation to KCT and make procedural avionics the first to use it

---

GameData/RP-0/Science/Experiments/RPWS.cfg
GameData/RP-0/Tree/Crossfeed.cfg
GameData/RP-0/Tree/EntryCostModifiers.cfg

Hi again KSP-RO team,
This is like KSP-RO/RealismOverhaul#2612 but for RP-1.
Referencing KSP-CKAN/CKAN/pull/3525 so I can find this again later easily.

Fix cfg syntax errors

---

GameData/RP-0/ResourceCosts.cfg

Hi KSP-RO team,
After #1640, RP-0 now has `:FOR[RealismOverhaul]` clauses in it. ModuleManager inteprets `:FOR` as a declaration that we are the specified mod; clauses using `:NEEDS[RealismOverhaul]` would be activated even if the real RO is absent. RP-0 depends on RO, so there should be no impact as long as the user's install is valid, but it's still better to avoid this:
https://github.com/sarbian/ModuleManager/wiki/Patch-Ordering#the-beforemodname-formodname-and-aftermodname-directives
> It is not recommended to use the :FOR directive to refer to other mods than the one you are writing.
Now these are changed to `:FOR[RP-0]`.
Cheers!

Fix :FOR[RealismOverhaul] in RP-0

---

GameData/RP-0/Tree/RP0TechTree.cfg

Because gating it behind the 7sci of Early Mat Sci basically
made it useless.
per https://discord.com/channels/319857228905447436/620690446540341261/964606272617996298
Also shifted the solid nodes a bit to make the tree a bit clearer.

Make Basic Solids depend on Post-War Mat sci

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Stock__RO_Config.json

Fix the issue mentioned in https://discord.com/channels/319857228905447436/512556137380315139/964727589581258802.
Add RP-1 configs for `HighGainAntenna5_v2`.
Requires [RO-#2639](https://github.com/KSP-RO/RealismOverhaul/pull/2639).

Support new HG-5 antenna model

---

Source/HarmonyPatcher.cs
Source/RP0.csproj

* Remove *Purchase all* button from under-research nodes
* Remove *Purchase* button from individual parts that are in nodes that are under-research
* Add *Purchase* button to experimental parts that have completed research
* KSP itself and hopefully also contracts no longer consider experimental parts as being available

Improve RnD UX for experimental parts and under-research tech nodes

---

GameData/RP-0/Avionics.cfg
GameData/RP-0/Tree/ProceduralAvionics.cfg

Use patching strategy of create-or-edit instead of create for kOS PartModule.  RO global patches now add one properly, and run first.
Extract individual patches into a tag-and-then-apply structure.  Removes copy-pasta-related errors.  Tag the part once, let the patch at the end apply consistent values.
Use create-or-edit for most ModuleAvionics patches.  Especially ones that can go on one line with a single setting -- Veyl hates whitespace!
Minor patch cleanup

Fix kOS Patch Application

---

GameData/RP-0/Contracts/Early X-Plane Research/CrewedSupersonic.cfg
GameData/RP-0/Contracts/Early X-Plane Research/RocketPlaneDevelopment.cfg
GameData/RP-0/Contracts/Suborbital Rocket Development/DistanceSoundingDifficult.cfg
GameData/RP-0/Contracts/Suborbital Rocket Development/DistanceSoundingIntermediate.cfg
GameData/RP-0/Contracts/Suborbital Rocket Development/SoundingDifficult.cfg
GameData/RP-0/Contracts/Suborbital Rocket Development/SoundingIntermediate.cfg

Done mostly according to the spreadsheet, except that I gave a lower reward to altitude SRs vs. Downrange. Also, all X-plane contracts are giving Rep, as it's not clear to me how we would go about giving Rep only to later completions beyond a "required" level.

Add soft cooldown reputation reward to repeatable SRs and X-Planes

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/ECM-Parts.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json
Source/Tech Tree/Parts Browser/data/RN_Soyuz.json

Add small entry cost to Hydrazine RCS so it isn't unlocked if "Hydrazine Fuel" and "Catalyst RCS" nodes are unlocked.
Should resolve https://github.com/KSP-RO/RP-0/issues/1704, testing needed.

Fix Hydrazine

---

RP-0.netkan

Dynamic Battery Storage disables itself when Kerbalism is installed, so it doesn't cause `incoherent behaviour`

Remove DBS from conflicts in netkan

---

GameData/RP-0/Tree/CockpitUpgrades.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Aviation_Cockpits.json

Because they shouldn't be able to go suborbital, that's X-15's niche

Give a max altitude to F-10x cockpits

---

GameData/RP-0/Tree/EntryCostModifiers.cfg

In PR #1411, The ECM link from the RD-103 was removed from the RD-107/108 to be replaced with the RD-200. As as result the RD-107/108 became 40000 funds cheaper and the RD-103 became a 47000 fund dead end.
By adding RD103-TP to R7-Engines, 25000 funds of the RD-103 cost is now applied forward to the RD-107/108 reducing the sunk cost of the RD-103 without effecting the RD-107/108 cost. The R7 upper stages starting with the RD-0105 will be more expensive for players that have not purchased the RD-103 or RD-107/108.

Restore RD103-TP to R7 ECMs

---

GameData/RP-0/KCT/KCT_ModuleTemplates.cfg

Compatibility fix for updated failure logic in TF.
`allowRestart` starts `true` in `ModuleEngines`.

Set allowRestart for TF compatibility

---

GameData/RP-0/Science/Experiments/CosmicRay.cfg
GameData/RP-0/Science/Experiments/GlobalExperimentPatches.cfg

Renames the Cosmic Ray experiment back to 1_5 to prevent craft from breaking, and creates a global patch to perform a dataScale division that was not working in the experiment definitions

Science hotfix

---

GameData/RP-0/Strategies/Leaders/LeadersAdmin.cfg

The Soviet Union still existed during the relevant time period. "Former" is unnecessary

Improve Glushco description

---

Source/KerbalConstructionTime/GUI/GUI_NewLC.cs

Creates a simpler way to view the daily fund impact of building a new LC.

Funds per day tooltip for Build Cost in New LC GUI

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Stock__RO_Config.json

similar to #1346: 350 funds for each of 4 verniers doesn't seem to make
sense, especially when paired with 3x 2-nozzle rd250 (which would cost
1140, based on 760 for ROE's 4-nozzle rd250) for a tsyklon first stage.
so assume 350 was meant to be the cost of the full 4-vernier engine,
and divide by 4. RO already divides mass & thrust by 4.

Split cost of stock rd855

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Stock__RO_Config.json

Half the cost of ROE's double-rd215, minus a bit to account for
not having anything for attitude control
for https://github.com/KSP-RO/RealismOverhaul/pull/2712

Configure RO-RD215

---

GameData/RP-0/Contracts/X-Planes/CrewedFlight.cfg
GameData/RP-0/Contracts/X-Planes/CrewedHighAtmo.cfg
GameData/RP-0/Contracts/X-Planes/CrewedHighAtmoDifficult.cfg
GameData/RP-0/Contracts/X-Planes/CrewedSupersonic.cfg
GameData/RP-0/Contracts/X-Planes/RocketPlaneDevelopment.cfg

Leverage the new CC resetChildrenWhenVesselDestroyed option to fix X-plane contracts staying locked to a destroyed vessel.
**NEEDS https://github.com/KSP-RO/ContractConfigurator/releases/tag/v99.9.9.3 TO WORK**

Reset X-plane contracts when vessel gets destroyed

---

GameData/RP-0/Tree/ECM-Engines.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json

Add 1000 cost to both to prevent becoming available if parts with MMHRCS or BipropRCS unlocked.

Fix MMH+NTO and UDMH+NTO early unlocks

---

Source/Tooling/ModuleToolingPTank.cs

Adds simple tooling to the offset smooth cone from ProcParts. The tooling ignores the offset and only looks at the diameters and length of the part

Simple Offset Cone tooling

---

Source/KerbalConstructionTime/GUI/GUI_CrewSelect.cs

Old code filled only the first crewable part found which made the Apollo CM + LEM combo not being able to crew the CM if the LEM was the first part found.
Tested with Apollo CM + LEM, Gemini, Mercury, X-15 and non crewable vessels.

Fix KCT not allowing crewing of parts with crew capacity other than the first one found

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Chaka_Monkey.json

Stock sepmotors were moved a while ago, but everyone forgot this existed. (it's probably also too cheap, and lacks a TF config, so it's still too good, but at least this will save Tiny Tim's job)

Move Chaka Monkey small sepmotor out of start node

---

GameData/RP-0/Contracts/Space Stations/First Space Station.cfg
GameData/RP-0/Contracts/Space Stations/Improved Space Station.cfg

Adds a set of 3 contracts based on the Skylab station. 1st contract requires launching a more advanced station and crewing it with 3 crew for 30d. 2nd contract involves crewing for 60d, and 3rd contract involves crewing for 90d. Both 2nd & 3rd contract can be completed twice, with the former intended to be required and the latter optional.
Also allows `Duration` timers to count down while outside the vessel scene, allowing for players to focus on other contracts. (Should a note/popup be added to let players know they can focus on other contracts?)

Add to the Earth Space Station Program

---

GameData/RP-0/Science/HardDriveConfigs.cfg

22 slots covers 11 earth biomes, flying high + space low.
Because it's silly that a camera can't take pictures of trees after having taken pictures of water, grass and rocks; as long as there's film, let it take pictures.
Also because juggling slots is too micromanagey.
There will still be micromanagement if the camera isn't recovered and the recovery part has too few slots, but this won't make it any worse?
(per https://discord.com/channels/319857228905447436/620690446540341261/1048371772753449031 )

Give Early Film Camera all the slots

---

GameData/RP-0/Tree/ECM-Parts.cfg
Source/Tech Tree/Parts Browser/data/DECQ_R7_SOYUZ.json

Giving the RD_0110 part a rd-0107 ECM ends up overriding the RD-0110 config's own 2000+rd0107 ECM.
An engine part doesn't need to list configs in its ECMs for the config costs to apply, so just delete the weird ECM.
Partial fix for #1862

Remove broken RD-0110 ECM

---

GameData/RP-0/Tree/TREE-Engines.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json
Source/Tech Tree/Parts Browser/tree_engine_cfg_generator.py

Mostly to give a clue why a config isn't actually available despite
the tree showing a PARTUPGRADE for it
(also includes a partupgrade for xlr35, forgot I had that in my tree)
Modifies the parts browser, which possibly means we don't want to merge this without also updating the .exe, and I'm not going to do that.

Add speclevel to engine CONFIG PARTUPGRADEs

---

Source/Tech Tree/Parts Browser/data/Engine_Config.json

I missed the JSON file when fixing this in #1875. Now it will stay fixed.

Correct typo in ECM for RD-252. Part Two: the JSON file

---

GameData/RP-0/Tree/RP0TechTree.cfg

Remove "after accepting the Unlock Parts contracts" as the contract doesn't exist anymore.

Correct Starting Parts node description

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Engines.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
GameData/RP-0/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json
Source/Tech Tree/Parts Browser/data/ROEngines.json
Source/Tech Tree/Parts Browser/data/ROEnginesExtended.json
Source/Tech Tree/Parts Browser/data/ReStock_Plus.json

Add support for the new C-1, MB-35/60, NERVA, NERVA II, and NERVA XE parts in ROEngines.
Also config a really nice RD0410 model from RestockPlus.
For https://github.com/KSP-RO/ROEngines/pull/186

Support for new BDB parts in ROEngines

---

GameData/RP-0/Science/HardDriveConfigs.cfg

The CMs are already getting sample slots set from crew experiments config but the LEM has no sample slots without this.

Add Apollo drive configs to ROC BDB Apollo parts

---

GameData/RP-0/Contracts/Flyby Contracts/Deimos Flyby.cfg
GameData/RP-0/Contracts/Flyby Contracts/Phobos Flyby.cfg

Remove "transmit science" from contract descriptions

Correct Phobos and Deimos flyby contract descriptions

---

Source/Tooling/ModuleToolingPTank.cs

The offset cone in ProcParts was merged into the normal smooth cone, so the tooling for that version isn't needed now.
(See https://github.com/KSP-RO/ProceduralParts/pull/328)

Remove unused Offset cone tooling

---

GameData/RP-0/Science/Experiments/Photography.cfg
GameData/RP-0/Science/Experiments/Temperature.cfg

Early suborbital rockets had cutouts for their cameras and other sensors. Lets just pretend we can also add cutouts to fairings for the early experiments. This would open up more possibilities for suborbital rocket design beyond either having a 1.25m section or have fairings that need to be jettisoned in the atmosphere before they can start running experiments.

Allow early experiments to run when shrouded

---

GameData/RP-0/Tree/TREE-Engines.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json

New ROTank parts were added to the start node instead of unlockParts and have been moved.
Hide engine configs from the tech tree if they are the default config for an engine part from an RO mod. An inconsistency with the Viking-5C is addressed in another open PR. The RD-170 and RD-191 still have some inconsistencies. 
The rest appeared from running the Part Browser. I guess it wasn't properly synced in before?

Hide default engine configs

---

GameData/RP-0/Contracts/Moon Exploration/Lunar Impactor.cfg

Put an end to the crewed impactor jokes. When this contract comes up it should be pretty obvious it "should be" done with a probe since you don't have access to capsules yet

Remove "Uncrewed" Lunar Impactor contract name

---

README.md

Replaced https://github.com/KSP-RO/RP-0/wiki/Recommended-Extra-Mods to https://github.com/KSP-RO/RP-0/wiki/Extra-Mods-to-Consider in readme file

Fixed link to recommended mod page

---

GameData/RP-0/Tree/PFTechLevels.cfg

Tested on my system: MM.CC looks right now (`density = 0.18`) and a new career had the correct behaviour.

Fix ordering of PF tech level patch

---

GameData/RP-0/Tree/TREE-Engines.cfg

Any reason why XLR35-RM-1 XLR11 subconfig should add +200f to the engine price, which already is quite high, sitting at 300 thanks to a human-rated, spaceplane natue of the original config? The combined cost is, like, **more than even RD108 costs**, for a second. If anything, it should be exactly the opposite: disposable variant of the engine, speculatively optimized for mass production.
Looking at similar-ish engines in game RN, like RD-200 or Gamma 4, pricepoint of ~200 cr for a disposable four-chambered gimballed turbopump motor looks plausible. No historical sources exist on real unit price AFAIK, since historically it was a one-off prototype, and they wouldn't account for speculative serial production anyway, so balance takes the point.
And from the point of balance, 500cr disposable …

XLR35-RM-1 subconfig price reduction

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/TREE-Engines.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json

Split X-405H proposals into one config without restart, and one with restart. Also adjust mass a bit based on Convair documents.
RO PR: https://github.com/KSP-RO/RealismOverhaul/pull/2619

Split X-405H configs

---

GameData/RP-0/Contracts/Early Satellites (Heavy)/FirstScienceSat-Heavy.cfg
GameData/RP-0/Contracts/Early Satellites (Light)/FirstScienceSat.cfg
GameData/RP-0/Parts/Science/US2.cfg
GameData/RP-0/Science/Configure.cfg
GameData/RP-0/Science/Experiments/CosmicRay.cfg

This requires 1% of the experiment to be transmitted to RnD and doesn't actually care what vessel (or vessels) did it.

Remove the hacky cosmic ray sci experiment and make contracts use RP1CollectScience parameter instead

---

GameData/RP-0/Contracts/Groups.cfg
GameData/RP-0/Contracts/Spaceplanes/DockingPlane.cfg
GameData/RP-0/Contracts/Spaceplanes/FirstPlaneOrbit.cfg
GameData/RP-0/Contracts/Spaceplanes/OrbitalPlane1.cfg
GameData/RP-0/Contracts/Spaceplanes/OrbitalPlane2.cfg
GameData/RP-0/Contracts/Spaceplanes/OrbitalPlane3.cfg
GameData/RP-0/Contracts/Spaceplanes/RendezvousPlane.cfg
GameData/RP-0/Contracts/Spaceplanes/SuborbitalPlaneCrewed.cfg
GameData/RP-0/Programs/Programs.cfg

I've tested that the program and contracts are present in-game but that's about all.  And I have no idea how to balance things for NotBudgets so I just took the capsule equivalent contract rewards and added 20%.
Note that the way I've done this, the program isn't an alternative to `CrewedOrbit`, because it requires completing the orbital re-entry contract.  So instead it's either a follow-on or a parallel development.  And I've blocked taking both the capsule and spaceplane version of a given contract simultaneously, so you can't get paid twice for one mission, but there's no reason you can't use your spaceplane to complete `CrewedOrbit` contracts if it's ready in time.

First draft of spaceplane program and contracts

---

GameData/RP-0/Tree/ResourceTechs.cfg

By changing the order in which the patches are applied. This change means oxygen gas in legacy RF `ServiceModule` tanks are unlocked in the new default `crewSurvivability` tech, instead of `standardDockingPorts`.
Thank @NathanKell for the idea. 
Should finally solve #1964.

Default oxygen gas tanks to unlock in tech crewsurvivability

---

GameData/RP-1/Contracts/Groups.cfg
GameData/RP-1/Contracts/Sounding Rockets/SoundingDifficult.cfg
GameData/RP-1/Contracts/Sounding Rockets/SoundingIntermediate.cfg

* Remove 10% base variation
* Fix payload amount to 75 units, for all levels
* Reduce the altitude increase per level from ~100km to 60km
* Cap levels to 15
* Completing the difficult variant will make the next intermediate have the exact same parameters

Rework the altitude SR contracts

---

Source/CC_RP0/CC_RP0.csproj
Source/CC_RP0/HasCompleted.cs
Source/CC_RP0/HasCompletedFactory.cs
Source/CC_RP0/RP1ContractTracker.cs

Add RP1ContractTracker scenario module. Tracks configured contract completions per KCTVesselID. Contract tag used if available, otherwise name.  UT of each completion is also stored.
Add HasCompleted vessel parameter. Checks RP1ContractTracker for contracts already completed by KCTVesselID, either current or in tracked/unloaded VPG. Invertible. Multiple contract tags allowed, results ORed.
Example syntax:
PARAMETER
{
name = ExclusiveLaunch
type = HasCompleted
title = Do Not Complete Other Accepted Contracts
invertParameter = true
contractTag = distance_SoundingRocket
contractTag = alt_SoundingRocket
contractTag = other_SoundingRocket
contractTag = exclude_EarlySatellite
}

HasCompleted vessel parameter and RP1ContractTracker

---

GameData/RP-1/Programs/Programs.cfg

When under Mars/Venus surface exploration programs, these optional repeatable contracts (originally present in the Early Inner Solar System Probes program) were available, but were missing confidence.
There are probably other contracts like these broken in the same way, and as more optional contracts are added we should be careful not to miss adding them to the appropriate lists.

Fix Mars/Venus orbiter contracts confidence

---

GameData/RP-1/Contracts/X-Plane Research/RocketPlaneDevelopment.cfg
GameData/RP-1/Contracts/X-Plane Research/RocketPlaneDevelopmentOptional.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesHighAltitude.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesHighAltitudeOptional.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesKarman.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesSuborbital.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesSupersonicMach2.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesSupersonicOptionalHigh.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesSupersonicOptionalLow.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesSupersonicOptionalMid.cfg

Following changes:
Removing the generic SuperSonicOptional contract - splitting it into 3 contracts, that do the following:
2 optional flights before the 450m/s required
3 optionals between 450 and mach 2
12 optionals after mach 2.
retuning of reputation for all of that.
retuning of rep for rocketplay/altitude contracts.
Optional SS contracts only require 3 minutes of velocity maintenance.

Xplane retuning and ss optional changes

---

Source/KerbalConstructionTime/BuildItems/FundTarget.cs

The algorithm used to detect a fund target failed when daily income became relatively large, which caused it to error out towards the mid to late game.
With the new algorithm, it will warp to the soonest time that it determines the listed amount of money will be available, even if it's very slightly above the desired fund target.

Fix WarpToFundTarget with high incomes

---

Source/CC_RP0/RP1CollectScience.cs
Source/CC_RP0/RP1CollectScienceFactory.cs

Now also updates the widget with biome completion percentages.

Add minSubjectsToComplete attribute to CollectScience parameter

---

Source/CareerLog/CareerLog.cs
Source/CareerLog/CareerLogDto.cs
Source/CareerLog/LogPeriod.cs
Source/KerbalConstructionTime/KerbalConstructionTime.cs
Source/KerbalConstructionTime/Utilities/Utilities.cs
Source/Maintenance/MaintenanceHandler.cs
Source/UnlockCreditHandler.cs

Log individual maintenance components & many more

---

GameData/RP-1/CustomBarnKit.cfg
GameData/RP-1/Localization/en-us.cfg
GameData/RP-1/Programs/Programs.cfg
Source/Harmony/Administration.cs
Source/Harmony/Strategy.cs
Source/Programs/Program.cs
Source/Programs/ProgramHandler.cs
Source/Programs/ProgramStrategy.cs
Source/Properties/AssemblyInfo.cs
Source/RP0.csproj
Source/UpgradeScripts/v2_4_AdminLevels.cs

* Programs now have a 'slots' field. *Admin Building now has a slot limit rather than program limit
* Apply slots field to all existing programs
* Add upgrade script to handle transition from pre-2.4 Admin.

Implement major/minor program support.

---

GameData/RP-1/Contracts/Lunar Surface Probes/MoonOrbiter.cfg
GameData/RP-1/Contracts/Lunar Surface Probes/MoonOrbiterOptional.cfg

Fixes Lunar Orbiter & Mapper contracts requiring a physical level 2 imager. Uses RP1 parameter, requiring one biome be 100% complete.
Need comment on whether `hideChildren = true` is needed for the RP1CollectScience parameter. Currently removed since the parameter provides transparency on the progress of the biome sci collected.

Fix Lunar Mapper Contracts

---

GameData/RP-1/Strategies/Leaders/LeadersContractors.cfg
GameData/RP-1/Strategies/Leaders/LeadersEngineers.cfg
GameData/RP-1/Strategies/Leaders/LeadersScientists.cfg
GameData/RP-1/Strategies/Leaders/LeadersSubcontractors.cfg

Long-term, I think the autogenerated text for effects has some issues, but that should probably wait until after we've done some more leader shuffling.
I removed the word "tech", because if "research speed" gets put on the end automatically, it's unnecessary.
Thanks to the users who pointed these errors out

Correct grammar

---

GameData/RP-1/Contracts/Earth Crewed/OrbitalFlight2.cfg

Allows the player to start in either orbit 1 or orbit 2, rather than just orbit 1, in the "Orbital Flight with Maneuvers and 2+ Crew" contract

Allow Flexibility in OrbitalFlight2 Contract

---

GameData/RP-1/Contracts/Earth Crewed/OrbitalTestFlight.cfg
GameData/RP-1/Contracts/Earth Crewed/OrbitalTestFlightAnimal.cfg
GameData/RP-1/Contracts/Earth Crewed/SuborbitalTestFlight.cfg
GameData/RP-1/Contracts/Space Stations/Add Crew Module Station.cfg
GameData/RP-1/Contracts/Space Stations/First Space Station.cfg
GameData/RP-1/Contracts/Space Stations/Improved Space Station.cfg
GameData/RP-1/Contracts/Z Disabled Contracts/Lunar Space Station.cfg.DISABLED
GameData/RP-1/Contracts/Z Disabled Contracts/Martian Space Station.cfg.DISABLED
GameData/RP-1/Contracts/Z Disabled Contracts/Surface Outposts (Disabled)/MarsOutpost.cfg.DISABLED
GameData/RP-1/Contracts/Z Disabled Contracts/Surface Outposts (Disabled)/MarsOutpostWithLab.cfg.DISABLED
GameData/RP-1/Contracts/Z Disabled Contracts/Surface Outposts (Disabled)/MoonOutpost.cfg.DISABLED
GameData/RP-1/Contracts/Z Disabled Contracts/Surface Outposts (Disabled)/MoonOutpostWithLab.cfg.DISABLED

Addresses #2106. Added `disableOnStateChange = false` to `HasCrewCapacity` parameters since it appears that once failed, they cannot return to being uncompleted.

Unstick HasCrewCapacity in contracts

---

GameData/RP-1/CustomBarnKit.cfg
GameData/RP-1/Programs/Programs.cfg

It'd actually still have a bit of an impact on balance in the form of maintenance costs, build time, and the fact that program payout depends on difficulty, while construction cost does not, but this could at least help a bit if too many construction costs is an issue.

Reduce astro3 cost and crewed lunar payout

---

GameData/RP-1/Contracts/Early Satellites (Heavy)/Downrange6000-Heavy.cfg
GameData/RP-1/Contracts/Early Satellites (Heavy)/Downrange7500-Heavy.cfg
GameData/RP-1/Contracts/Early Satellites (Light)/Downrange6000.cfg
GameData/RP-1/Contracts/Early Satellites (Light)/Downrange7500.cfg
GameData/RP-1/Contracts/Earth Satellites/ComTestSat.cfg
GameData/RP-1/Contracts/Earth Satellites/EarlyComNetwork3.cfg
GameData/RP-1/Contracts/Earth Satellites/EarlyComNetwork4.cfg
GameData/RP-1/Contracts/Earth Satellites/EarlyComSat.cfg
GameData/RP-1/Contracts/Earth Satellites/FirstComSat.cfg
GameData/RP-1/Contracts/Earth Satellites/FirstGEOSat.cfg
GameData/RP-1/Contracts/Earth Satellites/FirstMolniyaSat.cfg
GameData/RP-1/Contracts/Earth Satellites/FirstNavSat.cfg
GameData/RP-1/Contracts/Earth Satellites/FirstTundraSat.cfg
GameData/RP-1/Contracts/Earth Satellites/FirstWeatherSat.cfg
GameData/RP-1/Contracts/Earth Satellites/GEORepeatComSats.cfg
GameData/RP-1/Contracts/Earth Satellites/GeoComSatNetwork.cfg
GameData/RP-1/Contracts/Sounding Rockets/DistanceSoundingDifficult.cfg
GameData/RP-1/Contracts/Sounding Rockets/DistanceSoundingIntermediate.cfg
GameData/RP-1/Contracts/Sounding Rockets/Downrange.cfg
GameData/RP-1/Contracts/Sounding Rockets/SoundingDifficult.cfg
GameData/RP-1/Contracts/Sounding Rockets/SoundingIntermediate.cfg
GameData/RP-1/Contracts/Sounding Rockets/SoundingRocketAdvancedBio.cfg
GameData/RP-1/Contracts/Sounding Rockets/SoundingRocketAdvancedBioOptional.cfg
GameData/RP-1/Contracts/Sounding Rockets/SoundingRocketBio.cfg
GameData/RP-1/Contracts/Sounding Rockets/SoundingRocketBioOptional.cfg

Trying to fix #2133:
"Sounding rocket contracts, 4500+ km downrange contracts and many satellite contracts ask for a fixed amount of sounding/comsat/navsat/weather sat payload. However, there is rounding in the game that can result in 499.99 shown as 500 and the contract not completing, even though the player was sure that the rocket has enough payload."
All the contract now have a margin of 0.01, which is apparently not enough. This PR changes 0.01 to 0.1.

Fix sounding and satellite payload rounding errors issue

---

GameData/RP-1/Contracts/Groups.cfg
GameData/RP-1/Contracts/Lunar Surface Probes/MoonLandingReturn.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesHighAltitude.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesHighAltitudeOptional.cfg

According to Maxsimal on Discord, contract series with more than three max completions should have a cooldown, which includes X-plane (altitude), with four max completions, but not lunar sample return, with three max completions.

Remove cooldown on lunar sample return and add cooldown on X-plane (altitude)

---

GameData/RP-1/Contracts/Jupiter Observation/Jupiter Orbit_Rep.cfg
GameData/RP-1/Contracts/Mars/MarsOrbitRepeat.cfg
GameData/RP-1/Contracts/Mercury Exploration/Mercury Orbit_Rep.cfg
GameData/RP-1/Contracts/Saturn Observation/Saturn Orbit_Rep.cfg
GameData/RP-1/Contracts/Venus/VenusOrbitRepeat.cfg

The writing is awkward and I don't see why it needs to be included in that shortened form. Also, coplanar is one word and not hyphenated, see KSC-DF-107 Rev F 3.9.4 a.2

Remove inclination mention from moonless bodies for orbital science probe contracts

---

GameData/RP-1/ToolingDefinitions.cfg

Increase the max utilization of advanced composite tanks to match standard composite tanks
Make Starship tanks cheaper to balance their high weight
Change modern balloon tanks to only a bit more expensive than their refined counterparts (25% instead of 40%) and increase their tooling cost to 7% more than refined balloon tanks. 
Please merge at same time as RO PR

Rebalance later tanks

---

GameData/RP-1/Contracts/Earth Crewed/OrbitalFlight2.cfg

Reverts my previous PR done to the contract. `completeInSequence = true` is removed from the orbital parameters, which should still allow the contract to be done in any order instead of strictly orbit 1 -> orbit 2.

Fix Orbital Flight w/ 2 Crew missing orbital requirements in flight

---

GameData/RP-1/Contracts/Earth Satellites/EarlyComNetwork3.cfg
GameData/RP-1/Contracts/Earth Satellites/EarlyComNetwork4.cfg
GameData/RP-1/Contracts/Earth Satellites/GeoComSatNetwork.cfg

#2134 fixed the issue for all single satellite missions, but not for satellite network missions, which needed changes in 3-4 lines and not in just one.  This PR changes all remaining 0.01 margins to 0.1.

Fix the remaining sounding and satellite payload rounding errors

---

GameData/RP-1/Contracts/Early Satellites (Heavy)/FirstPolarSat-Heavy.cfg

This was in the correct program, but appeared in the Early Satellites-light contract group in Mission Control.

Fix First Polar Orbit-Heavy contract group

---

RP-1.netkan

I'm sorta half-joking with this, (and it's like 2 am) but I just can't believe how many people we get in the server who don't install the express install. If they can't follow these instructions then... I don't know
I did do a quick check and this has less characters than the express install's description so it should fit into 2 lines.

Update RP-1 description on ckan to make it more clear

---

GameData/RP-1/Contracts/Earth Satellites/EarlyComNetwork3.cfg
GameData/RP-1/Contracts/Earth Satellites/EarlyComNetwork4.cfg
GameData/RP-1/Programs/Programs.cfg

Give both programs the same per-year payout so there doesn't exist a perverse incentive to pick commnet over targeted sats.
Also, at least with the contracts we have right now in those programs I really can't justify commnet paying more than targetedSats.

Revise TargetedSats and CommNetwork balancing

---

GameData/RP-1/Contracts/Asteroid Exploration/Ceres Landing.cfg
GameData/RP-1/Contracts/Asteroid Exploration/Vesta Landing.cfg
GameData/RP-1/Contracts/Jovian Moon Landings/Callisto Landing.cfg
GameData/RP-1/Contracts/Jovian Moon Landings/Europa Landing.cfg
GameData/RP-1/Contracts/Jovian Moon Landings/Ganymede Landing.cfg
GameData/RP-1/Contracts/Jovian Moon Landings/Io Landing.cfg
GameData/RP-1/Contracts/Saturnine Moon Landings/Dione Landing.cfg
GameData/RP-1/Contracts/Saturnine Moon Landings/Enceladus Landing.cfg
GameData/RP-1/Contracts/Saturnine Moon Landings/Iapetus Landing.cfg
GameData/RP-1/Contracts/Saturnine Moon Landings/Mimas Landing.cfg
GameData/RP-1/Contracts/Saturnine Moon Landings/Rhea Landing.cfg
GameData/RP-1/Contracts/Saturnine Moon Landings/Tethys Landing.cfg
GameData/RP-1/Contracts/Saturnine Moon Landings/Titan Landing.cfg
GameData/RP-1/Programs/Programs.cfg

Still need to balance rewards, but all but two are going into disabled programs anyway

Add some landing contracts

---

GameData/RP-1/Contracts/Groups.cfg

The most common start in PLC seems to be taking the two SR programs, and I at least find it annoying that X-planes sits between them in MC. (Especially given that most research contracts depend on Karman Line in development.)

Make development/research contract groups adjacent

---

GameData/RP-1/ProcCosts.cfg

Fix two places where nodes that are not top-level were attempted to be filtered by using `|` to match multiple nodes (this doesn't work)
This might affect balance, so testing is needed!

Fix MM issue by splitting ORed nodes

---

GameData/RP-1/Programs/Programs.cfg

Flight planning is unlocked with the first mission control upgrade, so the program description needs updating.

Update Early Lunar Probes program description

---

GameData/RP-1/Avionics.cfg

This would improve support for custom service module or deorbit stages, including ones with HTP.

Increase avionics to 1.6t for Mercury capsule

---

Source/Harmony/StrategySystem.cs
Source/Leaders/StrategyRP0.cs
Source/Maintenance/MaintenanceGUI.cs
Source/Programs/Program.cs
Source/Programs/ProgramFundingOverview.cs
Source/Programs/ProgramHandler.cs

This PR fixes issues with Milt Rosen (and any other future leaders that might change program duration) by changing the program backend so that instead of computing everything based off (time - acceptedTime) it tracks the fraction elapsed. This means that if you take Rosen halfway through, your 20% faster will only affect the remaining 50% of program duration, and if you then fire him only the remaining duration will get extended back out. Taking or firing him after program deadline expiration still behaves a little strangely but this fixes the majority of the issues. Will close #2207

Rework program progress, duration, funding to be incremental

---

RP-0.netkan
RP-1.netkan

Hi!
This is a pending follow-up item for KSP-CKAN/CKAN#3892.
Sometime in the next 3 months or so, there will most likely be a new CKAN client release featuring "deep recommendations", where all the dependencies in a changeset will contribute recommendations and suggestions, instead of just what the user clicks on.
This pull request applies the `suppress_recommendations` property to suppress this behavior for affected KSP-RO netkans.
Cheers!

Recommendation suppression property for netkans

---

GameData/RP-1/Contracts/X-Plane Research/XPlanesHypersonic.cfg

Currently requires that non-existant program 'Suborbital Rocketplanes' is active

Fix Active Program requirement in XPlanesHypersonic.cfg

---

GameData/RP-1/Contracts/X-Plane Research/XPlanesHypersonicOptional.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesStratosphericResearch.cfg

Fix required/optional tags for new contracts, and reduce hypersonic requirements somewhat--it seems significantly harder than I remember it being to keep an X-15 cockpit intact at 3km/s, possibly a result of it getting the non-reentry-rated tag.

X-Planes tweaks

---

GameData/RP-1/Contracts/X-Plane Research/XPlanesKarman.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesSupersonicOptionalHigh.cfg

...such as maxCompletions in Mach 2+ supersonic contracts, and contract type of the Karman line contract.
Somone might had forgotten that the total amount of speed records in Mach 2+ supersonic contracts had reduced to 6, while it might be helpful to mark the most challenging contract(s) of a program (Karman line in this case) as "Capstone", like the other programs did.

Minor fixes on X-Plane Program

---

Source/Harmony/Contract.cs

Noticed when taking Glushko as admin--standard-difficulty SR at 100% rewards showed as 48 confidence in admin, but provided the correct 50 when actually accepted and completed. It seems that the display was already using base rep. This was tested using Glushko--altitude SR gave increased reputation (11 after rounding) but 50 confidence in the new total, total confidence earned summary, MC contract summary, contract completion message,  and career log.

Fix contract confidence display with leader reputation affects

---

GameData/RP-1/Contracts/Mars/MarsOrbit.cfg
GameData/RP-1/Contracts/Venus/VenusOrbit.cfg

Fix #2044 by removing the requirement to flyby mars or venus for their first orbit contract to show up. Also changed the "check for stable orbit" time in first venus orbit from 120s to 2m (which is what everywhere else is like) for consistency.

Remove flyby requirements for first mars and venus orbit

---

GameData/RP-1/Tree/ECM-Parts.cfg
GameData/RP-1/Tree/EntryCostModifiers.cfg
GameData/RP-1/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Near_Future_Electrical.json
Source/Tech Tree/Parts Browser/data/Universal_Storage_2.json

Configure SNAP-2, SNAP-8, SNAP-50 (300 kWe), and Prometheus from Near Future Electrical. Also adjust reactor ECMs to sane values based on SNAP-50 development costs.

Configure new reactor parts, better reactor ECMs

---

GameData/RP-1/Contracts/Mars/Mars Landing.cfg
GameData/RP-1/Contracts/Mars/Mars LandingRepeat.cfg
GameData/RP-1/Contracts/Mars/Mars RoverRepeat.cfg
GameData/RP-1/Contracts/Mercury Exploration/Mercury Landing.cfg
GameData/RP-1/Contracts/Mercury Exploration/Mercury LandingRepeat.cfg
GameData/RP-1/Contracts/Plutonian Landings/Charon LandingRepeatable.cfg
GameData/RP-1/Contracts/Plutonian Landings/Pluto Landing.cfg
GameData/RP-1/Contracts/Plutonian Landings/Pluto LandingRepeatable.cfg
GameData/RP-1/Contracts/Saturn Observation/Titan Rover.cfg
GameData/RP-1/Contracts/Venus/Venus Landing.cfg
GameData/RP-1/Contracts/Venus/Venus LandingRepeat.cfg
GameData/RP-1/Contracts/Venus/VenusOrbitRepeat.cfg
GameData/RP-1/Programs/Programs.cfg

Based on issue #2288 
- Split Venus landing into Capstone and optional repeatable, added optional to program definition
- Split Mars Landing and Mars Rover into required and optional repeatable, added optionals to program definition
- Split Mercury, Pluto, and Charon Landing into required and optional repeatables, added optionals to program definitions
- Crewed Targeted Moon Landing looks to be intentional.  The program requires 2 completions, and the contract is completable twice.
- Titan Rover was checking for SaturnObservation as the active program, but wasn't listed in the program.  It doesn't make sense there, so changing the check and optional listing to be SaturnMoonLandings.

Interplanetary contract issues

---

GameData/RP-1/Contracts/Early Satellites (Heavy)/FirstBioSat-Heavy.cfg

Transmitting science isn't a contract requirement, so I removed the text for that.  Also, the contract description is a direct copy of the science satellite contract, so it needs editing.

Fix descriptive text in the biological satellite contract parameters.

---

GameData/RP-1/Programs/Programs.cfg

`objectivesPrettyText` for Suborbital Rocket Development incorrectly reads 4500 km instead of 5000 km.

Fix objectivesPrettyText of Suborbital Rocket Development

---

GameData/RP-1/Contracts/Earth Crewed/OrbitalTestFlight.cfg

* OrbitWrapper being sticky
* ReturnHome not working in some (or possibly even most?) cases
Needs https://github.com/KSP-RO/ContractConfigurator/pull/29 and https://github.com/KSP-RO/ContractConfigurator/pull/30

Fix issues with OrbitalTestFlight contract

---

Source/RP0/PartModules/ModuleShowInfo.cs

The `name` field on a `Part` is not always the part name; in particular when creating the tooltip in the editor for a part with upgrades, it is not (it is instead "{partName}(Clone)"). See also https://github.com/KSPModdingLibs/KSPCommunityFixes/pull/177
Also, remove internal names from the info where possible. In particular,
- The part title is already the tooltip title, so it can just be removed;
- The tech now shows the title instead of the internal name;
- The training courses show an "internal" name in the RP-1 training window (they don't have a separate title), so I've left them as-is;
- ECM's don't have an user-facing title, so they're just left as-is.
Fixes an issue where the required crew training course name in the tooltip does not match the course name in the RP-1 training …

Improve information shown in part tooltips and fix training course names

---

Source/RP0/Addons/GameplayTips.cs
Source/RP0/Settings/GameParameters.cs

Easy enough for forget about those.

Add tip about unpurchased RA TLs

---

GameData/RP-1/Contracts/Commercial Applications 1/EarlyComSat-CA.cfg
GameData/RP-1/Contracts/Commercial Applications 1/EarlyMolniyaSat.cfg
GameData/RP-1/Contracts/Commercial Applications 1/EarlyNavSat-CA.cfg
GameData/RP-1/Contracts/Earth Satellites/ComTestSat.cfg
GameData/RP-1/Contracts/Earth Satellites/EarlyComSat.cfg
GameData/RP-1/Contracts/Earth Satellites/GEORepeatComSats.cfg

Remove dissassociateVesselsOnContractCompletion on contracts that also have DestroyVessel on completion.  If the dissasociate happens first, there's nothing to destroy.

Fix vessel transfers

---

GameData/RP-1/Contracts/X-Plane Research/XPlanesHypersonic.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesHypersonicOptional.cfg

The current optional hypersonic flight contracts require speeds of 2300 m/s and 2600 m/s. The 2300 m/s contract is achievable, but only when using the non-inline X-15 cockpit. No parts exist with an aerodynamic shape, or that can be changed into an aerodynamic shape, which can withstand the temperatures encountered at those speeds.
In real life, no X-15 ever flew faster than 2020 m/s (Flight 188). That flight also essentially ruined the aircraft from thermal damage.
Because of this, believe that the differences in speed requirements should be dropped in favour of duration requirements.
I have changed the optional contracts to instead require the player to maintain 2000 m/s for longer, at three minutes for the first contract, and four minutes for the second. These are still difficult …

Rebalance Optional Hypersonic Flight Contracts

---

Source/RP0/Tooling/ModuleToolingPFSide.cs

The new height calculation is also more accurate than previous code.
Depends on https://github.com/KSP-RO/ProceduralFairings/commit/6545fe19e2661e7844bd8072bd222806748716bc

Simplify fairing side tooling/size calculations

---

GameData/RP-1/Tree/PayloadLevels.cfg

EarlyAvionics upgrade for Com and Nav Sat's was missing from the tech tree due to a typo in the field techRequired in PayloadLevels.cfg
Tested this change in my local copy and it fixed the issue.

Fix missing contract Sat upgrade in early avionics node

---

GameData/RP-1/Contracts/Commercial Applications 2/FirstTundraSat.cfg
GameData/RP-1/Contracts/Earth Satellites/FirstTundraSat.cfg

With a 1000 km periapsis (eccentricity 0.82), the resulting orbit has barely any apogee dwell time; it moves west very quickly across the sky when it's at apogee.
At an eccentricity of 0.423, the ground track moves from being a figure-of-eight to a teardrop shape.  Higher eccentricities make the ground track more of an oblong shape. An eccentricity of 0.423 gives a periapsis altitude of 17958 km; I've rounded it down to 17000 km to give a quite lot of margin.
Also decreased the minimum eccentricity a little bit. According to Capderou's "Handbook of Satellite Orbits", a 0.2668 eccentricity Tundra orbit was considered for ESA's "Archimedes" telecommunications project, giving an 8 hour visibility window per orbit. The new minimum of 0.25 is a little below that value.
Examples of Tundra …

Increase Tundra orbit periapsis requirement

---

GameData/RP-1/Strategies/Leaders/LeadersScientists.cfg

I noticed an unused leader icon in the file.
Plan to expand upon it.

Chinese Leader Update.

---

Source/RP0/SpaceCenter/Projects/FacilityUpgradeProject.cs
Source/RP0/Utilities/KCTUtilities.cs

Depends on #2381, https://github.com/KSP-RO/RealAntennas/pull/19

Forcefully reset RA CommNet when upgrading TS

---

Source/Tech Tree/Parts Browser/app.py

This prevents an edge case I encountered where the following occurs:
- The user creates a new part, and forgets to add certain info (in my case, I forgot to check the "RP-1" box), and presses "Queue Changes"
- The user edits that part, and queues those changes
- The user presses "Commit Changes to JSON Files"
- Operation fails, console shows exception:
```
Traceback (most recent call last):
File "flask\app.py", line 2190, in wsgi_app
File "flask\app.py", line 1486, in full_dispatch_request
File "flask\app.py", line 1484, in full_dispatch_request
File "flask\app.py", line 1469, in dispatch_request
File "app.py", line 168, in commit_changes
part_data.add_new_part(part)
File "part_data.py", line 25, in add_new_part
print(f'Adding new part with name: {new_part["name"]}')
~~~~~~~~^^^^^^^^ …
```

Parts Browser: Run queued changes in reverse

---

Source/RP0/SpaceCenter/LaunchComplex/LaunchComplex.cs
Source/RP0/SpaceCenter/Projects/LCOpsProject.cs
Source/RP0/SpaceCenter/Projects/ReconRolloutProject.cs
Source/RP0/SpaceCenter/Projects/VesselRepairProject.cs
Source/RP0/SpaceCenter/SpaceCenterManagement.cs
Source/RP0/UI/KCT/GUI_Editor.cs
Source/RP0/UI/KCT/GUI_NewLC.cs
Source/RP0/UI/MaintenanceGUI.cs
Source/RP0/Utilities/Formula.cs

So reconditioning and LC reconstruction can now happen in parallel. Engineers are no longer needed for reconditioning so there's a fixed time and separate cost for this.

Change pad reconditioning to be independent from other LC operations

---

GameData/RP-1/Contracts/Lunar Surface Probes/MoonLandingFarSide.cfg
GameData/RP-1/Contracts/Lunar Surface Probes/MoonLandingFarSideOptional.cfg
GameData/RP-1/Contracts/Lunar Surface Probes/MoonLandingReturn.cfg

Currently, the reward for the lunar landing optional contracts are 200 reputation each. However, the sample return contract, which is far more difficult, gives the exact same reward, and furthermore the far side landing optional contract gives less of a reward?
I've fixed this problem by scaling the rewards roughly on difficulty. (for reference, Luna 16 (sample return) weighed 5.7t wet, while Luna 13 (lander) weighed 1.6t wet)

Buff reward of far side landing optional and sample return contracts

---

Source/RP0/ModIntegrations/KSCSwitcherInterop.cs
Source/RP0/Properties/AssemblyInfo.cs
Source/RP0/RP0.csproj
Source/RP0/SpaceCenter/LaunchComplex/LCSpaceCenter.cs
Source/RP0/SpaceCenter/SpaceCenterManagement.cs
Source/RP0/Utilities/KCTUtilities.cs

Needs https://github.com/KSP-RO/RealAntennas/pull/25 and https://github.com/KSP-RO/RealSolarSystem/pull/302

Toggle ground station state based on selected launch site

---

.github/workflows/attachReleaseArtifacts.yml
.github/workflows/build.yml
Source/CC_RP0/CC_RP0.csproj
Source/ClearInputLocks/ClearInputLocks.csproj
Source/InstallChecker/RP0InstallChecker.csproj
Source/RP0/RP0.csproj

This PR changes the csproj to use paths relative to `KSPRoot` and also updates the workflows for CI to use CKAN to install dependencies.
Custom dlls can still be provided by adding them to this repo: https://github.com/KSP-RO/BuildLibs
If `KSPRoot` is not set, `ReferencePath` will be used instead. With this behaviour `ReferencePath` can be set to either a folder with all references, or to a KSP install for local development

CI using CKAN

---

GameData/RP-1/Contracts/Mars/Mars Probe.cfg
GameData/RP-1/Contracts/Mars/Mars Rover.cfg
GameData/RP-1/Contracts/Mars/Mars RoverRepeat.cfg

Need to land within 50km of first waypoint and then the next 2 waypoints are generated a short distance from the landing spot.
Needs https://github.com/KSP-RO/ContractConfigurator/pull/47
TODO: other rover contracts

Generate waypoints around landing spot for Mars Rover

---

Source/RP0/Harmony/RealAntennas.cs
Source/RP0/RP0.csproj

Fixes #2408
Soft dependency on https://github.com/KSP-RO/RealAntennas/pull/34

Harmony-patch RA config can afford query to factor in unlock credit

---

Source/RP0/Harmony/Administration.cs
Source/RP0/Programs/Program.cs
Source/RP0/Programs/ProgramHandler.cs
Source/RP0/Programs/ProgramModifier.cs
Source/RP0/Programs/ProgramStrategy.cs
Source/RP0/RP0.csproj

These will change the funding, duration etc values on a program if another gets accepted.

Add support for Program Modifiers

---

GameData/RP-1/Contracts/Lunar Crewed/CrewedMoonLandingTargeted.cfg

Current `Crewed Targeted Moon Landing` requires landing within 1km of target locations, which is very difficult due to in-game limitations, also also does not make sense that the entire mission becomes a failure if you miss the site by just 1km.
The modified version：
- Relax distance requirement 1km -> 10km for completion (updated)
- Bonus science if you land within 3km, which is roughly [how far off Apollo did historically](https://space.stackexchange.com/questions/37488/how-far-off-did-apollo-11-land)
- Total reputation is unchanged (25% moved from base to the optional part)
- Check waypoint distance and landing status concurrently to prevent cheesing it by landing and then fly-by the waypoints
Also fixing some texts along the way.

Make targeted moon landing easier

---

GameData/RP-1/Strategies/Leaders/LeadersSubcontractors.cfg

Players will still have to pick carefully due to only having two subcontractor slots, but this removes the downsides from these less influential leaders, and should hopefully make the capitalist ones more practical. Feedback welcome

Remove downsides from subcontractors, buff research rate modifiers

---

GameData/RP-1/Contracts/Early Satellites (Heavy)/FirstPolarSat-Heavy.cfg

This puts it in line with first biosat and means early satellites heavy can't be completed in one launch anymore

Fix PolarSat Heavy to require FO

---

GameData/RP-1/Strategies/Leaders/LeadersScientists.cfg

Make the scientists that are relevant to the early game unlock a bit sooner. Half the scientists unlock after suborbital return/first bio now, with the rest still going off scisat

Stagger Chief Scientist unlocks

---

GameData/RP-1/Science/Experiments/CrewScience/BasicCapsuleExperiments.cfg
GameData/RP-1/Science/Experiments/CrewScience/MatureCapsuleExperiments.cfg
GameData/RP-1/Science/Experiments/CrewScience/SecondGenExperiments.cfg
GameData/RP-1/Science/Experiments/CrewScience/StationExperiments.cfg

Solves #2416.
Added `BodyAllowed = HomeBody` for experiments with `celestialBodies = Earth`, and added `BodyAllowed = HomeBodyAndMoons` for experiments with `celestialBodies = Earth;Moon`. 
Also trimmed the whitespace.

Enforce body restrictions for crewed experiments

---

GameData/RP-1/Science/Experiments/CrewScience/CockpitExperiments.cfg

As of now, the high-altitude flight experiment awards 9.6 science points. This number seems dubious, since 1) the other three cockpit experiments award integer numbers of science points and 2) the Ma1.5 experiment awards 9 points while being much easier than the high-altitude flight experiment. I suspect this is an oversight, as Earth Flying Low has a body modifier of x1, but Earth Flying High has x0.6. If a person wants to award 16 points for high-altitude flight and naively enters the number in the config, only 9.6 points are awarded. There are at least two instances of a dev forgetting the body modifier: 3e1d9194520bae61f2f58f6482478715305596af (6+10+12+15 = 43, whereas hypersonic flight requires 1+4+4+12 = 21) and 2ad5d1bdb5f0f5c8f5efc6ac695eada3527bf20b (if the dev remembered, he …

Increase High Alt Flight experiment reward to account for body modifier

---

GameData/RP-1/Tree/ECM-Engines.cfg
GameData/RP-1/Tree/ECM-Parts.cfg
GameData/RP-1/Tree/TREE-Engines.cfg
GameData/RP-1/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json
Source/Tech Tree/Parts Browser/data/ROEngines.json
Source/Tech Tree/Parts Browser/data/ROEnginesExtended.json
Source/Tech Tree/Parts Browser/data/Stock__RO_Config.json

Fix the XLR99 configs being incorrectly priced/not existing, and add configs for the AR-2.

Fix XLR99 configs, AR2 configs

---

GameData/RP-1/Contracts/Lunar Surface Probes/MoonOrbiter.cfg
GameData/RP-1/Contracts/Lunar Surface Probes/MoonOrbiterOptional.cfg

First Lunar Orbiter & Mapper (Uncrewed) & the optional mission afterwards, requires you to collect visual imaging 2 (VI2) science from around the moon.  The current contract doesn't require any PE Max, however the biome science has to be collected from space low.  To see why I wasn't collecting the science, I had to reference 3 different materials:
- the contract requirements (to see it was biome specific), 
- the Science window (too see that biome science only comes from low orbit), 
- and the wiki to see where "space low" started
In talks with the dev-feedback channel in discord, someone pointed out that someone else on the discord had to "cheat" their way to completing the contract because they weren't collecting the science, and assumed it's because they were in "space high" since you …

Lunar Orbiter & Mapper PE Max Updates

---

GameData/RP-1/Contracts/RP0_Contract_Resources.cfg

The space stations program PR #2326 accidentally added ComSat, NavSat and WeatherSat payloads back to SM tanks. Putting SoundingPayload into SM tanks is a classic "noob trap"; you should always put it into HP regular tanks, instead. Remove all these payload resources from SM tanks again.

Remove payloads from SM tanks again

---

GameData/RP-1/Contracts/X-Plane Research/RocketPlaneDevelopmentOptional.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesHighAltitude.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesHighAltitudeOptional.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesHypersonic.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesHypersonicOptional.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesKarman.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesStratosphericResearch.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesStratosphericResearchOptional.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesSuborbital.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesSupersonicMach2.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesSupersonicOptionalHigh.cfg
GameData/RP-1/Contracts/X-Plane Research/XPlanesSupersonicOptionalLow.cfg

suggested by Zavian and Quadrupole🇵🇸🇨🇺(https://discord.com/channels/319857228905447436/620690446540341261/1325665658868072630)

Add an "OPTIONAL" tag to the descent angle parameter on x-plane contracts

---

RP-1.netkan

There are a fair amount of other potentially conflicting tech trees on ckan that might be worthwhile to add to conflicts, but community tech tree is the biggest one by far (nearly 1.1 million downloads) and it is recommended by the near future mods, most of which are suggested by RP-1.

Add Community Tech Tree to conflicts

---

GameData/RP-1/Contracts/Earth Crewed Adv/Docking.cfg

~~As per discussion in https://discord.com/channels/319857228905447436/1295137142762242139/1328487821220118682~~
Additionally, add extra reputation/confidence for rendezvousing with a different craft before docking (instead of just re-docking to your upper stage, for example)

Add optional reward to docking contract for rendezvousing with a different craft first

---

GameData/RP-1/Contracts/Skopos Commercial Applications 0/FirstComSat-SCA.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/FirstGEOSat-SCA.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/FirstGeosync-SCA.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/FirstMolniyaSat-SCA.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/FirstTundraSat-SCA.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_paris_moscow_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_soviet_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_transatlantic_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_transpacific_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 3/l3_hermes_remote_tv.cfg

Set the max tracking station level in Skopos contracts to 11, so the contracts aren't accidentally hidden if you happen to start them very late.

Set max tracking station level to 11

---

GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_paris_moscow_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_soviet_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_transatlantic_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_transpacific_tv.cfg
GameData/RP-1/Contracts/Skopos_Contract_Configs.cfg
GameData/RP-1/Programs/Programs.cfg

Due to complaints, limit the duration of the Skopos contracts in the experimental program to 1 year. Also add warnings that Skopos contracts must be maintained forever once accepted.

Limit duration of experimental Skopos contracts, and add warnings

---

GameData/RP-1/Contracts/RP0_Contract_Resources.cfg

Set ResearchPayload cost to 0 to prevent drained tanks having negative cost due to a KSP bug.
Currently, if you designate a tank as a ResearchPayload carrier but fully drain it of payload, its cost can become negative: https://discord.com/channels/319857228905447436/1295137142762242139/1338257875298156566

Change ResearchPayload cost to prevent negative part costs.

---

Source/RP0/SpaceCenter/LaunchComplex/LaunchComplex.cs

When making a new launch complex, RP-1 automatically creates a launch pad with the name of "Launch Complex [number]-A". Not only is this only slightly different from the name of the Launch Complex itself (making it difficult for new players to tell the difference), it is also inconsistent with the default name of new launchpads created for that complex. There is also no real need for the player to be able to tell which launchpads are accessible to which complexes at a glance, as you can only access a launchpad from a certain complex.
For example, without changing the name of anything, here is what happens when you make 3 launch pads for LC-1.
Launch Complex 1: (default names)
Launch Complex 1-A
LaunchPad 2
LaunchPad 3
This PR fixes this inconsistency and fixes …

Change the default name of the first launchpad from "Launch Complex #-A" to "LaunchPad 1"

---

Source/RP0/SpaceCenter/SimulationParams.cs
Source/RP0/SpaceCenter/SpaceCenterManagement.cs
Source/RP0/UI/KCT/GUI_Simulation.cs

Fix https://github.com/KSP-RO/RP-1/issues/2364.
Currently, only inputting Hours:minutes:seconds into the simulation window passes through [TryParseTimeString](https://github.com/KSP-RO/ROUtils/blob/master/Source/ROUtils/Utils/DTUtils.cs#L68) without any failures as expected, but this leads to some problem later down the line where the game starts timewarping rapidly (2364). This PR makes it so if the user is trying to specify a specific time, they must include the YYYY-MM-DD as well to avoid this error. (only putting in YYYY-MM-DD and not the HH:mm:ss is currently fine, as it just sets the time to midnight) All other formats should still work.
Also remind the user that they are allowed to specify seconds in that format, as it can be parsed perfectly fine.
RIP analemma

Fix a timewarp kraken, add MNA and ArgPe to simulation GUI options, and some other various simulation GUI changes

---

Source/Tech Tree/Parts Browser/data/ROCapsules.json

Fix https://github.com/KSP-RO/RP-1/issues/1926
ECM should only be required for parts that are directly linked to the development of another part (like heatshields linked to capsules)

Do not require ECM for some apollo parts

---

Source/RP0/Leaders/StrategyRP0.cs
Source/RP0/Programs/Program.cs

Fix https://github.com/KSP-RO/RP-1/issues/2073
I honestly have no idea if this is set up remotely correctly, as I pretty much just copy and pasted from [here](https://github.com/KSP-RO/RP-1/blob/0a7d57a8038295a2be002089f5aa4b27fe48e456/Source/RP0/UI/TrainingGUI.cs#L425). If this is set up, this should automatically create a KAC alarm that says "Retirement: [leader name]", with the time set to their retirement date. I did not do this for normal astronauts because their retirement dates can move. (leaders' retirement dates can't move, right?)

Add KAC alarm for leader retirement and program deadline

---

GameData/RP-1/Tree/PFTechLevels.cfg

Currently, at 0.155 stringer mass procedural structures are overweight. This PR lowers the first upgrade to 0.135 to match empty Al Stringer parts, and the second upgrade to 0.124 to match the current relative reduction of that upgrade. It also clarifies that procedural structures begin at 0.300, and not 0.180.
Fixes #2512

Lower stringer mass to match empty Al Stringer tankage of the same year

---

GameData/RP-1/Contracts/Skopos Commercial Applications 0/FirstComSat-SCA.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/FirstGEOSat-SCA.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/FirstGeosync-SCA.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/FirstMolniyaSat-SCA.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/FirstTundraSat-SCA.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_paris_moscow_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_soviet_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_transatlantic_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_transpacific_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 3/l3_hermes_remote_tv.cfg

Related: https://github.com/KSP-RO/RP-1/pull/2489
There already exists a spot in RP-1 where this is done with the Astronaut Complex for the First EVA contract, where minLevel is specified but maxLevel is not:
https://github.com/KSP-RO/RP-1/blob/3be415ae90102baaf8a797c43fd488af3829edc8/GameData/RP-1/Contracts/Earth%20Crewed%20Adv/FirstEVA.cfg#L61-L68
The contract configurator code also seems to be correctly set up to handle this situation:
https://github.com/KSP-RO/ContractConfigurator/blob/2d4ee9c189da88dc2edf08fd44b8ec6ac26fec1c/source/ContractConfigurator/Requirement/FacilityRequirement.cs#L63-L65
```requirementmet is true if (((no minlevel) or (level ge minlevel)) and ((no maxlevel) or (level le maxlevel)))```
This should be better for future proofing.

Remove max level requirements on tracking station for skopos contracts

---

Source/CostExporter/CostExporter.csproj

While CostExporter does not need to be built usually, there is no need for its .csproj to lead to a custom Users folder (I think its NK's?) if someone builds it by accident.
Let me know if the output path should be set to something other than \bin\Release\, I just set it to that to get it out of the way. (and so KSP wouldn't try to load its dll if it was built by mistake)

Move CostExporter.csproj export path to \bin\Release\ to prevent unnecessary User folder being made

---

Source/CostExporter/CostExporter.csproj

Well this breaks the github actions and I do _not_ care enough to figure out why

Revert "Move CostExporter.csproj export path to \bin\Release\ to prevent unnecessary User folder being made"

---

RP-1.netkan

According to https://discord.com/channels/319857228905447436/620690446540341261/1345817564428767343, there is a strange issue where selecting community tree with RP-1 (non-express I think) [causes ckan to pick an older version of RP-1 without the community tech tree conflict](https://github.com/KSP-CKAN/CKAN/issues/4325). This PR removes recommendations from near future mods to prevent community tech tree from being suggested, although this is not a solution to the problem.

Add suppress notifications to Near Future mods

---

GameData/RP-1/Tree/RFTechLevels.cfg

Prevent MLI from being used on avionics and other parts with battery-only tanks
resolves https://github.com/KSP-RO/RP-1/issues/2487

No MLI on battery tanks

---

GameData/RP-1/Contracts/Early Satellites (Heavy)/FirstPolarSat-Heavy.cfg

Reported by [Qazerowl](https://discord.com/channels/319857228905447436/620690446540341261/1350515505332486184)
https://github.com/KSP-RO/RP-1/pull/2428 required that users need to have completed the FO heavy contract before accepting this contract, however forgot to remove the requirement later in the contract where it required you to either accept or complete the FO heavy contract. This happens to not change the expected behavior at all, just makes it look weird visually.

Fix double requirement of FO Heavy in polar sat contract

---

GameData/RP-1/Tree/ProceduralAvionics.cfg
Source/RP0/Avionics/ModuleProceduralAvionics.cs
Source/RP0/UI/ProceduralAvionicsWindow.cs

Reported by Krydax (https://discord.com/channels/319857228905447436/845457276641738782/1348458469983916082)
The top value was getting mass from GetShieldedAvionicsMass, while the bottom value was getting mass from GetAvionicsMass.
Actually, what even is 'shielding mass'? It seems to have been added all at once, with no real explanation for what it was, and then never used again. It might even be throwing off GetModuleMass and RefreshDisplays. Would it be safe to [remove all traces of this "shielding mass"](https://github.com/Clayell/RP-1/pull/2)?
Commits where it was added:
https://github.com/KSP-RO/RP-1/commit/a107763f0abe51d1ada9de388c690e3ed1919b2c
https://github.com/KSP-RO/RP-1/commit/08df9c823d79fba93b862f9e6f7ca57ea74bbcbb
Only present in these 3 files: …

Fix disconnect between avionics masses in procedural avionics window

---

Source/RP0/UI/KCT/GUI_Simulation.cs

Principia has some very strong perturbations, and not even the original 20,000 above atmosphere works. Doing +30000 (so, 170km) perturbs us down to 149.9km, so that should work. I've increased the default distance above the ground to +30000 based on the same principles, although TBH if you're using that feature on the moon Principia will wreck your craft decently quickly if you're below 200km anyway, so it's only a bandaid.
Simulating with +30km:

Raise default height above atmosphere/ground in simulation to be 30000

---

Source/RP0/UI/KCT/GUI_Personnel.cs

Fix https://github.com/KSP-RO/RP-1/issues/2547.
Strips any commas from the strings before using them. (ReserveFunds doesn't even need to be stripped since it seems that double.TryParse can handle commas anyway, but there's no harm in doing it)
Additionally, previously only the "reserve funds" error was able to show up, even if the error was within parsing "crew count". This is because the "staff count" error would only show if the staff count had successfully parsed, which doesn't make any sense. I have changed this logic to allow for both error messages to show up at the same time if necessary.

Allow for commas in autohire GUI, allow for both errors to show up simultaneously

---

GameData/RP-1/Strategies/Leaders/LeadersEngineers.cfg

Yangel was supposed to grant -15% from rollout, recovery and integration costs but:
Recovery cost are not an actual thing apparently, recovering costs 0 excluding the staff salary.
It's not clear to me what Integration costs are, i would imagine its the EffectiveCost of the rocket, since you pay for it over time, but no transactionReason affects it. (it would need to affect the engineer's salary only while they are working)
To fix the problem i opted for reducing the purchase cost instead, also maintaining the reduction to rollout cost.
The reasoning is that EC is often more than 2x the purchase cost so instead of 15% less EC it will reduce purchase cost and rollout by 25%.
I also removed a few reduntant commas from some leaders text.
Fixes #2540

Fix Yangel bonus, but for real

---

GameData/RP-1/Programs/Programs.cfg

Just changing the `COMPLETE_CONTRACT` parameters for SIMPLER `complete_contract = _contract_name_` where the `COMPLETE_CONTRACT` parameter isn't actually needed just for readability. An example of where the `COMPLETE_CONTRACT` parameter is needed is when specifying a minCount of contracts needed (Example: RepeatMoonLandingCrew).

Small change on Programs.cfg for better readability

---

GameData/RP-1/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

Since it takes about 3 R-103s to match a Tiny Tim, make them cost a third of a Tiny Tim so they aren't really cheap any more.

Increase R-103 cost

---

Source/RP0/Harmony/Administration.cs
Source/RP0/Leaders/StrategyRP0.cs

Fix https://github.com/KSP-RO/RP-1/issues/2517 (both parts)
CreateAlarm adds a way to make an alarm with a description that defaults to KAC if installed, but otherwise creates a stock alarm. I've made this trigger for:
- Program deadlines
- Leader retirement (although I don't think we use it anymore since https://github.com/KSP-RO/RP-1/pull/2569)
- Leader penalty fee expiration
- Leader reactivation cooldown
- Leader deactivation cooldown
ClearAlarms adds a way to remove all alarms (again accounting for KAC) with a certain string in the title. (to prevent duplicate alarms confusing people)
I've made this trigger when:
- Activating a leader
- Deactivating a leader
- Completing a program (no need to do it when activating the program, since the program can't have been activated before?) …

Add methods related to alarms with and without KAC

---

Source/RP0/UI/KCT/GUI_BuildPlans.cs

When the build plan window is open, the main window from KCT gets it's size set to 1 and back constantly whenever the mouse is button is being pressed.
I believe this line of code is the a remnant of some refactors done some years ago and it never got touched again. I did some local testing in the space center and in the VAB and didn't notice any loss of functionality, hence why i believe it's just left over code. More testing or some explanation would be appreciated though.

Stop flickering of main KCT window when Build Plans Window is open

---

GameData/RP-1/ToolingDefinitions.cfg

Considering conventional tanks are basically never worth it, significantly decrease their tooling costs. Also allow conventional tanks to inherit tooling discounts from isogrid tanks (since previous isogrid tanks could inherit from conventional tanks but not the other way around?)

Cheaper stringer tooling, more inheriting

---

GameData/RP-1/Science/ScienceLabs.cfg

Fixes issue with Kerbalism Planner reporting high EC consumption in Editor because of an unknown "lab" process.
https://discord.com/channels/418222516386004992/418222516386004994/1408348148023300109 
Adding `%MODULE[ModuleScienceConverter]` needs to happen before/above the patch that will look for all parts that have that module so it can replace it. Since it is currently at the bottom, it will add a blank module with no info and I Kerbalism is determining 5,000 Watts to be the max that a "lab" will consume.

Station Science Module (Early) incorrect EC consumption in Kerbalism Planner

---

GameData/RP-1/Tree/ECM-Parts.cfg
GameData/RP-1/Tree/TREE-Parts.cfg
GameData/RP-1/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

Actually configure the 4-vernier LR91 so you can use it in RP-1, remove some very old configs for old deprecated LR91 parts.

Actually configure 4-vernier LR91, remove old configs
