KSP-RO/RP-1

GameData/RP-0/CostHacks.cfg

B9 pWings costing

---

tree.yml

Salyut Stations & Soyuz Ferries Cost and Node Placement

Salyut Stations & Soyuz Ferries

---

tree.yml

Solars from Electronics to Electrics nodes

Cost/Place Skylab & fix Soyuz solar node

---

tree.yml

A bunch of part placings and costings so things look better for anyone
with FASA or SXT installed.

Place even more parts

---

tree.yml

One small step for a Bevo, one giant leap for RP-0

FASA Apollo

---

GameData/RP-0/Resources/ProbeExperiment.cfg
GameData/RP-0/Resources/X-Ray Detection.cfg

Also made ProbeExperiment consistent with this as well. Our sciencehacks
were setting baseValue to scienceCap later on in the MM dance, but we
now make sure that's the case from the get go.
Closes #101

X-Ray now results full science points on first transmit.

---

tree.yml

See individual commit messages for details.

Assorted part fixes from my train journey.

---

tree.yml

Prices aren't too prohibitive, although if TweakScale reduces the cost
of parts when they're scaled down then we might wish to bump them up.
Still sucks less than what we had before. :)

Placed Infernal Robotics parts.

---

tree.yml

ALso some tidying up of comments, etc.

Placement of SCANsat gear and life support equipment.

---

tree.yml

Place moar SAS/RW/CMG modules.

---

tree.yml

Reasoning in tree.cfg changes.
For #117.

Placed RPWS and dmscope, priced later SCANsat equipment

---

GameData/RP-0/ExperimentAdder.cfg
GameData/RP-0/PartHacks.cfg
tree.yml

- Wedge is heavier due to added experiment.
- Increased cost of wedge to cover new equipment.
- Wedge no longer requires 200W to operate.
- ModuleManager is amazing.

Added x-ray detection to the US/DMagic environment wedge.

---

tree.yml

Bobcat's Soviet Engines

---

tree.yml

B9 pWings now cost 0.1

---

GameData/RP-0/RemoteTech.cfg

Closes #124.
Not actually tested because clearly I'm living dangerously today.

Agena Avionics now has 300km omni.

---

tree.yml

Added initial placement and pricing for early R7 hardware from
RaiderNick.
Prices a few of the unpriced Atlas tanks. Will complete this after the
next RO release brings in my Atlas tank changes.

R7 Sputnik 1

---

tree.yml

Takes care of #107, I think. May have some other wings to price, but those also need to be placed, so they'll go elsewhere.

Non p wing pricing

---

tree.yml

These are placed logically for gameplay purposes, because gameplay is
cool. :)

Placed large LS containers, water purifier and splitter.

---

GameData/RP-0/Avionics.cfg

Updated the Proton Avionics to be able to control the craft.

RN Proton + R-7 Avionics

---

tree.yml

Updated Centaur costs

---

GameData/RP-0/Science/Results/CrewReport.cfg

Reports for Saturn and its moons still missing, I can do these later.

CrewReport.cfg

---

GameData/RP-0/KW_Engines.cfg
tree.yml

not too sure about the upgrade costs for the later configs, but everything else should be ok i hope.

Place R-7 main engines from KWRocketry

---

GameData/RP-0/Science/Results/BioSample.cfg
GameData/RP-0/Science/Results/TemperatureScan.cfg

TemperatureScan is complete Mecury - Mars&Moons, some Saturn entries.

TemperatureScan.cfg updated & BioSample.cfg started

---

GameData/RP-0/Contracts/Human Spaceflight/Lunar Orbital 1 Repeat.cfg
GameData/RP-0/Contracts/Human Spaceflight/Lunar Orbital 3 Repeat.cfg

This contract resembles Apollo 8 mission, which was the first manned
flight to moon and made 10 lunar orbits in 20 hours.
For #177.

Add contract for three-person into lunar orbit

---

GameData/RP-0/BobCat_Engines.cfg
tree.yml

this kinda depends on my pull request for RO of course.

Place NK15/15V and AJ26-62

---

tree.yml

Costing the small batteries that no one uses since we all use Proc Parts batteries.  Just want to get rid of the non-ro / no costing title. =D

Battery Costing

---

tree.yml

Price is set to 8, based on smaller crew capacity than Bonny (12 funds).

Added and priced SXTke111 cockpit

---

tree.yml

This integrates RaiderNick's US Probes into RP-0, all parts after 1990 have researched costs.

US Probes Integration

---

GameData/RP-0/Contracts/Human Spaceflight/Orbital 2 Repeat.cfg

Added 2/LEO mission based on Gemini project.

Create Orbital 2 Repeat.cfg

---

GameData/RP-0/Contracts/Human Spaceflight/Orbital 3 Repeat.cfg

Added 3/LEO mission based on Apollo project.

Create Orbital 3 Repeat.cfg

---

GameData/RP-0/Contracts/Human Spaceflight/Orbital 1 Repeat.cfg

Modified 1/LEO to fit with proposed 2/LEO and 3/LEO missions

Update Orbital 1 Repeat.cfg

---

tree.yml

-Added Tantares Soyuz launcher and craft
-Added Vostok launcher and craft
-Added prices to NK-15 and NK-15V (taken from here (RU)
http://goo.gl/BYlQa7)

Tantares update

---

tree.yml

Placing patch

---

tree.yml

AIES Landing Legs + LRDecoupler

---

tree.yml

Barometer 
Thermometer
Orbital perturbation
FASA Gemini MOL
FASA Goo

Science parts - AIES, FASA

---

tree.yml

-decoupler
-radial attachment point
-stationhub
-RTG
-DroneCore
-Ion engine

Stock parts

---

tree.yml

Aestus II
AJ10-190 OME
KVD-1
RD-855
RD-856

Stock engines - costs

---

tree.yml

http://forum.nasaspaceflight.com/index.php?topic=19938.90;wap2

RS-68 cost

---

tree.yml

Adding Remote Tech support plus an RTG
Please note, I have no clue on cost of any of this. I pretty much made up random numbers. 11k cost seemed high to me so lowered the cost a lot.
Edit: It is also showing changes I made because I ran into tab chars when trying to test it. Only changes I did to the engine ones was removing the tab chars

Remote Tech + RTG

---

GameData/RP-0/Tantares_Engines.cfg

Replaced spaces with question marks as MM was giving errors about it

MM syntax fix

---

tree.yml

cost:25M USD
Erik Seedhouse - Lunar Outpost: The Challenges of Establishing a Human Settlement on the Moon http://i.imgur.com/lnqO6om.jpg
entryCost: 1200M USD
http://www.parabolicarc.com/2013/10/07/billion-dollar-j2x-engine-mothballed/

J-2X, RL60 - pricing

---

tree.yml

http://www.lr.tudelft.nl/en/organisation/departments/space-engineering/space-systems-engineering/expertise-areas/space-propulsion/design-of-elements/cost/

AJ10-118K, Vulcain, LE-7A: costs

---

tree.yml

Total cost of Space Shuttle Program: 209 bln USD,  1,5 bln USD per flight (135 flights)
, ,
"The shuttle, which consisted of two “re-manufactureable” solid boosters, an expendable external tank, and a refurbishable orbiter, cost about $1 billion per launch, based only on average annual program costs, and $1.5 billion per launch if development costs were also included, based on a 2011 study."
http://www.thespacereview.com/article/2330/1
135 flights
1bln USD per launch (2011)
1,5 bln USD per launch with development cost included (2011)
209 bln USD total cost
74 bln USD development cost (2011) =  10 360 000k (USD, 1965) - however I think that this number includes cost of the 6 orbiters so: 10 360 000 - 4 x 494 000 = 8 384 000 (USD, 1965)
***
Nasa says it was only 450 mln USD per launch but I …

Component Space Shuttle  - 2 mods: Mike NZ and Dragon01

---

GameData/RP-0/Contracts/Human Spaceflight/Orbital 2 Repeat.cfg

Updates to take advantage of CC1.7.7 fixes

Update Orbital 2 Repeat.cfg

---

GameData/RP-0/Contracts/Human Spaceflight/Orbital 3 Repeat.cfg

Updates to take advantage of CC1.7.7 fixes

Update Orbital 3 Repeat.cfg

---

GameData/RP-0/Contracts/Human Spaceflight/Lunar Orbital 1 Repeat.cfg

Updates to take advantage of CC1.7.7 fixes

Update Lunar Orbital 1 Repeat.cfg

---

GameData/RP-0/Contracts/Human Spaceflight/Lunar Landing 1 Repeat.cfg

Manned lunar landing contract with random duration and location requirements.  I've only had a short time to test this but so far I have not encountered any issues with it.

Create Lunar Landing 1 Repeat.cfg

---

tree.yml

Cost is similar to other comparable engines (AJ-110K), I didn't find any useful data but I think we should put these numbers until someone will find actual costs (which will probably never happen).

Aestus, Aestus II

---

tree.yml

https://github.com/KSP-RO/RealismOverhaul/pull/654/files

AIES solar panels

---

GameData/RP-0/EntryCostModifiers.cfg

https://github.com/KSP-RO/RP-0/pull/325/files
https://github.com/KSP-RO/RP-0/pull/254/files

RS-25 entryCostModifiers

---

GameData/RP-0/EntryCostModifiers.cfg

https://github.com/KSP-RO/RP-0/pull/254/files

RS68 entryCostModifiers

---

tree.yml

With the numbers above and about 80% refund after landing you should get 1bln (USD 2011) per flight  = 130-140 mln (USD 1965)

Space Shuttle - pricing

---

tree.yml

lander legs, Gemini engine for landers, srb, ICBM parts

FASA update

---

tree.yml

Could someone tell me where to place these parts?  Same for the 6.25 Heatshield. Temporarily added to orphans node.

HIAD, Falcon gear

---

tree.yml

RO support:
https://github.com/KSP-RO/RealismOverhaul/pull/668/files

bahaMk2LightningCockpit

---

tree.yml

https://github.com/KSP-RO/RP-0/pull/316/files
https://github.com/KSP-RO/RP-0/pull/327

RL10 from Chaka

---

GameData/RP-0/EntryCostModifiers.cfg

https://github.com/KSP-RO/RP-0/pull/317/files
https://github.com/KSP-RO/RP-0/pull/316/files

Chaka RL10 - entryCostModifiers

---

tree.yml

http://space.stackexchange.com/questions/4388/what-are-the-costs-of-the-various-different-engines-in-current-use

Merlin engines -  cost

---

tree.yml

RO-support:
https://github.com/KSP-RO/RealismOverhaul/pull/566
https://github.com/KSP-RO/RealismOverhaul/pull/563

Ju-87, B-52, B-737, Concorde - cockpits

---

tree.yml

https://github.com/KSP-RO/RP-0/pull/348

stock Merlin - pricing

---

GameData/RP-0/Squad_engines.cfg

https://github.com/KSP-RO/RP-0/pull/347

stock Merlin - engine configs

---

tree.yml

-solar panels removed from orphans because they are already placed an costed
-decouplers placed
-2m nose cone placed ad costed
-command pods

AIES - update

---

GameData/RP-0/EntryCostModifiers.cfg

https://github.com/KSP-RO/RP-0/pull/323

Gemini - entryCostModifiers

---

tree.yml

https://github.com/KSP-RO/RP-0/issues/237

Mk2 system - pricing

---

tree.yml

https://github.com/KSP-RO/RP-0/issues/237

RO-Mk1 system pricing

---

tree.yml

https://github.com/KSP-RO/RP-0/issues/237

Mk3 system - pricing

---

tree.yml

They shouldn't be cheaper than RAPIER so I increased their cost.

Sabre engines - cost revision

---

tree.yml

I've found some smaller numbers for Space Shuttle.
http://www.nasa.gov/centers/kennedy/about/information/shuttle_faq.html
http://www.astronautix.com/articles/costhing.htm

Space Shuttle - cost revision

---

tree.yml

https://github.com/KSP-RO/RealismOverhaul/pull/667

Adjustable Landing Gear - revision

---

GameData/RP-0/Avionics.cfg

-stock mk1, mk2, mk3
-B9
-FASA
-AIES
-DragonV2
-Orion
-Space Shuttle

Avionics for many new parts

---

tree.yml

based on the AJE config for Squad jets:
https://github.com/camlost2/AJE/blob/solver_redo/GameData/AJE/Squad.cfg

New 1.0.5  jet engines - P&P

---

tree.yml

Only placements, no clue about prices. I thought salyut/soyuz left and right solar panels shouldn't have seperate development costs, so changed that. Also placed proton interstage adapters and soyuz astp.

placement of some rn parts & fix typo

---

tree.yml

based on : https://camo.githubusercontent.com/7f7959e9a74bd0bd2e269a06d98a690770529d10/687474703a2f2f692e696d6775722e636f6d2f6b79746c704e502e706e67
RO support:
https://github.com/KSP-RO/RealismOverhaul/pull/684/files

NearFutureSolar panels - P&P

---

GameData/RP-0/CTTChanges.cfg

I think that docking ports are really important so we should have them before tech tree overhaul ( which will probably take a while)
Everything is based on Niemand303 proposition: https://camo.githubusercontent.com/7f7959e9a74bd0bd2e269a06d98a690770529d10/687474703a2f2f692e696d6775722e636f6d2f6b79746c704e502e706e67
Think about it as a temporary solution until we get tech tree overhaul.

Avionics TL4, 5, 6, 7 nodes

---

tree.yml

https://github.com/KSP-RO/RP-0/issues/388
@stratochief66
- J-2 moved  to hydrolox TL3
- S-IB stage moved to Mature Orbital
- P&P for S-IB fins

FASA changes

---

tree.yml

some Ven parts that haven't been RO'd or RP-0'd yet.
A few SXT as well

Adding Orphans

---

tree.yml

First stage (FASAGeminiLFTLong) same as proc price, 187
Second stage (FASAGeminiLFTMed) proc price + avionics @ ~1.5 per ton of control, 250

P&P FASA Titan II tanks

---

GameData/RP-0/Avionics.cfg

forgot this the first time 'round, sorry.

Surveyor-grade avionics for the HECSII

---

tree.yml

Implement #407
Moving the placement of FASA Nova elements from Advanced Construction to Specialized Construction.

FASA Nova move

---

GameData/RP-0/FASA_Engines.cfg
GameData/RP-0/KW_Engines.cfg
GameData/RP-0/Squad_engines.cfg

there will be a RO PR to go with this soon
Don't Merge yet, needs checking/testing.

Migrate RL10 Configs to RP-0

---

GameData/RP-0/CryoEngines_Engines.cfg
tree.yml

Something seems wrong with the RL10B-2 pricing, either it's me or it's the pricing of XXxAres1J2-XHIGH, where does the 3500 figure come from?

Place and price Cryoengines mod

---

GameData/RP-0/Avionics.cfg

These are the avionics adjustments discussed in issue #417.  The changes include:
1- Modify the avionics for the Centaur D3 & D5 to reflect the integrated avionics on those two vehicles.
2- Added avionics for the new FASA Atlas II tank.
3- Added avionics for all five of the new FASA Thor/Delta avionics parts.

Update Avionics for issue #417

---

GameData/RP-0/FASA_Engines.cfg

These are tech node placement changes as discussed in issue #417.

Update FASA_Engines for issue #417

---

GameData/RP-0/Science/Results/CrewReport.cfg

I added some more answers for the crew reports and fixed a typo or two.

Added more results for CrewReport.cfg

---

GameData/RP-0/Science/Results/Pressure.cfg

Just more results, mainly for Earth, Venus, Mercury and Mars.

Added more science results for Pressure.cfg

---

GameData/RP-0/Filter_Extensions_Configs/non_wip_RP0.cfg
GameData/RP-0/NonRP0.cfg

* Add "WIP" and "NON" RP-0 categories for FilterExtensions.
* Remove patch for a non - existent VSR engine.

RP-0 Filter Extensions

---

GameData/RP-0/Avionics.cfg

* Second part of the PR #815 from RealismOverhaul.

Vanguard probe science core

---

GameData/RP-0/Avionics.cfg

Slight increase to allow the avionics part designed for the LTTAT to function on the Delta 0900 rocket.

Delta LTTAT avionics upgrade

---

GameData/RP-0/Avionics.cfg

https://github.com/KSP-RO/RP-0/issues/433

roverBody - avionics

---

tree.yml

* Place and price the OLDD Saturn V parts. Covers PR https://github.com/KSP-RO/RealismOverhaul/pull/758
Most of the parts are costed directly from FASA so they should be OK.

OLDD Saturn V tech

---

GameData/RP-0/Avionics.cfg

Setup avionics for the Skylab TRS module

Skylab TRS

---

tree.yml

I've accidentally put the same name to various parts.
https://github.com/KSP-RO/RealismOverhaul/pull/965

Adjustable Landing Gear

---

tree.yml

https://github.com/KSP-RO/RealismOverhaul/pull/981

VSR habitat

---

tree.yml

https://github.com/KSP-RO/RealismOverhaul/pull/983

SXT science nose cone

---

tree.yml

https://github.com/KSP-RO/RealismOverhaul/pull/988

B9 Aerospace update - new parts

---

tree.yml

https://github.com/KSP-RO/RealismOverhaul/pull/989/files

VSR cargobays

---

GameData/RP-0/EntryCostModifiers.cfg

https://github.com/KSP-RO/RP-0/pull/464

NERVA - entry cost

---

tree.yml

Most of these parts should be placed in much later nodes because they are from 1980+ era.

AIES command pods

---

GameData/RP-0/Avionics.cfg

Not sure why it was deleted.
https://github.com/KSP-RO/RP-0/issues/433
https://github.com/KSP-RO/RP-0/pull/434/files

roverBody avionics

---

tree.yml

See [RO configs](https://github.com/KSP-RO/RealismOverhaul/pull/1026) for these two NTR.

Placed and Priced STX NTR

---

tree.yml

These probe cores are the same as probeCoreCube above which costs 15000.

AIES parts  - cost revision

---

GameData/RP-0/EntryCostModifiers.cfg
tree.yml

[RO Reference](https://github.com/KSP-RO/RealismOverhaul/pull/1048)
@NathanKell it is ok this time with the `entryCostSubstractors` ?

SXT Airbags

---

tree.yml

-Massive WIP to fix my parts and add new ones
-DO NOT MERGE

RN part update/fixes

---

tree.yml

Moved the larger diameter LEO rated shields into the survivability node along with the smaller ones.  Also did a bit of a balance pass on prices.

Moved larger LEO rated heat shields into survivability

---

tree.yml

A pruned part was being placed in the tree.

Swap around Tantares_Habitation_A and Tantares_Orbital_A

---

GameData/RP-0/Science/Results/CrewReport.cfg

Added crew reports, including some from spreadsheets and google docs survey.

Added more crew reports

---

RP-0.netkan

Asteroid Day has been merged into KSP as of v1.1.0

Remove Asteroid Day from dependencies

---

GameData/RP-0/EntryCostModifiers.cfg
tree.yml

Support for my Forgotten Real Engines pack.

FRE Viking Engines support

---

tree.yml

I don't know if they are in the best node, move them around if needed. Also one KSP fund = how much euros/dollars? I have something like one KSP fund = $4000, I don't know if it's accurate (calculated from F-1 price). Since they are advanced SRBs, maybe they should be later in the tech tree. @stratochief66  or @NathanKell any idea about this?

FRE Vega engines support

---

tree.yml

Support LE-5 (FRE)

---

tree.yml

Added costs for misc aerospace parts and small tanks

Update tree.yml - misc wip-noncost costs

---

tree.yml

The LE-7 engine is almost ready and will come with the latest FRE update, probably later today.
I will also include pricing by config.

Support for FRE LE-7

---

GameData/RP-0/EntryCostModifiers.cfg

Includes SSTU parts placed in #525

Entry costs for duplicate RD-107, RD-108, RD-0105/0109, and RD-0110

---

tree.yml

* Add RP-0 support for the Octocore, the radial LS tanks and the recyclers.
* Fix incorrect part names.

RP-0 Universal Storage updates/fixes

---

GameData/RP-0/EntryCostModifiers.cfg
tree.yml

Merlin 1B/1Bvac (slighly less expensive than 1C) and XLR81 (part in developpment)

SSTU Merlin engines

---

tree.yml

-First pass engine adds for RN engines based on existing values for identical parts

RN engines adds

---

tree.yml

Place and price 2 SSTU premade engine clusters
place Soyuz lunar heatshield with similar shields

place and price 2 SSTU premade engine clusters, Soyuz shield

---

GameData/RP-0/EntryCostModifiers.cfg
tree.yml

I know these engines names are ridiculous

support FRE FRE-1 and FRE-2 engines

---

tree.yml

* Place and price the Real Scale Boosters engines.

RP0 RSB Updates

---

tree.yml

-Add lr-87 and lr-91 engines
-Add all 3 ua boosters

RN engines add more

---

tree.yml

Reduced price of the nuclear warhead to 1 fund. Useless part shouldn't stand in the way of just purchasing all parts in the node.

nuclear warhead, cost reduced to 1 

---

tree.yml

I'm interested in suggestions for the costs on the C and D engines, since I don't have a good reference point.

Add LLV_* engines and decouplers.

---

tree.yml

* Place and price the AJ-60A SRM and the RD-180 engine from the BahamutoD Atlas V pack.

BahamutoD Atlas V parts P&P

---

tree.yml

Change log:
* Add RP-0 support for the [K2 Command Pod](http://forum.kerbalspaceprogram.com/index.php?showtopic=155013) (Gemini style).

K2 Command Pod RP-0 support

---

tree.yml

-add solar panels pack configs

RN add solar panels

---

tree.yml

* Place and price the RO Castor 4 and Star 37 SRMs.

RO Castor IV & Star 37 P&P

---

GameData/RP-0/Science/Experiments/AtmosphereAnalysis.cfg
GameData/RP-0/Science/Experiments/BioSample.cfg
GameData/RP-0/Science/Experiments/CrewReport.cfg
GameData/RP-0/Science/Experiments/EVAReport.cfg
GameData/RP-0/Science/Experiments/FilmReturn.cfg
GameData/RP-0/Science/Experiments/Geiger.cfg
GameData/RP-0/Science/Experiments/Micrometeorite.cfg
GameData/RP-0/Science/Experiments/OrbitalPerturb.cfg
GameData/RP-0/Science/Experiments/Pressure.cfg
GameData/RP-0/Science/Experiments/SCANSat.cfg
GameData/RP-0/Science/Experiments/StationScienceEarly.cfg
GameData/RP-0/Science/Experiments/SurfaceSample.cfg
GameData/RP-0/Science/Experiments/TelemetryAnalysis.cfg
GameData/RP-0/Science/Experiments/Temperature.cfg

* Add cooldowns for the experiments (cannot be rerun immediately) and
"is shielded" checks.
* Remove some trailing spaces.
[Alternate diff (ignoring whitespace changes).](https://github.com/KSP-RO/RP-0/compare/master...PhineasFreak:RP0-Experiments-Cooldown-Shielding?w=1)

Experiment cooldown & shielding

---

GameData/RP-0/Contracts/Satellite/WeatherContracts.cfg

Fix for multiple weather satellite contracts completed after first satellite insertion #591 
Polish required ElectricCharge Amount
Increase rewards to match current (stock) satellite rewards (30k per satellite approximatively)
Can be reverted if that's too much

Fix for issue #591 - Weather Satellite Contract Completes After One Launch

---

GameData/RP-0/Avionics.cfg
tree.yml

- Add avionics to the new RO Centaur avionics ring.

Stock Centaur avionics

---

tree.yml

P&P 120inch FASA aerocone

---

GameData/RP-0/Filter_Extensions_Configs/non_wip_RP0.cfg

Change log:
* Update the list numbering of the RP-0 custom categories.
* Remove trailing spaces.

Update the RP-0 FilterExtensions patch

---

tree.yml

Goes with this https://github.com/KSP-RO/RealismOverhaul/pull/1350

Place/price SSTU XLR81s and SuperDraco

---

GameData/RP-0/Avionics.cfg
tree.yml

Have the Atlas SLV3C/D tank appear a bit sooner.

Atlas SLV-3C placement

---

RP-0.netkan

Revert "Update netkan" - sorry @Olympic1

---

GameData/RP-0/Contracts/Landings/Deimos Landing.cfg

It is possible to land on Deimos. (I did.) It's just difficult to stay there.

Create Deimos Landing.cfg

---

GameData/RP-0/Contracts/Milestones/Suborbital Return.cfg

Contract description said to fly about the Karman line, but the actual requirement is to fly out of the atmosphere.

Update description of suborbital return contract

---

GameData/RP-0/Tree/RP0TechTree.cfg

fix lost of capital RL and H inicon references

---

GameData/RP-0/Science/Results/CrewReport.cfg
GameData/RP-0/Science/Results/FilmReturn.cfg
GameData/RP-0/Science/Results/SurfaceSample.cfg
GameData/RP-0/Science/Results/TemperatureScan.cfg

Signed-off-by: Michael Casadevall <mcasadevall@ubuntu.com>

First attempt at adding science defs

---

GameData/RP-0/Contracts/Sounding Rockets/SoundingLow.cfg

Lowering Sounding Low's limit to having reached Karman before

Setting Sounding Low's limit

---

GameData/RP-0/Tree/ProceduralAvionics.cfg

Fixed only the early eras, post-war and sattelite era

Adjust Proc. Avionics to keep with non-procedurals

---

Source/Crew/CrewHandler.cs
Source/Maintenance/MaintenanceWindow.cs

Since there's not a lot else on the Astronauts tab, add a scroll list with the
retirement NET dates.

Astronaut list in the UI

---

GameData/RP-0/Contracts/Sounding Rockets/SoundingAltitude.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingDifficult.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingEasy.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingIntermediate.cfg

Increased sounding rocket payouts due to the new tank tuning
Increased tech scaling so payouts decline as tech improves more

Adjusting sounding rocket costs

---

GameData/RP-0/Science/CleanupParts/RemoveScienceParts.cfg
GameData/RP-0/Science/CrewScience/CrewLabAdder.cfg
GameData/RP-0/Science/CrewScience/Experiments/BasicCapsuleExperiments.cfg
GameData/RP-0/Science/CrewScience/Experiments/CrewObservations-BONUS.cfg
GameData/RP-0/Science/CrewScience/Experiments/EmptyExperiment.cfg
GameData/RP-0/Science/CrewScience/LabConfigs.cfg
GameData/RP-0/Science/Experiments/CrewReport.cfg
GameData/RP-0/Science/Experiments/EVAReport.cfg
GameData/RP-0/Science/Results/CrewReport.cfg
GameData/RP-0/Science/Results/ResultClearer.cfg
Notes/Science/WildBlue Lab Format.cfg

First set of Basic Capsules Crew Science

Crew Science Merge

---

Source/UI/UIHolder.cs

UI still provides useful info in sandbox mode, such as whether a vessel
has sufficient avionics

Allow RP-0 UI in Sandbox

---

Source/Crew/CrewHandler.cs
Source/Maintenance/MaintenanceGUI.cs
Source/Maintenance/MaintenanceHandler.cs
Source/UI/TopWindow.cs
Source/UI/UIHolder.cs

This one should actually work.
Haven't added the .dll recompile because it'll cause merge conflicts if another .dll PR is merged first.

Allow ui in sandbox

---

Source/Crew/FSGUI.cs

Basically required for sandbox/science/late career games, where there
are so many parts for which courses can be taken that the list is
several screens tall
Haven't added the recompiled .dll to avoid merge conflicts if other PRs are merged first.

Put course list into a ScrollView

---

GameData/RP-0/KCT_Presets/RP0_KCTPresets.cfg
GameData/RP-0/Tree/TREE-Parts.cfg

Work towards Issue #771.  However, there are some TODOs, mainly for mods that I don't have.
(Also added Reentry tag to a Vostok & Voskhod pod that were missing them.)

Implement multiplier fixes for (some) crew pods

---

GameData/RP-0/Contracts/Early Satellites/Early CommNet (4 Sat).cfg

reduce reward from 900000 to 90000

Update Early CommNet (4 Sat).cfg

---

GameData/RP-0/Filter_Extensions_Configs/non_wip_RP0.cfg

**Change log:**
* Update the MM patch for compatibility with the new FilterExtensions releases.

[Bugfix] Update the RP-0 FilterExtensions patch

---

GameData/RP-0/Contracts/Advanced Satellites/IridiumNEXT.cfg
GameData/RP-0/Contracts/Surface Outposts/MarsOutpost.cfg
GameData/RP-0/Contracts/Surface Outposts/MarsOutpostWithLab.cfg
GameData/RP-0/Contracts/Surface Outposts/MoonOutpost.cfg
GameData/RP-0/Contracts/Surface Outposts/MoonOutpostWithLab.cfg

I accidentally merged to the wrong branch. Rusty mistake!

Move Contracts into Dev

---

GameData/RP-0/CrewTrainingTimes.cfg

Also added SSTU lander cans to the Lander training.

Add Orion Capsule to crew training

---

Source/Tooling/ToolingGUI.cs

Name sort of suggested by schnobs on #RO.
General layout was copied from some other dialog, but I don't remember
from which one, unfortunately

Add "just tool it all fer crissakes" button

---

Source/Avionics/ModuleProceduralAvionics.cs

Fix proc avionics getting stuck in an update loop because of a weird issue with float field control

Fix procedural avionics getting stuck in an infinite update loop

---

GameData/RP-0/Contracts/Moon Exploration/Lunar Rover.cfg

maxCompletions was bumped up from 2 to 3 a while ago, but description still claimed 2. A nice surprise, but accuracy is better.

Tell the player Lunar Rover can be done 3 times

---

Source/Maintenance/MaintenanceHandler.cs

Continuation of PR #957 
Changed the facility level upgrade costs to be loaded only once. Previously this data was discarded and reloaded on each scene change. Facility upgrade data is unavailable when focusing on a vessel that is outside the HomeWorld's SOI so the best place to load the costs would be the space center scene.

Fix incorrect facility maintenance costs

---

GameData/RP-0/PluginData/LoadingScreenTips.txt
Source/LoadingScreenChanger.cs

Tips shouldn't get much longer than the examples in LoadingScreenTips.txt

Added custom tips to loading screen

---

Source/Tooling/ToolingGUI.cs

not just the untooled extra cost.
Also fix the all tooled cost display.

Fix untooled cost to display total untooled cost

---

GameData/RP-0/Parts/Science/MS01-IonMassSpectrometer.cfg
GameData/RP-0/Science/CleanupParts/PartExperimentAdder.cfg

* Also removes the mass of the experiments from each probe.
* Changed the IonMassSpectrometer to be transmittable, as the parts in probes were.

Removes experiments from all probes

---

GameData/RP-0/Contracts/Human Milestones/Karman Line Crew.cfg

fix typo:
completedMessage = Congratulations! The first person as officially reached space!
becomes
completedMessage = Congratulations! The first person has officially reached space!

Karman Line Crew.cfg - 'as' -> 'has'

---

GameData/RP-0/Science/CleanupParts/PartExperimentAdder.cfg

I based it by era, using the Pioneer 6-9 as divider, as those were very focused in cosmic ray science and had several experiments on that.

Divide the probes with cosmic radiation experiments into level 1 and 2

---

GameData/RP-0/Contracts/Landings/Asteroid Landing.cfg

From the rest of the changes made, it looks like this should be a float.

Update Asteroid Landing rewardScience

---

GameData/RP-0/Contracts/Early Satellites/Molniya Satellite.cfg

fix first Molniya contract inclination

---

GameData/RP-0/Parts/SSTUToolingDecoupler.cfg
GameData/RP-0/ProcCosts.cfg

And made it's mass and cost similar to ProceduralParts' decoupler

Added tooling to SSTU procedural decoupler 

---

GameData/RP-0/Tree/EntryCostModifiers.cfg
GameData/RP-0/Tree/ProceduralAvionics.cfg

The way I implemented it before does not work. Now they are a separate procedural avionics config.
I won't be able to test until Sunday though. If anyone wants to give it a try, please do.

Fix the deep space upper avionics

---

Source/ModuleTag/EngineSolid.cs
Source/ModuleTag/HumanRated.cs
Source/ModuleTag/Reentry.cs
Source/ModuleTag/TankBalloon.cs
Source/ModuleTag/TankServiceModule.cs

ModuleTagEngineSolid 1->1.05
ModuleTagHumanRated 1.5->1.25
ModuleTagReentry 2-> 1.5
ModuleTagTankBalloon 2->2.5
ModuleTagTankServiceModule 2.5->2

Update ModuleTag *.cs as per RP1_KCT_Master.cfg

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
GameData/RP-0/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json
Source/Tech Tree/Parts Browser/data/SXT.json

Added to ROEngines in https://github.com/KSP-RO/ROEngines/pull/12

Configure RO Engines Gamma 2

---

README.md

exponential is b^x, x^2 is polynomial

Minor error in mathematical terminology

---

Source/Crew/CrewHandler.cs

Fixed typo.

---

Source/Properties/AssemblyInfo.cs

Declare dependency on RealFuels

---

GameData/RP-0/Contracts/Advanced Satellites/Earth Imaging Satellites.cfg
GameData/RP-0/Contracts/Weather Sats/Early Weather Sats.cfg
GameData/RP-0/Contracts/Weather Sats/First Weather Sat.cfg
GameData/RP-0/Contracts/Weather Sats/Second Gen Weather Sats.cfg

fixed typo in contracts, 'achieve'

---

Source/Crew/CrewHandler.cs

Changed the event we bind to when recovering a vessel, and changed our logic to compute how long of a mission was flown.
This fixes #937

Pilot recovery fix

---

Source/Avionics/ControlLocker.cs

Added control locking for MechJeb

Added control locking for MechJeb

---

GameData/RP-0/CrewTrainingTimes.cfg

Missing Crew training for ROC-Mercury added

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Engines.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
GameData/RP-0/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

Add ROEngines Agenas to part browser

---

Source/Tech Tree/Parts Browser/app.py
Source/Tech Tree/Parts Browser/ecm_data.py
Source/Tech Tree/Parts Browser/part_data.py
Source/Tech Tree/Parts Browser/templates/browser/dashboard.html

Loosely equivalent to restarting 'app.py'
Main use case: pick up filesystem changes to json files coming
from a git pull, git checkout, etc.

Add 'reload from disk' to part browser

---

GameData/RP-0/Contracts/Space Stations/First Space Station.cfg

Changed the required crew from 4 to 3 so it can be completed with Salyut 1, the actual first space station.

Contract: First Space Station

---

Source/CC_RP0/AvionicsCheckFactory.cs
Source/CC_RP0/AvionicsCheckVesselParam.cs
Source/CC_RP0/CC_RP0.csproj

Add AvionicsCheck parameter round two

---

GameData/RP-0/Tree/ProceduralAvionics.cfg

Show information about avionics upgrades in the tech tree description

---

GameData/RP-0/Parts/ProcFairingFix.cfg
GameData/RP-0/Parts/RFProcTanks.cfg

same as #1215, but also adds `TechHidden = True`

Hide deprecated parts from the editor and tech tree

---

GameData/RP-0/Avionics.cfg
GameData/RP-0/Tree/ProceduralAvionics.cfg

A (hopefully) resonable set of configs, to replace the current global fallback from RO.

Added kOS configs for avionics parts

---

GameData/RP-0/Tree/ECM-Engines.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json

matching all/most other start-of-career parts

Lower ORM-65 entry cost to 1

---

GameData/RP-0/Avionics.cfg

Adds avionics control to RealScaleBoosters and KK's SpaceX mods

RSB + KK SpaceX pack avionics support

---

GameData/RP-0/Contracts/Milestones/Orbital Recovery.cfg

Increase the required parameters for completion based on discussions in discord thread. Fist completion is unchanged, second requires a "typical" crewed orbit (set to min paerigee of 200km) to test in actual situation after diong initial test. Thrid requires a 1000km apogee to test higher safety margins

Update Orbital Recovery.cfg

---

GameData/RP-0/Tree/ProceduralAvionics.cfg

Fixed upgrade process breaking kOS disk space and causing increased mass.
Tweaked early progression to be a bit more useful.

Fixed kOS upgrades adding mass

---

Source/CareerLog/CareerLog.cs
Source/CareerLog/CareerLogDto.cs
Source/CareerLog/CareerLogGUI.cs
Source/RP0.csproj

* added the export buttton with the users identifier for access via the webpage
* added required dependancies to .csproj
* added logic for payload creation and export
@siimav if it's all fine - own branch if possible like last time I tried to PR this.

Webexport for analytics testing

---

GameData/RP-0/Contracts/Orbits/Ceres Orbit.cfg
GameData/RP-0/Contracts/Orbits/Ceres Orbit_Rep.cfg
GameData/RP-0/Contracts/Orbits/Vesta Orbit.cfg
GameData/RP-0/Contracts/Orbits/Vesta Orbit_Rep.cfg

Pretty much it. The contracts follow the general pattern for both the first orbit contracts and repeatables.

Add orbit contracts to Ceres and Vesta

---

Source/Tech Tree/Parts Browser/data/Engine_Config.json
Source/Tech Tree/Parts Browser/data/ROEngines.json
Source/Tech Tree/Parts Browser/data/RealEngines.json

Add ECMs and tech nodes for this PR: https://github.com/KSP-RO/ROEngines/pull/76

ROEngines RE stuff

---

GameData/RP-0/Avionics.cfg

Added 4.0 T avionics to ROC Big G Crew Module and 30.0 T avionics to ROC Big G SM.

Add Avionics to Big G Crew Module and Big G SM

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
GameData/RP-0/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

Add ROE HG-3

---

GameData/RP-0/Contracts/Early Satellites/Early CommNet (3 Sat).cfg
GameData/RP-0/Contracts/Early Satellites/Early CommNet (4 Sat).cfg
GameData/RP-0/Contracts/Nav Sats/Early Nav Sats.cfg

per discord conversation:
- Make Early Nav Sats get destroyed on completion
- Gate Early Comm Network behind Comm Test Sats

Sat contract tweaks

---

Source/Crew/CrewHandler.cs
Source/KerbalConstructionTime/Utilities/Utilities.cs

- Fix a NRE that could appear when building vessels from the build plan, outside the editor
- (untested) Fix courses appearing for experimental parts
-  Fix "unlock all parts and build vessel" button not working

Fix various issues with experimental parts

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

Add configuration for the GATV fairing from ROCapsules.

GATV Fairing

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

LEO shield was moved, lunar was forgotten?

Move BigG lunar shield to shield r&d node

---

GameData/RP-0/Contracts/Milestones/Orbital Recovery.cfg

Fix typo in contract description for orbital return (moderate, extreme)

---

GameData/RP-0/Contracts/Human Exploration/Phobos Landing Crew.cfg

Fixes a typo in Phobos Landing Crew.cfg

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
GameData/RP-0/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

Separate ROC Apollo HS from the Apollo capsules

Separate ROC Apollo HS

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
GameData/RP-0/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

Merlin 1C was given 1D's stats and vice-versa

Unswap ROE Merlin 1C/D configs

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/RP0TechTree.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

It should also depend on NF MatSci, like other NF nodes
Also: change Raptor Vacuum's ECM to one that actually works

Fix NF Staged Combustion prereqs

---

GameData/RP-0/Parts/SampleReturnCapsule/RP0SampleReturnCommand.cfg

Now orienting retrograde is possible without Smart A.S.S.

Add ModuleSAS level 1

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Near_Future_Electrical.json

Configure TOPAZ-I, TOPAZ-II and BES-5.

Add TOPAZ-I and BES-5

---

GameData/RP-0/Contracts/Weather Sats/Geostationary Weather Sat.cfg

Adds a title to the Waypoint in 'GEO Weather sat' contract displaying target longitude.

Add Waypoint Title to GEO Weather sat contract

---

README.md

Remove KCT Mod Requirement in README.md since it is now built in RP-1.

Remove KCT Requirement in README

---

GameData/RP-0/TestFlightInterop.cfg
GameData/RP-0/TestFlightRnD.cfg

These config updates are needed for when Test Flight v2 is released or else it won't work anymore.

Updates for TF v2

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ReStock_Plus.json
Source/Tech Tree/Parts Browser/data/Stock__RO_Config.json

3 restockplus antennas and one stock that have RO and RA configs
but were left out of RP-1
Placement and costs set to match "equivalent" parts already configured

More antennas

---

GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Realism_Overhaul.json

See also: https://github.com/KSP-RO/RealismOverhaul/pull/2454

Add small radial sep motor to tree

---

GameData/RP-0/Parts/SampleReturnCapsule/RP0SampleReturnCommand.cfg

Waterfall: add config for sample return capsule.

---

GameData/RP-0/Contracts/Moon Exploration/Lunar Landing Far Side.cfg

Added notes in contract parameter about landing within 80 deg, as well as contract description, with reference to Lunar Libration

Restrict Far Side Lunar Lander angle to 80 deg

---

GameData/RP-0/Contracts/Early Satellites/Solar Satellite.cfg

Idea is for the contract to have meaningful design and mission considerations rather than have the player slap the smallest solar panel they can find onto the probe.

Rework the FirstSolarSat contract parameters

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
GameData/RP-0/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

Add missing config to ROE-RangerRetro

Add missing config to ROE-RangerRetro

---

Source/CareerLog/CareerLog.cs
Source/CareerLog/CareerLogDto.cs
Source/CareerLog/FailureEvent.cs
Source/CareerLog/LaunchEvent.cs
Source/KerbalConstructionTime/BuildItems/BuildListVessel.cs
Source/KerbalConstructionTime/KCTVesselTracker.cs
Source/KerbalConstructionTime/KerbalConstructionTime.cs
Source/KerbalConstructionTime/Persistence/KCTVesselData.cs
Source/KerbalConstructionTime/Utilities/Utilities.cs
Source/RP0.csproj

* Log LaunchID and store it in KCTVesselTracker vesselmodule
* Add method for logging failures, needs integration from TF/TL
* Also fix inconsistent KCTPersistentID format

Additional CareerLog logging

---

Source/Tooling/ModuleToolingPTank.cs

Adds tooling support for Hollow Cylinder, Hollow Cone and Hollow Fillet Cylinder

Add tooling support for hollow proc parts

---

GameData/RP-0/KCT_Presets/RP1_KCT_Presets.cfg

Add Aniline22 and Aniline37 to KCT resource multipliers

Add aniline mix to KCT

---

GameData/RP-0/Contracts/X-Planes/CrewedFlight.cfg
GameData/RP-0/Contracts/X-Planes/CrewedSupersonic.cfg
Source/CC_RP0/CC_RP0.csproj
Source/CC_RP0/HorizontalLandingFactory.cs
Source/CC_RP0/HorizontalLandingVesselParam.cs

* Add a new CC VesselParam that detects whether the landing was horizontal and with descent angle lower than specified
* Add optional horizontal runway landing objective to X-Planes (Low) and X-Planes (Supersonic) with a small reward

Add optional reward for runway landings with <10° descent angle to XPL and XPSS

---

Source/Crew/CourseTemplate.cs
Source/Crew/CrewHandler.cs
Source/Crew/FSGUI.cs

Caveats;
* Only parts that have been unlocked or are under research, are added to tooltips
* Needed to create courses for parts that are researched but not yet purchased. This includes mission courses.

Add tooltips with part titles to courses

---

GameData/RP-0/Tree/RP0TechTree.cfg

Should be Prototype Spaceplanes.

Correct typo: Prototype Spaceplaces (1965)

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/TREE-Engines.cfg
GameData/RP-0/Tree/TREE-Parts.cfg

Regenerate RP-0 .cfgs to fix parts that were incorrectly placed by the parts browser

Regenerate tree .cfgs

---

GameData/RP-0/KCT/FuelResources.cfg
GameData/RP-0/KCT_Presets/RP1_KCT_Presets.cfg

Add resource cost multipliers for Boranes and Halogens, and add aniline mixes to KCT fuel list (I don't know if this is actually used for anything).

Add KCT configs for more fuel types

---

GameData/RP-0/Science/Experiments/Photography.cfg
GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

Add support for the ROC Zenit camera system. This just models the early Zenit models as the improved film camera.
ROC PR: https://github.com/KSP-RO/ROCapsules/pull/114

Add support for ROC Zenit camera system

---

GameData/RP-0/Tree/RFTechLevels.cfg
GameData/RP-0/Tree/ResourceTechs.cfg

Move PartUpgrades definitions to RO, and patch placement/cost here.
Delete old types (Tank-I..IV)

Tank Definition PartUpgrades

---

.github/workflows/build.yml

Same as https://github.com/KSP-RO/RealismOverhaul/pull/2645

Run build job when secret is available

---

GameData/RP-0/Avionics.cfg
GameData/RP-0/CrewTrainingTimes.cfg
GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
GameData/RP-0/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

Add support for alternative Dynasoar cockpit.
ROC PR: https://github.com/KSP-RO/ROCapsules/pull/121

Add support for Dynasoar alt cockpit

---

GameData/RP-0/Avionics.cfg
GameData/RP-0/CrewTrainingTimes.cfg
GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/RN_Soyuz.json

Add support for new RN Soyuz 7K-OKS and Soyuz-T parts, and improve ECMs of existing ones. Also fix some errors in the crewtraining settings.
RO PR: https://github.com/KSP-RO/RealismOverhaul/pull/2659

Add support for new Soyuz parts

---

.github/workflows/attachReleaseArtifacts.yml
README.md
makeMeta.py

Adds 3 badges that can be clicked; Nighlty build of RP-1, the RO/RP-1 Discord and the diff of commits since latest release. The link to the diff is updated by CI when making releases

Add interactable badges to the README

---

GameData/RP-0/Avionics.cfg
GameData/RP-0/CrewTrainingTimes.cfg
GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

RP-1 Support for Gemini L
Part is in ROCapsules

Add Support for Gemini L

---

GameData/RP-0/Contracts/Early Lunar Probes/LunarFirstOrbiters.cfg
GameData/RP-0/Contracts/Early Lunar Probes/LunarImpactor.cfg
GameData/RP-0/Contracts/Suborbital Rocket Research/SoundingRocketAdvancedBio.cfg
GameData/RP-0/Contracts/Suborbital Rocket Research/SoundingRocketBio.cfg
GameData/RP-0/Contracts/Suborbital Rocket Research/SoundingRocketFilm.cfg

Rep now awarded to contracts after first completion instead of after second completion.

Fix Rep in SR Research and Early Lunar Probes

---

Source/KerbalConstructionTime/GUI/GUI_VesselMerge.cs
Source/KerbalConstructionTime/Utilities/Utilities.cs

Resolve conflict with EC use in recovery formula.

Only discount used engine EC when in editor scene

---

Source/KerbalConstructionTime/BuildItems/BuildListVessel.cs
Source/KerbalConstructionTime/BuildItems/ReconRollout.cs
Source/KerbalConstructionTime/Utilities/Utilities.cs

Runway detection shamelessly stolen from CC_RP0.

Add Runway Recovery Bonus to SPH Recovery

---

GameData/RP-0/Contracts/Earth Satellites/ComTestSat.cfg
GameData/RP-0/Contracts/Earth Satellites/EarlyComSat.cfg
GameData/RP-0/Contracts/Sounding Rockets/DistanceSoundingDifficult.cfg
GameData/RP-0/Contracts/Sounding Rockets/DistanceSoundingIntermediate.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingDifficult.cfg
GameData/RP-0/Contracts/Sounding Rockets/SoundingIntermediate.cfg

Include the reward multiplier factor for cooldown for the repeatable SR and CommSat contracts

Cooldown multiplier for repeatable SR/ComSat

---

GameData/RP-0/Contracts/Programs.cfg
Source/Programs/Requirements.cs

PR to address [KSP-RO/ProgramsIssueTracker#61](https://github.com/KSP-RO/ProgramsIssueTracker/issues/61).
Allow for program requirements description to explicitly state that a contract only needs to be completed once.

Suborbital Research program requirements description

---

Source/Tooling/ModuleToolingPTank.cs

Adds tooling support for https://github.com/KSP-RO/ProceduralParts/pull/319

Add ProcPart Truss tooling

---

.github/workflows/attachReleaseArtifacts.yml
GameData/RP-0/changelog.cfg
RP-0.netkan
processChangeLog.py

Adds a python script that processes the body of a release changelog and converts it into KebralChangelog format and inserts the new release as a node in the config in GameData

Kerbal changelog action

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/TREE-Engines.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json

Add config for the RL10A-3-3B.

Add RL10A-3-3B Config

---

GameData/RP-0/Contracts/Programs.cfg
GameData/RP-0/Localization/en-us.cfg
GameData/RP-0/Strategies/Leaders/LeadersAdmin.cfg
GameData/RP-0/Strategies/Leaders/LeadersContractors.cfg
GameData/RP-0/Strategies/Leaders/LeadersEngineers.cfg
GameData/RP-0/Strategies/Leaders/LeadersScientists.cfg

"Program" and "Leader" are now consistently treated as proper nouns.
Von Braun description now correctly states that he worked for the U.S. Army, and his role in the Saturn V is emphasized.
Slightly expanded EarlyInnerPlanetProbes description
Improved wording in a few places
Conformed style to KSC-DF-107 Revision F, mostly by adding an Oxford comma, though I probably haven't caught everything.

Add Korolev, Morgan descriptions, misc grammar, style fixes

---

Source/Avionics/AvionicsGUI.cs
Source/Avionics/ProceduralAvionicsWindow.cs
Source/CareerLog/CareerLogGUI.cs
Source/Crew/TrainingGUI.cs
Source/KerbalConstructionTime/GUI/GUI_Airlaunch.cs
Source/KerbalConstructionTime/GUI/GUI_BuildList.cs
Source/KerbalConstructionTime/GUI/GUI_BuildPlans.cs
Source/KerbalConstructionTime/GUI/GUI_CrewSelect.cs
Source/KerbalConstructionTime/GUI/GUI_DevParts.cs
Source/KerbalConstructionTime/GUI/GUI_DismantlePad.cs
Source/KerbalConstructionTime/GUI/GUI_Editor.cs
Source/KerbalConstructionTime/GUI/GUI_FirstRun.cs
Source/KerbalConstructionTime/GUI/GUI_Main.cs
Source/KerbalConstructionTime/GUI/GUI_NewLC.cs
Source/KerbalConstructionTime/GUI/GUI_NewPad.cs
Source/KerbalConstructionTime/GUI/GUI_Personnel.cs
Source/KerbalConstructionTime/GUI/GUI_Presets.cs
Source/KerbalConstructionTime/GUI/GUI_Simulation.cs
Source/KerbalConstructionTime/GUI/GUI_Tooltip.cs
Source/KerbalConstructionTime/GUI/GUI_VesselMerge.cs
Source/KerbalConstructionTime/KerbalConstructionTime.cs
Source/Maintenance/MaintenanceGUI.cs
Source/Programs/ProgramHandler.cs
Source/Tooling/ToolingGUI.cs
Source/UI/ContractGUI.cs
Source/UI/Tooltip.cs
Source/UI/TopWindow.cs
Source/UI/UIBase.cs
Source/UI/UIHolder.cs

Uses the same technique as Principia and applies it to both RP0 and KCT UI. Should scale everything but the KCT settings window.

Scale the UI according to KSP settings

---

GameData/RP-0/Strategies/Leaders/LeadersEngineers.cfg

little less clogged on the description. redid the bonus/penalty text.

Redo ValCleaver description, bonus/penalty text

---

GameData/RP-0/ToolingDefinitions.cfg
Source/Tooling/ModuleTooling.cs
Source/Tooling/ModuleToolingDiamLen.cs
Source/Tooling/ModuleToolingPTank.cs
Source/Tooling/ToolingDatabase.cs

Additionally can now configure different factors for cost reducers.

Separate HP and non-HP tooling

---

RP-0.netkan

Some changes to the RP-1 netkan to better reflect the currently often used mods and better agree with the Express install.
Suggestions for further changes are welcome!

Netkan touchups

---

Source/KerbalConstructionTime/GUI/GUI_CrewSelect.cs

Trigger FillAllPodsWithCrew() instead of CrewFirstAvailable()
Ported from https://github.com/KSP-RO/RP-0/pull/1838

Fix KCT not allowing crewing of parts with crew capacity other than the first one found

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Engines.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

For https://github.com/KSP-RO/ROEngines/pull/182

Add support for R103

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Advanced_Jet_Engines.json
Source/Tech Tree/Parts Browser/data/QuizTech_Aero.json
Source/Tech Tree/Parts Browser/data/SXT.json

For https://github.com/KSP-RO/RealismOverhaul/pull/2742

Configure J85-GE-5, SXT F-135

---

GameData/RP-0/ToolingDefinitions.cfg
Source/Tooling/ModuleTooling.cs
Source/Tooling/ModuleToolingDiamLen.cs
Source/Tooling/ModuleToolingPTank.cs
Source/Tooling/ToolingDefinition.cs
Source/Tooling/ToolingGUI.cs
Source/Tooling/ToolingScenario.cs

Needs https://github.com/NathanKell/ModularFuelSystem/pull/299

Add support for titles on tooling

---

GameData/RP-0/Programs/Programs.cfg

Should be merged together with https://github.com/KSP-RO/RP-0/pull/1835

Add contracts to EarthSpaceStation program & add program description

---

GameData/RP-0/Contracts/Lunar Crewed/CrewedMoonLandingTargeted.cfg
GameData/RP-0/Contracts/Mars/Mars Rover.cfg
GameData/RP-0/Contracts/Plutonian Landings/Charon Rover.cfg
GameData/RP-0/Contracts/Plutonian Landings/Pluto Rover.cfg
GameData/RP-0/Contracts/Rovers/Callisto Rover.cfg.DISABLED
GameData/RP-0/Contracts/Rovers/Dione Rover.cfg.DISABLED
GameData/RP-0/Contracts/Rovers/Enceladus Rover.cfg.DISABLED
GameData/RP-0/Contracts/Rovers/Europa Rover.cfg.DISABLED
GameData/RP-0/Contracts/Rovers/Ganymede Rover.cfg.DISABLED
GameData/RP-0/Contracts/Rovers/Iapetus Rover.cfg.DISABLED
GameData/RP-0/Contracts/Rovers/Io Rover.cfg.DISABLED
GameData/RP-0/Contracts/Rovers/Mimas Rover.cfg.DISABLED
GameData/RP-0/Contracts/Rovers/Rhea Rover.cfg.DISABLED
GameData/RP-0/Contracts/Rovers/Tethys Rover.cfg.DISABLED
GameData/RP-0/Contracts/Rovers/Triton Rover.cfg.DISABLED
GameData/RP-0/Contracts/Saturn Observation/Titan Rover.cfg
GameData/RP-0/Contracts/Venus/Venus Rover.cfg

Addresses KSP-RO/ProgramsIssueTracker#107 & other contracts that use WayPoint Parameters.

Fix Waypoint Parameters in Contracts

---

GameData/RP-0/Contracts/Rovers/Callisto Rover.cfg
GameData/RP-0/Contracts/Rovers/Charon Rover.cfg
GameData/RP-0/Contracts/Rovers/Dione Rover.cfg
GameData/RP-0/Contracts/Rovers/Enceladus Rover.cfg
GameData/RP-0/Contracts/Rovers/Europa Rover.cfg
GameData/RP-0/Contracts/Rovers/Ganymede Rover.cfg
GameData/RP-0/Contracts/Rovers/Iapetus Rover.cfg
GameData/RP-0/Contracts/Rovers/Io Rover.cfg
GameData/RP-0/Contracts/Rovers/Mars Rover.cfg
GameData/RP-0/Contracts/Rovers/Mercury Rover.cfg
GameData/RP-0/Contracts/Rovers/Mimas Rover.cfg
GameData/RP-0/Contracts/Rovers/Pluto Rover.cfg
GameData/RP-0/Contracts/Rovers/Rhea Rover.cfg
GameData/RP-0/Contracts/Rovers/Tethys Rover.cfg
GameData/RP-0/Contracts/Rovers/Titan Rover.cfg
GameData/RP-0/Contracts/Rovers/Triton Rover.cfg
GameData/RP-0/Contracts/Rovers/Venus Rover.cfg

Same as #1846 but for the master branch

Fix Waypoint Parameters in Rover Contracts

---

GameData/RP-0/Contracts/Advanced Satellites/GEO Communications Satellites.cfg
GameData/RP-0/Contracts/Advanced Satellites/Molniya Communications Satellites.cfg
GameData/RP-0/Contracts/Advanced Satellites/Tundra Communications Satellites.cfg
GameData/RP-0/Contracts/Weather Sats/Geostationary Weather Sat.cfg
GameData/RP-0/Contracts/Weather Sats/Second Gen Weather Sats.cfg
GameData/RP-0/Contracts/Weather Sats/Sun Sync Weather Sats.cfg

just the final set to start, because they're the more interesting ones:
- they stick around longest
- the slider means their value can swing wildly
example:

Display nominal value of satellite contracts on a cooldown

---

Source/KerbalConstructionTime/GUI/GUI_CrewSelect.cs

Fixes https://discord.com/channels/319857228905447436/512556137380315139/1060500033704837220

Fix KCT CrewSelect not filling properly if multiple same parts on vessel

---

GameData/RP-0/Tree/TREE-Engines.cfg
Source/Tech Tree/Parts Browser/tree_engine_cfg_generator.py

Edit parts browser to properly parse all engine configs, and recompile parts browser .exe to incorporate changes.
Testing would be appreciated, I'm not positive I did this right.

Fix Bimodal Engine Configs

---

GameData/RP-0/Tree/ECM-Parts.cfg
GameData/RP-0/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

Add support for Algol III parts for https://github.com/KSP-RO/ROEngines/pull/184

Add support for Algol III

---

GameData/RP-0/Contracts/Human Records/CrewedAltRecord.cfg
GameData/RP-0/Contracts/Human Records/CrewedCountRecord.cfg
GameData/RP-0/Contracts/Human Records/CrewedDurationRecord.cfg
GameData/RP-0/Contracts/Human Records/CrewedSpeedRecord.cfg

Rework all crewed record contracts such that the parameters are wrapped in a VPG.
Depends on [CC v2.2.2.0](https://github.com/KSP-RO/ContractConfigurator/releases/tag/v2.2.2.0) or newer.

Fix crewed records getting completed when switching to an uncrewed vessel

---

GameData/RP-0/KCT/KCT_ModuleTemplates.cfg
GameData/RP-0/Tree/EjectionSeats.cfg

Depends on https://github.com/KSP-RO/RealismOverhaul/pull/2767

Add basic ejection seat configs

---

GameData/RP-0/Contracts/Earth Satellites/GeoComSatNetwork.cfg
GameData/RP-0/Programs/Programs.cfg

Remove requirement for older contract and update program name

Fix GEO program by removing contract requirement

---

.github/workflows/attachReleaseArtifacts.yml
.github/workflows/build.yml
.gitignore
Source/RP0.csproj
Source/packages.config

Add krafs.publicizer to RP0 project

---

GameData/RP-0/Contracts/Early Satellites/Sun Sync Satellite.cfg

Add a reference to the orbit calculator to try to save players some time from asking for the same thing in discord

Add reference to online orbit calculator to Sun Sync Satellite contract

---

GameData/RP-0/Programs/Programs.cfg

Double reputation reward per year early for sounding rockets and X-planes so it feels more significant

Increase rep reward for early completion

---

GameData/RP-0/Strategies/Leaders/LeadersContractors.cfg
GameData/RP-0/Strategies/Leaders/LeadersSubcontractors.cfg

And change OKB to ОКБ because I tested and it renders fine

Add descriptions to ОКБs

---

GameData/RP-0/Tree/ECM-Engines.cfg
GameData/RP-0/Tree/TREE-Engines.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json

Resolves https://github.com/KSP-RO/RP-0/issues/1862
Needs https://github.com/KSP-RO/RealismOverhaul/pull/2836 to avoid breaking saves

Rename SNTPPFE config to avoid name conflict

---

GameData/RP-0/Contracts/Early Satellites/Sun Sync Satellite.cfg

Shorten the calculator link so it doesn't get commented out

Fix calculator link in Sun Sync Satellite contract

---

GameData/RP-0/Tree/RP0TechTree.cfg

200 fewer sci points needed to unlock the nodes from that era.

Reduce cost for '58 to '64 tech nodes

---

GameData/RP-1/Localization/ru.cfg

Russian localization. For now text from en-us.cfg only

added Russian translation

---

GameData/RP-1/Contracts/Sounding Rockets/DistanceSoundingDifficult.cfg
GameData/RP-1/Contracts/Sounding Rockets/DistanceSoundingIntermediate.cfg

Adjusting tuning - was not tuned with guided requirements in mind

Adjust Distance SR tuning

---

GameData/RP-1/Contracts/Groups.cfg
GameData/RP-1/Contracts/Sounding Rockets/DistanceSoundingDifficult.cfg
GameData/RP-1/Contracts/Sounding Rockets/DistanceSoundingIntermediate.cfg

Each level now increases the distance by 80-90km. The starting point is the same 140km.

Set Distance SR payload to a fixed amount and halve the per-level downrange increase

---

GameData/RP-1/Strategies/Leaders/LeadersContractors.cfg
GameData/RP-1/Strategies/Leaders/LeadersSubcontractors.cfg

Make locked leader disappear properly for subcontractors
Buff a couple contractors slightly
Buff a lot of subcontractors
More to do but this should be a good start

Rebalance RP-1 contractors and subcontractors

---

Source/Avionics/ModuleProceduralAvionics.cs

Needs https://github.com/KSP-RO/RealFuels/pull/326

Properly refresh EC tank parameters in proc avi window when RF tank def gets changed

---

GameData/RP-1/Contracts/Early Satellites (Heavy)/FirstBioSat-Heavy.cfg
GameData/RP-1/Contracts/Early Satellites (Heavy)/FirstPolarSat-Heavy.cfg
GameData/RP-1/Programs/Programs.cfg

Players can now chose between realistic Soviet launch goals and saving virtual dogs. Both contracts can be completed if players want to, but only one of the two is needed to finish the program.

Add polar sat to Early Satellites (Heavy)

---

GameData/RP-1/Contracts/Early Satellites (Light)/AtmosphereAnalysis.cfg

Explain how to complete weather satellite contract using forced run

Explain Forced Run

---

GameData/RP-1/ProcCosts.cfg

Add RP-1 cost multiplier for new fairing side petal option

Add RP-1 cost multiplier for new fairing side petal option

---

GameData/RP-1/Localization/en-us.cfg

I don't understand how facility descriptions work.
This should replace the existing TS descriptions with a new hardcoded text block that contains data more relevant to RA comms. Some code work will still be required to actually put these locs in the correct place.

Better tracking station descriptions

---

GameData/RP-1/Contracts/X-Plane Research/BreakSoundBarrier.cfg

Don't say BtSB needs 350m/s

---

GameData/RP-1/Tree/ECM-Engines.cfg
GameData/RP-1/Tree/ECM-Parts.cfg
GameData/RP-1/Tree/TREE-Engines.cfg
GameData/RP-1/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Engine_Config.json
Source/Tech Tree/Parts Browser/data/ROEngines.json

Vernier solid motor from Pioneer 0/1/2
https://github.com/KSP-RO/ROEngines/pull/215
https://github.com/KSP-RO/RealismOverhaul/pull/2899

RP-1 support for Pioneer Vernier Solid Motor

---

GameData/RP-1/Strategies/Leaders/LeadersContractors.cfg
GameData/RP-1/Strategies/Leaders/LeadersScientists.cfg
GameData/RP-1/Strategies/Leaders/LeadersSubcontractors.cfg

I believe the current values have too big of an impact on vessel integration times.
Ref: https://discord.com/channels/319857228905447436/512556346869284864/1148668671636541573

Lower leader/contractor integration rate bonuses for turbopumps and avionics

---

GameData/RP-1/Contracts/X-Plane Research/RocketPlaneDevelopmentOptional.cfg

Apologies--I really thought I'd tested this after the last time I touched it.

Fix Rocket Plane Development

---

GameData/RP-1/Strategies/Milestones.cfg

Fixing https://github.com/KSP-RO/RP-1/issues/2246

Fix Syncom 3 launch date

---

GameData/RP-1/Contracts/Earth Observation 1/EOSMagScan1.cfg
GameData/RP-1/Science/Experiments/VisibleImaging.cfg

- Corrected MagScan duration title, stated 14 days, requires 45
- Changed Visible Imaging experiments titles to Video Imaging

Grammar tweaks - MagScan and Visible Imaging

---

GameData/RP-1/Tree/ECM-Parts.cfg
GameData/RP-1/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/Ven_Stock_Revamp.json

Add SNAP-3A. Needs https://github.com/KSP-RO/RealismOverhaul/pull/2923

Add SNAP-3A

---

GameData/RP-1/Strategies/Leaders/LeadersAdmin.cfg
GameData/RP-1/Strategies/Leaders/LeadersFlightDirectors.cfg

Correct which award was won by Glushko
Make it clearer what the issue with Von Braun was
Flip an effect that should reduce SPH speed based on the name to reduce it instead of increasing it

Minor leader tweaks

---

GameData/RP-1/Contracts/Earth Crewed/OrbitalTestFlight.cfg

The contract condition is copied from Suborbital Test Flight mission.

Orbital Test Flight (Uncrewed): check that cockpit is pressurized and space-capable

---

GameData/RP-1/Contracts/Earth Crewed/CrewedScienceBasic.cfg
GameData/RP-1/Contracts/Earth Crewed/FirstOrbitCrewed.cfg
GameData/RP-1/Contracts/Earth Crewed/OrbitalFlight1.cfg
GameData/RP-1/Contracts/Earth Crewed/OrbitalTestFlight.cfg
GameData/RP-1/Contracts/Earth Crewed/OrbitalTestFlightAnimal.cfg

Crew pods with ModuleNonReentryRated can no longer complete orbital flight contracts

---

GameData/RP-1/Localization/zh-cn.cfg

add more Simplified Chinesee localization

---

GameData/RP-1/Scenarios/1957Start.cfg
Source/RP0/ConfigurableStart/DateHandler.cs
Source/RP0/ConfigurableStart/PresetPickerGUI.cs
Source/RP0/ConfigurableStart/README.md
Source/RP0/ConfigurableStart/Scenario.cs
Source/RP0/ConfigurableStart/ScenarioHandler.cs
Source/RP0/ConfigurableStart/Utilities.cs
Source/RP0/Debug.cs
Source/RP0/Harmony/MainMenu.cs
Source/RP0/ModIntegrations/TFInterop.cs
Source/RP0/Programs/ProgramHandler.cs
Source/RP0/RP0.csproj
Source/RP0/ScenarioModules/Confidence.cs
Source/RP0/ScenarioModules/FirstStart.cs
Source/RP0/ScenarioModules/UnlockCreditHandler.cs
Source/RP0/Singletons/Database.cs
Source/RP0/SpaceCenter/LaunchComplex/LCData.cs
Source/RP0/Utilities/ScienceUtils.cs

Integrate ConfigurableStart into RP-1 codebase

---

Source/RP0/ConfigurableStart/PresetPickerGUI.cs
Source/RP0/ConfigurableStart/ScenarioHandler.cs

Change all static state in CS to belong to instance

---

GameData/RP-1/Tree/ECM-Parts.cfg
GameData/RP-1/Tree/ROHeatshields.cfg
GameData/RP-1/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROHeatshields.json

RP-1 configs for https://github.com/KSP-RO/ROHeatshields/pull/13

Configs for ROHS HIAD

---

Source/RP0/RP0.csproj
Source/RP0/Settings/SpaceCenterSettings.cs
Source/RP0/SpaceCenter/LaunchComplex/LaunchComplex.cs
Source/RP0/SpaceCenter/Projects/FundTargetProject.cs
Source/RP0/SpaceCenter/Projects/HireStaffProject.cs
Source/RP0/SpaceCenter/SpaceCenterManagement.cs
Source/RP0/UI/KCT/GUI_BuildList.cs
Source/RP0/UI/KCT/GUI_NewLC.cs
Source/RP0/UI/KCT/GUI_Personnel.cs
Source/RP0/UI/MaintenanceGUI.cs
Source/RP0/Utilities/KCTUtilities.cs

Add automated staff hiring

---

GameData/RP-1/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROCapsules.json

For https://github.com/KSP-RO/ROCapsules/pull/174

Add lunar flying vehicle config

---

GameData/RP-1/Tree/RFTechLevels.cfg

Noticed by "pineconez" https://discord.com/channels/319857228905447436/620690446540341261/1250544875691315231
**Unrelated note: At long-term mat sci, there are 2 separate mli upgrade parts, shouldn't these be merged into one?**

Update desc of MLI layer 1

---

Source/RP0/SpaceCenter/Projects/FacilityUpgradeProject.cs
Source/RP0/Utilities/KCTUtilities.cs

Apply facility upgrades even when space center is unloaded

---

GameData/RP-1/CustomBarnKit.cfg
GameData/RP-1/Tree/CommsTechlevels.cfg
GameData/RP-1/Tree/EntryCostModifiers.cfg

For https://github.com/KSP-RO/RealAntennas/pull/26

Add support for RA TL10 (Tracking Station lvl 11)

---

GameData/RP-1/Tree/PFTechLevels.cfg

Let PF itself set it to the smallest possible value.

Do not set PF side density

---

Source/RP0/Avionics/ModuleAvionics.cs
Source/RP0/Avionics/ModuleProceduralAvionics.cs
Source/RP0/Harmony/Vessel.cs
Source/RP0/Properties/AssemblyInfo.cs
Source/RP0/RP0.csproj

Needs https://github.com/KSP-RO/RealAntennas/pull/28

Add option to permanently kill avionics

---

GameData/RP-1/Tree/ECM-Parts.cfg
GameData/RP-1/Tree/TREE-Parts.cfg
GameData/RP-1/Tree/identicalParts.cfg
Source/Tech Tree/Parts Browser/data/Near_Future_Electrical.json
Source/Tech Tree/Parts Browser/data/RLA_Stockalike.json
Source/Tech Tree/Parts Browser/data/ROCapsules.json
Source/Tech Tree/Parts Browser/data/Ven_Stock_Revamp.json

For https://github.com/KSP-RO/RealismOverhaul/pull/3004

Switch to new NFE models and configure new ones

---

GameData/RP-1/Strategies/Leaders/LeadersContractors.cfg

just copied Yvonne's cfg over as suggested, works correctly in game

Fix Bell's researchers hiring penalty

---

GameData/RP-1/Tree/ECM-Parts.cfg
GameData/RP-1/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

for https://github.com/KSP-RO/ROEngines/pull/246

New Veronique configs

---

GameData/RP-1/SpaceCenterSettings.cfg
Source/RP0/Maintenance/MaintenanceHandler.cs
Source/RP0/Settings/SpaceCenterSettings.cs
Source/RP0/SpaceCenter/SpaceCenterManagement.cs
Source/RP0/UI/KCT/GUI_Editor.cs

When no tech nodes are in queue researchers only get 50% of their active salary.

Give idle researchers lower salary

---

GameData/RP-1/Contracts/Commercial Applications 1/FirstMolniyaSat-CA.cfg

resolves https://github.com/KSP-RO/RP-1/issues/2432

Fix Molniya orbit SMA

---

Source/RP0/SpaceCenter/SimulationParams.cs
Source/RP0/SpaceCenter/SpaceCenterManagement.cs
Source/RP0/UI/KCT/GUI_Simulation.cs

* Separate Ap and Pe (including negative values to easily yeet stuff into the atmosphere!)
* LAN

Add additional orbital parameters to sim UI

---

Source/Tech Tree/Parts Browser/README.md

This info is based on these messages from Kirk:
https://discord.com/channels/319857228905447436/620690446540341261/1227283136988053586
https://discord.com/channels/319857228905447436/620690446540341261/1355311201134837781
I don't really know if this is right or not (or if it needs additional elaboration), so I am hoping that Kirk (or someone else) can review this.

Update README of parts browser

---

Source/RP0/RP0.csproj
Source/RP0/SpaceCenter/LaunchComplex/LCLaunchPad.cs
Source/RP0/SpaceCenter/LaunchComplex/LaunchComplex.cs
Source/RP0/SpaceCenter/SCMEvents.cs
Source/RP0/SpaceCenter/SpaceCenterManagement.cs
Source/RP0/UI/KCT/GUI_BuildList.cs
Source/RP0/UI/KCT/GUI_DismantlePadOrLC.cs
Source/RP0/UI/KCT/GUI_Main.cs

Keep track of prelaunch vessels for rollout and dismantle checks

---

GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_paris_moscow_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_soviet_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_transatlantic_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/intermittent_transpacific_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/syncom_ship_to_shore.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/syncom_transatlantic_tv.cfg
GameData/RP-1/Contracts/Skopos Commercial Applications 0/syncom_transpacific_tv.cfg

Add some lines to the experimental Skopos contracts encouraging the player to open the Skopos window, as well as add a little more detail on the level of service expected (not much) for the Skopos contracts.

Gently encourage the player to actually open the Skopos window

---

GameData/RP-1/Science/Configure.cfg
GameData/RP-1/Science/Experiments/BioSample.cfg
GameData/RP-1/Science/Experiments/CrewScience/BasicCapsuleExperiments.cfg
GameData/RP-1/Science/Experiments/CrewScience/CockpitExperiments.cfg
GameData/RP-1/Science/Experiments/CrewScience/MatureCapsuleExperiments.cfg
GameData/RP-1/Science/Experiments/CrewScience/SecondGenExperiments.cfg
GameData/RP-1/Science/Experiments/CrewScience/StationExperiments.cfg
GameData/RP-1/Science/Experiments/EVAReport.cfg
GameData/RP-1/Science/Experiments/GlobalExperimentPatches.cfg
GameData/RP-1/Science/Experiments/ImagingSpectrometry.cfg
GameData/RP-1/Science/Experiments/InfraredRadiometry.cfg
GameData/RP-1/Science/Experiments/MagneticScan.cfg
GameData/RP-1/Science/Experiments/MassSpectrometry.cfg
GameData/RP-1/Science/Experiments/Micrometeorite.cfg
GameData/RP-1/Science/Experiments/OrbitalPerturbation.cfg
GameData/RP-1/Science/Experiments/Photography.cfg
GameData/RP-1/Science/Experiments/PressureScan.cfg
GameData/RP-1/Science/Experiments/RPWS.cfg
GameData/RP-1/Science/Experiments/SurfaceSample.cfg
GameData/RP-1/Science/Experiments/TelemetryAnalysis.cfg
GameData/RP-1/Science/Experiments/Temperature.cfg
GameData/RP-1/Science/Experiments/VisibleImaging.cfg
GameData/RP-1/Science/HardDriveConfigs.cfg
GameData/RP-1/Science/ScienceLabs.cfg

Most of the science configs are not consistent with their indentation  - this PR aims to fix that.

Fix Science Config Indentation

---

Source/Tech Tree/Parts Browser/data/Cryo_Engines.json

Thanks to [UndeckedTrash87](https://discord.com/channels/319857228905447436/620690446540341261/1398095461050613770)
Related: https://github.com/KSP-RO/RealismOverhaul/pull/3080

Update Vulcain description

---

Source/RP0/CareerLog/CareerLog.cs
Source/RP0/Programs/Program.cs
Source/RP0/Programs/ProgramHandlerSettings.cs
Source/RP0/Properties/AssemblyInfo.cs
Source/RP0/ScenarioModules/Confidence.cs
Source/RP0/Settings/SpaceCenterSettings.cs
Source/RP0/SpaceCenter/LaunchComplex/LCEfficiency.cs
Source/RP0/SpaceCenter/Projects/ConstructionProject.cs
Source/RP0/SpaceCenter/Projects/ResearchProject.cs
Source/RP0/SpaceCenter/SpaceCenterManagement.cs
Source/RP0/UI/ConfidenceWidget.cs
Source/RP0/UI/KCT/GUI_BuildList.cs
Source/RP0/Utilities/Formula.cs

Use HermiteCurve, use doubles instead of floats

---

GameData/RP-1/Tree/ECM-Parts.cfg
GameData/RP-1/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROEngines.json

Add Castor 4A

---

GameData/RP-1/Parts/Science/PHOTO02-BasicFilmCamera.cfg
GameData/RP-1/Parts/Science/PHOTO03-ImprovedFilmCamera.cfg
GameData/RP-1/Parts/Science/PHOTO04-HighResFilmCamera.cfg
GameData/RP-1/Science/Experiments/Photography.cfg

* Remove section in PH04 part description that said it can be transmitted digitally (thanks [jimmymcgoochie](https://discord.com/channels/319857228905447436/620690446540341261/1409466882624589877))
* Add a description for the PH02 part
* Slightly change PH03 part description
* Add description for PH05 experiment

Various changes to photography parts/experiments

---

GameData/RP-1/Tree/ECM-Parts.cfg
GameData/RP-1/Tree/TREE-Parts.cfg
Source/Tech Tree/Parts Browser/data/ROEnginesExtended.json

Fix ROEE AR2 name

---

GameData/RP-1/Strategies/Leaders/LeadersAdmin.cfg
GameData/RP-1/Strategies/Leaders/LeadersEngineers.cfg
GameData/RP-1/Strategies/Leaders/LeadersFlightDirectors.cfg
GameData/RP-1/Strategies/Leaders/LeadersSubcontractors.cfg

Try to give the admins more interesting effects, hopefully now most of them are interesting to consider
Rebalance Von Braun as an engineer, as he's overpowered in that role
Similarly rebalance Kraft, as his effects were too broad for that category
Explain what Morgan does a bit better
Slightly buff Aerojet, as it seemed a bit weak

Rebalance leaders

---

Source/RP0/Crew/CrewHandler.cs
Source/RP0/Crew/TrainingCourse.cs
Source/RP0/ScenarioModules/UnlockCreditHandler.cs
Source/RP0/Settings/GameParameters.cs

TODO: figure out what the per-preset default values should be

Add difficulty settings for unlock credit and training rates
